// GENERATED BY `keel sync` — DO NOT EDIT BY HAND.
// Source: packages/contracts/modules/*/keel.module.json and */deployments/*.json

/** Reusable protocol infrastructure. Each module ships as its own repository. */
export type KeelModuleId = "keel-kernel" | "keel-codecs" | "keel-hold" | "keel-artifacts" | "keel-graph" | "keel-harness" | "keel-presentation" | "keel-die" | "keel-creator-identity" | "keel-mint-access" | "keel-equipment" | "keel-market" | "keel-anchors" | "keel-crucible" | "keel-ip-control" | "keel-sleeve" | "keel-web3-url" | "keel-cross-chain-mint" | "keel-stake";

/**
 * Concrete products built on the modules. Apps consume modules exactly as an
 * outside integrator does, and no module may depend on one.
 */
export type KeelAppId = "keel-canvas" | "cool-s" | "line" | "vault-runner";

/** Anything with contracts on a chain — a module or an app. */
export type KeelUnitId = KeelModuleId | KeelAppId;

/** Role labels units are grouped and browsed by. */
export type KeelModuleGroup = "apps" | "assets" | "core" | "market" | "provenance" | "render" | "token";

export interface KeelModule {
  readonly id: KeelUnitId;
  /** "module" is reusable infrastructure; "app" is a product built on it. */
  readonly kind: "module" | "app";
  readonly title: string;
  /** Role label; the topic this module's repository is tagged with. */
  readonly group: KeelModuleGroup;
  readonly summary: string;
  readonly version: string;
  /** Repository this module is published from once split out of the monorepo. */
  readonly repo: string | null;
  /** Repository visibility, when known. Affects installation, not resolution. */
  readonly visibility: "public" | "private" | null;
  readonly deps: readonly KeelUnitId[];
  readonly contracts: readonly string[];
  /** Contracts with creation bytecode — the ones a release actually deploys. */
  readonly deployable: readonly string[];
}

export interface KeelDeployment {
  readonly module: KeelUnitId;
  readonly chainId: number;
  /** Named instance: one chain can carry several deployments of a module. */
  readonly instance: string;
  readonly contract: string;
  readonly address: `0x${string}`;
  readonly block: string | null;
  readonly txHash: string | null;
}

export const KEEL_MODULES: readonly KeelModule[] = [
  {
    "id": "keel-kernel",
    "kind": "module",
    "title": "Kernel",
    "group": "core",
    "visibility": "private",
    "summary": "Admin/access primitives and encoding helpers every other module is allowed to import.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-kernel",
    "deps": [],
    "contracts": [
      "SafeAdminAccessControl.sol",
      "libraries/JsonEscape.sol",
      "libraries/KeelCodeIdentity.sol",
      "libraries/KeelCollectionFreezeValidation.sol",
      "libraries/KeelUriEscape.sol",
      "KeelFeeTreasury.sol",
      "libraries/KeelPlatformFees.sol",
      "libraries/KeelGovernance.sol",
      "KeelAccessGroups.sol",
      "KeelLocalPause.sol",
      "libraries/KeelPause.sol",
      "libraries/KeelTokenURIEnvelope.sol",
      "libraries/KeelMintSeeded.sol",
      "interfaces/IKeelMintSeededErrors.sol",
      "interfaces/IKeelMintSeededData.sol",
      "interfaces/IKeelGovernanceErrors.sol",
      "interfaces/IKeelAccessGroupErrors.sol",
      "interfaces/IKeelAccessGroupEvents.sol",
      "KeelRecoveryGroups.sol",
      "interfaces/IKeelRecoveryErrors.sol"
    ],
    "deployable": [
      "KeelFeeTreasury",
      "KeelAccessGroups",
      "KeelRecoveryGroups"
    ]
  },
  {
    "id": "keel-codecs",
    "kind": "module",
    "title": "Codecs",
    "group": "core",
    "visibility": "private",
    "summary": "Pure, stateless decoders: RLP, Merkle-Patricia, block headers, IPFS CIDs, base32/58, BLS12-381.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-codecs",
    "deps": [],
    "contracts": [
      "libraries/KeelRlp.sol",
      "libraries/KeelBlockHeader.sol",
      "libraries/KeelMerklePatricia.sol",
      "libraries/KeelEthAccount.sol",
      "libraries/KeelOpOutputRoot.sol",
      "libraries/KeelIpfsCid.sol",
      "libraries/KeelDagPb.sol",
      "libraries/KeelBase32.sol",
      "libraries/KeelBase58.sol",
      "libraries/Bls12381.sol"
    ],
    "deployable": []
  },
  {
    "id": "keel-hold",
    "kind": "module",
    "title": "Storage",
    "group": "core",
    "visibility": "private",
    "summary": "Immutable content-addressed chunk storage and the artifact registry that activates revisions.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-hold",
    "deps": [
      "keel-kernel"
    ],
    "contracts": [
      "KeelHold.sol",
      "Ingot.sol",
      "KeelIndex.sol",
      "interfaces/IKeelHold.sol",
      "interfaces/IKeelHoldLimits.sol",
      "interfaces/IKeelHoldSeal.sol",
      "libraries/KeelSealValidation.sol",
      "libraries/KeelCastDispatch.sol",
      "interfaces/IKeelIndex.sol",
      "interfaces/IKeelHoldHarness.sol",
      "interfaces/IKeelHoldEvents.sol",
      "libraries/KeelHoldMetadata.sol",
      "interfaces/IKeelHoldErrors.sol",
      "interfaces/IKeelIndexErrors.sol",
      "interfaces/IKeelIndexEvents.sol"
    ],
    "deployable": [
      "Ingot",
      "KeelHold",
      "KeelIndex"
    ]
  },
  {
    "id": "keel-artifacts",
    "kind": "module",
    "title": "Object model",
    "group": "core",
    "visibility": "private",
    "summary": "The Keel object graph: objects, viewers, links, seeds, and the manager that fronts them.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-artifacts",
    "deps": [
      "keel-hold",
      "keel-kernel"
    ],
    "contracts": [
      "KeelArtifactRegistry.sol",
      "KeelManager.sol",
      "KeelManagerProxy.sol",
      "KeelHarnessRegistry.sol",
      "KeelLinkRegistry.sol",
      "KeelSeedRegistry.sol",
      "interfaces/IKeelMintSeedSource.sol",
      "interfaces/IKeelSeedRegistryErrors.sol",
      "interfaces/IKeelSeedRegistryEvents.sol",
      "interfaces/IKeelArtifactRegistry.sol",
      "interfaces/IKeelManager.sol",
      "interfaces/IKeelArtifactRevisionPolicy.sol",
      "interfaces/IKeelHarnessRegistry.sol",
      "interfaces/IKeelHarnessRegistryErrors.sol",
      "interfaces/IKeelHarnessRegistryEvents.sol",
      "KeelManagerRecovery.sol",
      "KeelManagerRpcPolicy.sol",
      "interfaces/IKeelManagerErrors.sol",
      "interfaces/IKeelManagerEvents.sol",
      "interfaces/IKeelManagerRecoveryErrors.sol",
      "interfaces/IKeelManagerRecoveryEvents.sol",
      "interfaces/IKeelManagerRpcErrors.sol",
      "interfaces/IKeelManagerRpcEvents.sol",
      "interfaces/IKeelManagerTypes.sol",
      "libraries/KeelManagerGovernorState.sol",
      "KeelLinkURIBuilder.sol",
      "interfaces/IKeelLinkURIBuilder.sol",
      "interfaces/IKeelLinkURIBuilderErrors.sol",
      "interfaces/IKeelLinkRegistryErrors.sol",
      "interfaces/IKeelLinkRegistryEvents.sol"
    ],
    "deployable": [
      "KeelArtifactRegistry",
      "KeelHarnessRegistry",
      "KeelLinkRegistry",
      "KeelManager",
      "KeelManagerProxy",
      "KeelSeedRegistry",
      "KeelManagerRecovery",
      "KeelManagerRpcPolicy"
    ]
  },
  {
    "id": "keel-graph",
    "kind": "module",
    "title": "Graph trust lattice",
    "group": "core",
    "visibility": "private",
    "summary": "Graph/plugin/library/module registries \u2014 the on-chain trust lattice the runtime re-derives against.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-graph",
    "deps": [],
    "contracts": [
      "KeelGraphRegistry.sol",
      "KeelPluginRegistry.sol",
      "KeelModuleReviewRegistry.sol",
      "KeelLibraryRegistry.sol",
      "KeelAssetTagRegistry.sol",
      "interfaces/IKeelGraphRegistry.sol",
      "interfaces/IKeelContractPlugin.sol"
    ],
    "deployable": [
      "KeelAssetTagRegistry",
      "KeelGraphRegistry",
      "KeelLibraryRegistry",
      "KeelModuleReviewRegistry",
      "KeelPluginRegistry"
    ]
  },
  {
    "id": "keel-harness",
    "kind": "module",
    "title": "On-chain HTML builder",
    "group": "render",
    "visibility": "private",
    "summary": "Assembles viewer HTML from chunk-stored resources entirely on chain.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-harness",
    "deps": [
      "keel-hold",
      "keel-kernel"
    ],
    "contracts": [
      "KeelHarnessBuilder.sol",
      "KeelPercentTokenURIBuilder.sol",
      "interfaces/IKeelHarnessBuilder.sol",
      "interfaces/IKeelPercentTokenURIBuilder.sol",
      "libraries/KeelHarnessContextDispatch.sol",
      "libraries/KeelPreEncodedTokenURI.sol",
      "libraries/KeelPreparedTokenURI.sol",
      "KeelObjectURIBuilder.sol",
      "KeelRawTokenURIBuilder.sol",
      "interfaces/IKeelObjectURIBuilder.sol",
      "interfaces/IKeelRawTokenURIBuilder.sol"
    ],
    "deployable": [
      "KeelHarnessBuilder",
      "KeelPercentTokenURIBuilder",
      "KeelObjectURIBuilder",
      "KeelRawTokenURIBuilder"
    ]
  },
  {
    "id": "keel-presentation",
    "kind": "module",
    "title": "Presentation state",
    "group": "core",
    "visibility": "private",
    "summary": "Presentation/visual state ledgers that record what a token currently renders as.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-presentation",
    "deps": [],
    "contracts": [
      "KeelPresentationStateRegistry.sol",
      "KeelVisualStateLedger.sol",
      "interfaces/IKeelPresentationRegistry.sol"
    ],
    "deployable": [
      "KeelPresentationStateRegistry",
      "KeelVisualStateLedger"
    ]
  },
  {
    "id": "keel-die",
    "kind": "module",
    "title": "Token base",
    "group": "token",
    "visibility": "private",
    "summary": "Compact creator-owned ERC-721/ERC-1155 collections, a shared multi-creator ERC-1155, renderer boundaries, and factories that organize them.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-die",
    "deps": [
      "keel-kernel",
      "keel-harness",
      "keel-presentation",
      "keel-artifacts",
      "keel-hold"
    ],
    "contracts": [
      "KEEL721.sol",
      "KeelMintSeeded721.sol",
      "KeelMintSeeded721A.sol",
      "KEEL721Deployer.sol",
      "KeelFactory.sol",
      "KeelFactorySepolia.sol",
      "KeelCreator721.sol",
      "KeelCreator721A.sol",
      "KeelCreator1155.sol",
      "KeelShared1155.sol",
      "KeelCreatorFactory.sol",
      "KeelArtifactTokenRenderer.sol",
      "interfaces/IKeelMintable.sol",
      "interfaces/IKeelMintDataSource.sol",
      "interfaces/IKeelMintCapacity.sol",
      "interfaces/IKeelCampaignAuthorizer.sol",
      "interfaces/IKeelItemMintTarget.sol",
      "interfaces/IKeelTokenRenderer.sol",
      "interfaces/IKeelCreatorDirectory.sol",
      "KeelRawPrepared721.sol"
    ],
    "deployable": [
      "KEEL721",
      "KEEL721Deployer",
      "KeelArtifactTokenRenderer",
      "KeelCreator1155",
      "KeelCreator721",
      "KeelCreator721A",
      "KeelCreatorFactory",
      "KeelFactory",
      "KeelFactorySepolia",
      "KeelShared1155",
      "KeelRawPrepared721"
    ]
  },
  {
    "id": "keel-creator-identity",
    "kind": "module",
    "title": "Creator identity",
    "group": "token",
    "visibility": "private",
    "summary": "Creator profiles, commitments, and attribution records.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-creator-identity",
    "deps": [
      "keel-artifacts",
      "keel-kernel"
    ],
    "contracts": [
      "KeelCreatorProfileRegistry.sol",
      "KeelCreatorCommitmentRegistry.sol",
      "KeelAttributionRegistry.sol",
      "interfaces/IKeelCreatorProfileRegistry.sol"
    ],
    "deployable": [
      "KeelAttributionRegistry",
      "KeelCreatorCommitmentRegistry",
      "KeelCreatorProfileRegistry"
    ]
  },
  {
    "id": "keel-mint-access",
    "kind": "module",
    "title": "Mint access",
    "group": "token",
    "visibility": "private",
    "summary": "Shared creator-registered mint routes and custom hooks for every KEEL-controlled minter, plus campaign, OneMint, and Fray Auction controllers.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-mint-access",
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-creator-identity"
    ],
    "contracts": [
      "FrayAuctionIssuer.sol",
      "KeelMintGate.sol",
      "KeelMintRouteRegistry.sol",
      "OneMintController.sol",
      "OpenOneMintController.sol",
      "interfaces/IKeelAccessGate.sol",
      "interfaces/IKeelMintAdapter.sol",
      "interfaces/IKeelMintHook.sol",
      "interfaces/IKeelMintRouteRegistry.sol"
    ],
    "deployable": [
      "FrayAuctionIssuer",
      "KeelMintGate",
      "KeelMintRouteRegistry",
      "OneMintController",
      "OpenOneMintController"
    ]
  },
  {
    "id": "keel-equipment",
    "kind": "module",
    "title": "Equipment",
    "group": "assets",
    "visibility": "private",
    "summary": "Token-owned equipment: inventory custody, distribution lanes, reservations, and one-use duplication.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-equipment",
    "deps": [
      "keel-kernel",
      "keel-artifacts",
      "keel-hold"
    ],
    "contracts": [
      "KeelEquipmentInventory.sol",
      "KeelEquipmentDistributor.sol",
      "KeelEquipmentReservationEngine.sol",
      "KeelEquipmentDescriptorValidator.sol",
      "KeelEquipmentInventoryReader.sol",
      "KeelOneUseDuplicator.sol",
      "interfaces/IKeelERC1155EquipmentDescriptor.sol",
      "interfaces/IKeelReservableMint1155.sol",
      "libraries/KeelMintBoundEquipmentProvision.sol"
    ],
    "deployable": [
      "KeelEquipmentDescriptorValidator",
      "KeelEquipmentDistributor",
      "KeelEquipmentInventory",
      "KeelEquipmentInventoryReader",
      "KeelEquipmentReservationEngine",
      "KeelOneUseDuplicator"
    ]
  },
  {
    "id": "keel-market",
    "kind": "module",
    "title": "Market",
    "group": "market",
    "visibility": "private",
    "summary": "The Keel marketplace plugin contract.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-market",
    "deps": [
      "keel-graph",
      "keel-kernel"
    ],
    "contracts": [
      "KeelMarket.sol"
    ],
    "deployable": [
      "KeelMarket"
    ]
  },
  {
    "id": "keel-anchors",
    "kind": "module",
    "title": "Anchors",
    "group": "provenance",
    "visibility": "private",
    "summary": "Cross-chain and off-chain anchoring: attested/portable anchors, L2 state proofs, zk backends, oracle verifiers.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-anchors",
    "deps": [
      "keel-kernel",
      "keel-codecs",
      "keel-artifacts",
      "keel-graph"
    ],
    "contracts": [
      "KeelAttestedAnchorRegistry.sol",
      "KeelPortableAnchorRegistry.sol",
      "KeelAnchorReplicationBridge.sol",
      "KeelL2AnchorVerifier.sol",
      "KeelL2StateVerifier.sol",
      "KeelSettlementRegistry.sol",
      "KeelZkAnchorVerifier.sol",
      "KeelZkVerifyProofBackend.sol",
      "KeelZkVerifyProofVerifier.sol",
      "KeelSp1GatewayProofBackend.sol",
      "KeelSp1GatewayProofVerifier.sol",
      "KeelIpfsCidVerifier.sol",
      "KeelChainlinkFunctionsVerifier.sol",
      "KeelCreReportVerifier.sol",
      "KeelLocalFunctionsRouter.sol",
      "KeelNodeRegistry.sol",
      "interfaces/IKeelAnchorProofBackend.sol",
      "interfaces/IKeelAnchorProofVerifier.sol",
      "interfaces/IKeelAnchoredChainQueries.sol",
      "interfaces/IKeelSettlementSource.sol"
    ],
    "deployable": [
      "KeelAnchorReplicationBridge",
      "KeelAttestedAnchorRegistry",
      "KeelChainlinkFunctionsVerifier",
      "KeelCreReportVerifier",
      "KeelIpfsCidVerifier",
      "KeelL2AnchorVerifier",
      "KeelL2StateVerifier",
      "KeelLocalFunctionsRouter",
      "KeelNodeRegistry",
      "KeelPortableAnchorRegistry",
      "KeelSettlementRegistry",
      "KeelSp1GatewayProofBackend",
      "KeelSp1GatewayProofVerifier",
      "KeelZkAnchorVerifier",
      "KeelZkVerifyProofBackend",
      "KeelZkVerifyProofVerifier"
    ]
  },
  {
    "id": "keel-crucible",
    "kind": "module",
    "title": "Collection verification",
    "group": "provenance",
    "visibility": "private",
    "summary": "Third-party collection attestation, URI/pixel fingerprints, community replication, and preservation bounties.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-crucible",
    "deps": [
      "keel-kernel",
      "keel-hold",
      "keel-artifacts"
    ],
    "contracts": [
      "KeelCollectionVerificationRegistry.sol",
      "KeelCollectionVerificationHookBase.sol",
      "KeelCollectionAttestationRegistry.sol",
      "KeelUriAttestationRegistry.sol",
      "KeelPixelFingerprintRegistry.sol",
      "KeelCommunityReplicationRegistry.sol",
      "interfaces/IKeelCollectionVerificationHook.sol",
      "interfaces/IKeelCollectionVerificationAdapter.sol",
      "interfaces/ICommunityHold.sol"
    ],
    "deployable": [
      "KeelCollectionAttestationRegistry",
      "KeelCollectionVerificationRegistry",
      "KeelCommunityReplicationRegistry",
      "KeelPixelFingerprintRegistry",
      "KeelUriAttestationRegistry"
    ]
  },
  {
    "id": "keel-ip-control",
    "kind": "module",
    "title": "IP control",
    "group": "provenance",
    "visibility": "private",
    "summary": "On-chain IP rights control, wrapped-721 custody, and the executor that acts on granted rights.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-ip-control",
    "deps": [
      "keel-hold",
      "keel-artifacts",
      "keel-kernel"
    ],
    "contracts": [
      "KeelIPControl.sol",
      "KeelIPActionExecutor.sol",
      "KeelIPWrapped721.sol",
      "interfaces/IKeelIPControl.sol",
      "interfaces/IKeelIPMintTarget.sol"
    ],
    "deployable": [
      "KeelIPActionExecutor",
      "KeelIPControl",
      "KeelIPWrapped721"
    ]
  },
  {
    "id": "keel-sleeve",
    "kind": "module",
    "title": "Metadata resolver",
    "group": "core",
    "visibility": "private",
    "summary": "Token JSON resolution for collections that delegate metadata assembly.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-sleeve",
    "deps": [],
    "contracts": [
      "KeelSleeve.sol",
      "interfaces/IKeelTokenJSONResolver.sol"
    ],
    "deployable": [
      "KeelSleeve"
    ]
  },
  {
    "id": "keel-web3-url",
    "kind": "module",
    "title": "web3:// adapter",
    "group": "render",
    "visibility": "private",
    "summary": "ERC-5219/7617 resource adapter exposing Keel content over web3:// URLs, plus its demos.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-web3-url",
    "deps": [
      "keel-hold"
    ],
    "contracts": [
      "KeelWeb3ResourceAdapter.sol",
      "interfaces/IDecentralizedApp.sol",
      "interfaces/IERC7572.sol"
    ],
    "deployable": [
      "KeelWeb3ResourceAdapter"
    ]
  },
  {
    "id": "keel-cross-chain-mint",
    "kind": "module",
    "title": "Cross-chain mint",
    "group": "token",
    "visibility": "private",
    "summary": "Bridged mint intents and the batcher that carries them between chains.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-cross-chain-mint",
    "deps": [
      "keel-kernel",
      "keel-mint-access",
      "keel-hold"
    ],
    "contracts": [
      "KeelCrossChainMintBridge.sol",
      "KeelCarrierBatcher.sol",
      "KeelHistoryPublicationJob.sol",
      "KeelPublicationJob.sol"
    ],
    "deployable": [
      "KeelCarrierBatcher",
      "KeelCrossChainMintBridge",
      "KeelHistoryPublicationJob",
      "KeelPublicationJob"
    ]
  },
  {
    "id": "keel-stake",
    "kind": "module",
    "title": "Stake objects",
    "group": "assets",
    "visibility": "private",
    "summary": "Stake-object custody and the seasonal grove state that consumes it.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-stake",
    "deps": [
      "keel-artifacts"
    ],
    "contracts": [
      "KeelStakeObjectManager.sol"
    ],
    "deployable": [
      "KeelStakeObjectManager"
    ]
  }
] as const;

/** Products built on the modules; excluded from the module registry by design. */
export const KEEL_APPS: readonly KeelModule[] = [
  {
    "id": "keel-canvas",
    "kind": "app",
    "title": "Canvas",
    "group": "apps",
    "visibility": null,
    "summary": "Shared canvas renderer/splitter/composer surface that both CoolS and LINE collections render through.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-artifacts"
    ],
    "contracts": [
      "CoolSCanvas721.sol",
      "CoolSCanvasRenderer.sol",
      "CoolSCanvasSplitter.sol",
      "CoolSCanvasMintController.sol",
      "CoolSComposer.sol",
      "interfaces/ICoolSCanvasRenderer.sol",
      "interfaces/ICoolSCanvasSplitter.sol",
      "interfaces/ICoolSCanvasView.sol",
      "interfaces/ILINE721.sol",
      "interfaces/ILINEThumbnailSource.sol",
      "libraries/CoolSCanvasStorage.sol"
    ],
    "deployable": [
      "CoolSCanvas721",
      "CoolSCanvasMintController",
      "CoolSCanvasRenderer",
      "CoolSCanvasSplitter",
      "CoolSComposer"
    ]
  },
  {
    "id": "cool-s",
    "kind": "app",
    "title": "CoolS",
    "group": "apps",
    "visibility": null,
    "summary": "The CoolS collection: generative mint hook, metadata renderer, release resolver, novelty ledger, visual registry.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-equipment",
      "keel-presentation"
    ],
    "contracts": [
      "CoolS721.sol",
      "CoolSMetadataRendererV1.sol",
      "CoolSNoveltyLedgerV1.sol",
      "CoolSReleaseResolverV1.sol",
      "CoolSTargetTableV1.sol",
      "CoolSVisualRegistryV1.sol",
      "CoolSLocalVRFCoordinator.sol",
      "KeelGenerativeMintHookBase.sol",
      "interfaces/ICoolSReleaseResolverV1.sol",
      "libraries/CoolSVisualStateCodecV1.sol"
    ],
    "deployable": [
      "CoolS721",
      "CoolSLocalVRFCoordinator",
      "CoolSMetadataRendererV1",
      "CoolSNoveltyLedgerV1",
      "CoolSReleaseResolverV1",
      "CoolSTargetTableV1",
      "CoolSVisualRegistryV1"
    ]
  },
  {
    "id": "line",
    "kind": "app",
    "title": "LINE",
    "group": "apps",
    "visibility": null,
    "summary": "The LINE collection and its on-chain thumbnail renderer.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-die",
      "keel-canvas",
      "keel-artifacts"
    ],
    "contracts": [
      "LINE721.sol",
      "LINEThumbnail.sol",
      "LINEThumbnailRenderer.sol"
    ],
    "deployable": [
      "LINE721",
      "LINEThumbnail",
      "LINEThumbnailRenderer"
    ]
  },
  {
    "id": "vault-runner",
    "kind": "app",
    "title": "Vault Runner",
    "group": "apps",
    "visibility": null,
    "summary": "The Vault Runner game system: characters, packs, items, arcade/achievement registries, run settlement, map auctions.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-artifacts",
      "keel-hold",
      "keel-equipment",
      "keel-crucible",
      "keel-harness"
    ],
    "contracts": [
      "VaultCharacter721.sol",
      "VaultCharacterMetadataRenderer.sol",
      "VaultCharacterRegistry.sol",
      "VaultCharacterPackV2.sol",
      "VaultCharacterStarterPack.sol",
      "VaultItem1155.sol",
      "VaultGameCard.sol",
      "VaultArcadeRegistry.sol",
      "VaultAchievementRegistry.sol",
      "VaultMapAuction.sol",
      "VaultRunLeaderboard.sol",
      "VaultRunLootExtraction.sol",
      "VaultRunSignatureAuthority.sol",
      "VaultSpriteAssetRegistry.sol",
      "interfaces/IVaultRunSource.sol",
      "interfaces/IVaultHardcoreRunSource.sol",
      "interfaces/IVaultRunSignatureAuthority.sol"
    ],
    "deployable": [
      "VaultAchievementRegistry",
      "VaultArcadeRegistry",
      "VaultCharacter721",
      "VaultCharacterMetadataRenderer",
      "VaultCharacterPackV2",
      "VaultCharacterRegistry",
      "VaultCharacterStarterPack",
      "VaultGameCard",
      "VaultItem1155",
      "VaultMapAuction",
      "VaultRunLeaderboard",
      "VaultRunLootExtraction",
      "VaultRunSignatureAuthority",
      "VaultSpriteAssetRegistry"
    ]
  }
] as const;

export const KEEL_DEPLOYMENTS: readonly KeelDeployment[] = [
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelArtifactRegistry",
    "address": "0x137965e2cf635b065ec676d0f706d797a844a8a2",
    "block": "11476939",
    "txHash": "0x77d4e92e2beaa236bc7505b1aa02db7040f127a84a1bd5f688ce8a06c98cb2fc"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelHarnessRegistry",
    "address": "0x7890077a2ad124f3412a946f84c8c4802ad93cb0",
    "block": "11476941",
    "txHash": "0x58c29362d208f72457e1c204e26a8fea2c4d72f64fdf1cf60f5aadceaf8ad657"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelLinkRegistry",
    "address": "0x762fe971dba1e77c5cc7ca7e82b3ccd0e2e3135d",
    "block": "11476943",
    "txHash": "0x4b4b2771512b3a809a276ca19b713e6cfcfeb6dbad4663e956b71614d1ef7245"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelManager",
    "address": "0x9be5cd3af690948472a614aa9b5aba97b29736b7",
    "block": "11476922",
    "txHash": "0xf201adb7424eed1844591f27411b761d120325dfa39abac03e70c93f768c3000"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelManagerProxy",
    "address": "0x7cb6d62cdd968ba45a8a1f0d99a02e5e274fe6e3",
    "block": "11476924",
    "txHash": "0xd651408d7ec6f222aa5a47655ce34e7f92fd02a92c58bee1f1f69c69d25455c2"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelSeedRegistry",
    "address": "0x8d614a10631ee201997efd81a31e8b029869f8f6",
    "block": "11476945",
    "txHash": "0x838f690a9ed7ff3a365cdc957b950e04d2e72d06b65007f8ab24486787e45a31"
  },
  {
    "module": "keel-creator-identity",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelCreatorProfileRegistry",
    "address": "0xa4112eda52ca519adaeebee7c12c4770594529fa",
    "block": "11476926",
    "txHash": "0x09edbc01e0f41681c211e2781d54ba5f8a7931ea14224bb730b24773365c51a6"
  },
  {
    "module": "keel-crucible",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelCommunityReplicationRegistry",
    "address": "0xee36d4123fda319ecf64363317658cfa8c3d96bf",
    "block": "11478535",
    "txHash": "0xe2101466daa17f050f91a144b16a67283a6b38681360431c8eb9fa71b331f262"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KEEL721",
    "address": "0x71B25649E8A27992494eDAD355497c0Bea50A8e0",
    "block": "11476935",
    "txHash": "0x77739909a00b20931c21517d1594dbe386ad94ce0fdced4f6321aec16db03bde"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelFactory",
    "address": "0x4254a9911d3ad371bb129b5ef9a2a75f85ba3219",
    "block": "11476933",
    "txHash": "0x629e1fbfa482e2e82c82f66dc61ebcbb7bc9c1cd563cec25f3057f54c36656a1"
  },
  {
    "module": "keel-equipment",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelEquipmentInventory",
    "address": "0xf4b2044c15deed5f7bf1cf3468ae8c78fcfefccf",
    "block": "11476947",
    "txHash": "0x8c82308482b93b060fb499cf284d4b57355dd59df903f47827935062a01d6f59"
  },
  {
    "module": "keel-equipment",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "KeelEquipmentInventory",
    "address": "0xe5f341AB0C6246E230412B464c298fa7980AAdC3",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelGraphRegistry",
    "address": "0x5b86439598d2091bf45971c3676eb25c5d64dca4",
    "block": "11476949",
    "txHash": "0x894cb84bf69f040db859ad9dd018c7fb62059282015e384422f6c73114ef2a72"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelPluginRegistry",
    "address": "0xb7a4f9d0ef9d81ab4190d847e804e27c1ea820fd",
    "block": "11476951",
    "txHash": "0x555896b004c2cf657d46ba545436dfaa7e3ea30b5ffaa06b8dd15b034ea6730f"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "trusted-runtime",
    "contract": "KeelGraphRegistry",
    "address": "0x5b86439598d2091bf45971c3676eb25c5d64dca4",
    "block": null,
    "txHash": null
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "trusted-runtime",
    "contract": "KeelModuleReviewRegistry",
    "address": "0x9abb1f929a05e0ddf558aa9f594ec7775e28f8b2",
    "block": null,
    "txHash": null
  },
  {
    "module": "keel-hold",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelHold",
    "address": "0x0a4f31d5ab08029e4c68f6f3227d9fa3a2d66267",
    "block": "11559677",
    "txHash": "0xae9e37ce8705258f4395498747e03682207d3a4e04e23e734086fedd01d404ef"
  },
  {
    "module": "keel-hold",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelIndex",
    "address": "0x2b706ded15fb27a582da256321f2b3295413b8ac",
    "block": "11559678",
    "txHash": "0x93bdfd7694deb532a01aee4092020b8aad25a1720317d609949ab68166e944fc"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPActionExecutor",
    "address": "0x82548953d1a8baba9f4902844877FFA747ff243D",
    "block": "11491417",
    "txHash": "0xf5fcae22f51b8f381ef67c80b4f6f399e3c176936e45ba36813f49aaad8e3347"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPControl",
    "address": "0x9f62Aec9E1bd5117864C6A19a7FC8C4e51F39aD0",
    "block": "11491416",
    "txHash": "0x924da433760a9ecbfbf1d146a328c065bdf04960d8133c13401763f82293113d"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPWrapped721",
    "address": "0xD6290b9777B1Be895719e32900552107aADD674c",
    "block": "11491418",
    "txHash": "0x8d2653dcc830a8a400ac5c6cd10d543d3d289fc3e1a1c34701c76e79f009888d"
  },
  {
    "module": "keel-market",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelMarket",
    "address": "0xd87f72b751d2008c7365680653b79ff7eb0780b6",
    "block": "11476953",
    "txHash": "0x2500616c8bbf2c5f5642b70309513e8cb4ec90e8945045c1e1491e0edf33852a"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelMintGate",
    "address": "0xec125031e5972f0f874b313e8e3c69d42503c9cf",
    "block": "11476928",
    "txHash": "0xa92c538456ad309617e5354e9110b0b404858ed343ee9baaa8d2e19dce46e0ed"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "OneMintController",
    "address": "0xf0e7ca391105fb34ef00db72027752998de1067a",
    "block": "11476930",
    "txHash": "0x3b4b4c71d975b5bc17563353add330dd36b23c7c9e396b0cd03c529ec5afd72e"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultArcadeRegistry",
    "address": "0xC5356FfEBE287145AF9d52300cCd39d0A5787e01",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultCharacter721",
    "address": "0xf9EaE6838C718BbeF224c4846b01e35306B60520",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultCharacterPackV2",
    "address": "0xdBC33a7633130f11E2A5E020d7029E68402AC489",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  }
] as const;
