// GENERATED BY `keel sync` — DO NOT EDIT BY HAND.
// Source: packages/contracts/modules/*/keel.module.json and */deployments/*.json

/** Reusable protocol infrastructure. Each module ships as its own repository. */
export type KeelModuleId = "keel-kernel" | "keel-codecs" | "keel-hold" | "keel-artifacts" | "keel-graph" | "keel-harness" | "keel-presentation" | "keel-die" | "keel-creator-identity" | "keel-mint-access" | "keel-market" | "keel-anchors" | "keel-crucible" | "keel-ip-control" | "keel-sleeve" | "keel-web3-url" | "keel-cross-chain-mint" | "keel-publication" | "keel-stake";

/**
 * Concrete products built on the modules. Apps consume modules exactly as an
 * outside integrator does, and no module may depend on one.
 */
export type KeelAppId = "keel-canvas" | "cool-s" | "line" | "vault-runner";

/** Anything with contracts on a chain — a module or an app. */
export type KeelUnitId = KeelModuleId | KeelAppId;

/** Role labels units are grouped and browsed by. */
export type KeelModuleGroup = "apps" | "assets" | "core" | "market" | "provenance" | "render" | "token";

export interface KeelModule {
  readonly id: KeelUnitId;
  /** "module" is reusable infrastructure; "app" is a product built on it. */
  readonly kind: "module" | "app";
  readonly title: string;
  /** Role label; the topic this module's repository is tagged with. */
  readonly group: KeelModuleGroup;
  readonly summary: string;
  readonly version: string;
  /** Repository this module is published from once split out of the monorepo. */
  readonly repo: string | null;
  /** Repository visibility, when known. Affects installation, not resolution. */
  readonly visibility: "public" | "private" | null;
  readonly deps: readonly KeelUnitId[];
  readonly contracts: readonly string[];
  /** Contracts with creation bytecode — the ones a release actually deploys. */
  readonly deployable: readonly string[];
}

export interface KeelDeployment {
  readonly module: KeelUnitId;
  readonly chainId: number;
  /** Named instance: one chain can carry several deployments of a module. */
  readonly instance: string;
  readonly contract: string;
  readonly address: `0x${string}`;
  readonly block: string | null;
  readonly txHash: string | null;
  /** Exact deployed runtime commitment when authenticated separately from the ABI. */
  readonly runtimeCodeHash?: `0x${string}`;
}

export const KEEL_MODULES: readonly KeelModule[] = [
  {
    "id": "keel-kernel",
    "kind": "module",
    "title": "Kernel",
    "group": "core",
    "visibility": "private",
    "summary": "Admin/access primitives and encoding helpers every other module is allowed to import.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-kernel",
    "deps": [],
    "contracts": [
      "SafeAdminAccessControl.sol",
      "libraries/JsonEscape.sol",
      "libraries/KeelCodeIdentity.sol",
      "libraries/KeelUriEscape.sol",
      "KeelFeeTreasury.sol",
      "libraries/KeelPlatformFees.sol",
      "libraries/KeelGovernance.sol",
      "KeelAccessGroups.sol",
      "KeelLocalPause.sol",
      "libraries/KeelPause.sol",
      "libraries/KeelTokenURIEnvelope.sol",
      "libraries/KeelMintSeeded.sol",
      "libraries/KeelMintSeededBatches.sol",
      "interfaces/IKeelMintSeededBatchErrors.sol",
      "interfaces/IKeelMintSeededErrors.sol",
      "interfaces/IKeelMintSeededData.sol",
      "interfaces/IKeelVrfV2Plus.sol",
      "interfaces/IKeelGovernanceErrors.sol",
      "interfaces/IKeelPlatformFeeErrors.sol",
      "interfaces/IKeelFeeTreasuryErrors.sol",
      "interfaces/IKeelFeeTreasuryEvents.sol",
      "interfaces/IKeelAccessGroupErrors.sol",
      "interfaces/IKeelAccessGroupEvents.sol",
      "KeelRecoveryGroups.sol",
      "interfaces/IKeelRecoveryErrors.sol",
      "interfaces/IKeelMetadataRelay.sol",
      "libraries/KeelMetadataSubscriptions.sol",
      "libraries/KeelRawStringReturn.sol",
      "KeelAuthority.sol",
      "interfaces/IKeelAuthorityErrors.sol"
    ],
    "deployable": [
      "KeelFeeTreasury",
      "KeelAccessGroups",
      "KeelRecoveryGroups",
      "KeelAuthority"
    ]
  },
  {
    "id": "keel-codecs",
    "kind": "module",
    "title": "Codecs",
    "group": "core",
    "visibility": "private",
    "summary": "Pure, stateless decoders: RLP, Merkle-Patricia, block headers, IPFS CIDs, base32/58, BLS12-381.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-codecs",
    "deps": [],
    "contracts": [
      "libraries/KeelRlp.sol",
      "libraries/KeelBlockHeader.sol",
      "libraries/KeelMerklePatricia.sol",
      "libraries/KeelEthAccount.sol",
      "libraries/KeelOpOutputRoot.sol",
      "libraries/KeelIpfsCid.sol",
      "libraries/KeelDagPb.sol",
      "libraries/KeelBase32.sol",
      "libraries/KeelBase58.sol",
      "libraries/Bls12381.sol"
    ],
    "deployable": []
  },
  {
    "id": "keel-hold",
    "kind": "module",
    "title": "Storage",
    "group": "core",
    "visibility": "private",
    "summary": "Immutable content-addressed chunk storage and the artifact registry that activates revisions.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-hold",
    "deps": [
      "keel-kernel"
    ],
    "contracts": [
      "KeelHold.sol",
      "Ingot.sol",
      "KeelIndex.sol",
      "interfaces/IKeelHold.sol",
      "interfaces/IKeelHoldLimits.sol",
      "interfaces/IKeelHoldSeal.sol",
      "libraries/KeelSealValidation.sol",
      "libraries/KeelCastDispatch.sol",
      "interfaces/IKeelIndex.sol",
      "interfaces/IKeelHoldHarness.sol",
      "interfaces/IKeelHoldEvents.sol",
      "libraries/KeelHoldMetadata.sol",
      "interfaces/IKeelHoldErrors.sol",
      "interfaces/IKeelIndexErrors.sol",
      "interfaces/IKeelIndexEvents.sol",
      "interfaces/IKeelIndexMetadataReceiver.sol"
    ],
    "deployable": [
      "Ingot",
      "KeelHold",
      "KeelIndex"
    ]
  },
  {
    "id": "keel-artifacts",
    "kind": "module",
    "title": "Object model",
    "group": "core",
    "visibility": "private",
    "summary": "The Keel object graph: objects, viewers, links, seeds, and the manager that fronts them.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-artifacts",
    "deps": [
      "keel-hold",
      "keel-kernel"
    ],
    "contracts": [
      "KeelArtifactRegistry.sol",
      "KeelManager.sol",
      "KeelTestOwnerManager.sol",
      "KeelManagerProxy.sol",
      "KeelHarnessRegistry.sol",
      "KeelLinkRegistry.sol",
      "KeelSeedRegistry.sol",
      "interfaces/IKeelMintSeedSource.sol",
      "interfaces/IKeelSeedRegistryErrors.sol",
      "interfaces/IKeelSeedRegistryEvents.sol",
      "interfaces/IKeelArtifactRegistry.sol",
      "interfaces/IKeelManager.sol",
      "interfaces/IKeelArtifactRevisionPolicy.sol",
      "interfaces/IKeelHarnessRegistry.sol",
      "interfaces/IKeelHarnessRegistryErrors.sol",
      "interfaces/IKeelHarnessRegistryEvents.sol",
      "KeelManagerRecovery.sol",
      "KeelManagerRpcPolicy.sol",
      "interfaces/IKeelManagerErrors.sol",
      "interfaces/IKeelManagerEvents.sol",
      "interfaces/IKeelManagerRecoveryErrors.sol",
      "interfaces/IKeelManagerRecoveryEvents.sol",
      "interfaces/IKeelManagerRpcErrors.sol",
      "interfaces/IKeelManagerRpcEvents.sol",
      "interfaces/IKeelManagerTypes.sol",
      "libraries/KeelManagerGovernorState.sol",
      "KeelLinkURIBuilder.sol",
      "interfaces/IKeelLinkURIBuilder.sol",
      "interfaces/IKeelLinkURIBuilderErrors.sol",
      "interfaces/IKeelLinkRegistryErrors.sol",
      "interfaces/IKeelLinkRegistryEvents.sol",
      "KeelRawFragmentValidationRegistry.sol",
      "KeelRawFragmentRevisionPolicy.sol",
      "KeelRawImageRevisionPolicy.sol",
      "KeelArtifactFragmentResolver.sol",
      "KeelRegisteredArtifactFragmentResolver.sol",
      "interfaces/IKeelArtifactFragmentResolver.sol",
      "interfaces/IKeelRawCanonicalShellRegistry.sol",
      "interfaces/IKeelRawFragmentRevisionPolicy.sol",
      "interfaces/IKeelRawFragmentValidationRegistry.sol",
      "interfaces/IKeelRawFragmentValidationRegistryEvents.sol",
      "interfaces/IKeelRawImageRevisionPolicy.sol",
      "interfaces/IKeelRevisionedRawTokenURIBuilder.sol"
    ],
    "deployable": [
      "KeelArtifactRegistry",
      "KeelHarnessRegistry",
      "KeelLinkRegistry",
      "KeelManager",
      "KeelTestOwnerManager",
      "KeelManagerProxy",
      "KeelSeedRegistry",
      "KeelManagerRecovery",
      "KeelManagerRpcPolicy",
      "KeelLinkURIBuilder",
      "KeelRawFragmentValidationRegistry",
      "KeelRawFragmentRevisionPolicy",
      "KeelRawImageRevisionPolicy",
      "KeelArtifactFragmentResolver",
      "KeelRegisteredArtifactFragmentResolver"
    ]
  },
  {
    "id": "keel-graph",
    "kind": "module",
    "title": "Graph trust lattice",
    "group": "core",
    "visibility": "private",
    "summary": "Graph/plugin/library/module registries — the on-chain trust lattice the runtime re-derives against.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-graph",
    "deps": [],
    "contracts": [
      "KeelGraphRegistry.sol",
      "KeelPluginRegistry.sol",
      "KeelModuleReviewRegistry.sol",
      "KeelLibraryRegistry.sol",
      "KeelAssetTagRegistry.sol",
      "interfaces/IKeelGraphRegistry.sol",
      "interfaces/IKeelContractPlugin.sol"
    ],
    "deployable": [
      "KeelAssetTagRegistry",
      "KeelGraphRegistry",
      "KeelLibraryRegistry",
      "KeelModuleReviewRegistry",
      "KeelPluginRegistry"
    ]
  },
  {
    "id": "keel-harness",
    "kind": "module",
    "title": "On-chain HTML builder",
    "group": "render",
    "visibility": "private",
    "summary": "Assembles viewer HTML from chunk-stored resources entirely on chain.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-harness",
    "deps": [
      "keel-hold",
      "keel-kernel",
      "keel-artifacts"
    ],
    "contracts": [
      "KeelHarnessBuilder.sol",
      "KeelPercentTokenURIBuilder.sol",
      "interfaces/IKeelHarnessBuilder.sol",
      "interfaces/IKeelPercentTokenURIBuilder.sol",
      "libraries/KeelHarnessContextDispatch.sol",
      "libraries/KeelPreEncodedTokenURI.sol",
      "libraries/KeelPreparedTokenURI.sol",
      "KeelObjectURIBuilder.sol",
      "KeelRawTokenURIBuilder.sol",
      "interfaces/IKeelObjectURIBuilder.sol",
      "interfaces/IKeelRawTokenURIBuilder.sol",
      "KeelSVGRenderer.sol",
      "interfaces/IKeelSVGRenderer.sol",
      "KeelRawInlineShellRegistry.sol",
      "interfaces/IKeelRawInlineShellRegistry.sol"
    ],
    "deployable": [
      "KeelHarnessBuilder",
      "KeelPercentTokenURIBuilder",
      "KeelObjectURIBuilder",
      "KeelRawTokenURIBuilder",
      "KeelRawInlineShellRegistry"
    ]
  },
  {
    "id": "keel-presentation",
    "kind": "module",
    "title": "Presentation state",
    "group": "core",
    "visibility": "private",
    "summary": "Presentation/visual state ledgers that record what a token currently renders as.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-presentation",
    "deps": [],
    "contracts": [
      "KeelPresentationStateRegistry.sol",
      "KeelVisualStateLedger.sol",
      "interfaces/IKeelPresentationRegistry.sol",
      "interfaces/IKeelImmutableObjectSource.sol",
      "interfaces/IKeelPresentationStateErrors.sol",
      "interfaces/IKeelPresentationStateEvents.sol",
      "interfaces/IKeelStakingAdapter.sol",
      "interfaces/IKeelVisualStateLedgerErrors.sol",
      "interfaces/IKeelVisualStateLedgerEvents.sol"
    ],
    "deployable": [
      "KeelPresentationStateRegistry",
      "KeelVisualStateLedger"
    ]
  },
  {
    "id": "keel-die",
    "kind": "module",
    "title": "Token base",
    "group": "token",
    "visibility": "private",
    "summary": "Compact creator-owned ERC-721/ERC-1155 collections, a shared multi-creator ERC-1155, renderer boundaries, and factories that organize them.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-die",
    "deps": [
      "keel-kernel",
      "keel-harness",
      "keel-presentation",
      "keel-artifacts",
      "keel-hold",
      "keel-codecs"
    ],
    "contracts": [
      "KEEL721.sol",
      "KeelMintSeeded721.sol",
      "KeelMintSeeded721A.sol",
      "KEEL721Deployer.sol",
      "KeelFactory.sol",
      "KeelFactorySepolia.sol",
      "KeelCreator721.sol",
      "KeelCreator721A.sol",
      "KeelCreatorSeeded721A.sol",
      "KeelSeedBlockArchive.sol",
      "KeelSeedVrfAdapter.sol",
      "interfaces/IKeelSeedVrf.sol",
      "interfaces/IKeelSeedVrfErrors.sol",
      "interfaces/IKeelSeedVrfEvents.sol",
      "interfaces/IKeelCreatorSeedErrors.sol",
      "interfaces/IKeelCreatorSeedEvents.sol",
      "KeelCreator1155.sol",
      "interfaces/IKeelCreatorLifecycleEvents.sol",
      "interfaces/IKeelCreatorItemErrors.sol",
      "interfaces/IKeelItemCapacityEvents.sol",
      "interfaces/IKeelCreator1155Events.sol",
      "KeelShared1155.sol",
      "interfaces/IKeelItemBatchMintTarget.sol",
      "interfaces/IKeelMintBatchErrors.sol",
      "interfaces/IKeelShared1155Errors.sol",
      "interfaces/IKeelShared1155Events.sol",
      "KeelCreatorFactory.sol",
      "interfaces/IKeelCreatorFactoryErrors.sol",
      "interfaces/IKeelCreatorFactoryEvents.sol",
      "KeelArtifactTokenRenderer.sol",
      "interfaces/IKeelMintable.sol",
      "interfaces/IKeelMintDataSource.sol",
      "interfaces/IKeelMintCapacity.sol",
      "interfaces/IKeelCampaignAuthorizer.sol",
      "interfaces/IKeelItemMintTarget.sol",
      "interfaces/IKeelTokenRenderer.sol",
      "interfaces/IKeelCreatorDirectory.sol",
      "KeelRawPrepared721.sol",
      "KeelRouted721.sol",
      "Keel721Presentation.sol",
      "interfaces/IKeel721Errors.sol",
      "interfaces/IKeel721Events.sol",
      "interfaces/IKeelCreatorCollectionErrors.sol",
      "interfaces/IKeelCreatorCollectionEvents.sol",
      "interfaces/IKeelMintTargetErrors.sol",
      "interfaces/IKeelStrikeCapacityEvents.sol",
      "interfaces/IKeel721PresentationEvents.sol",
      "interfaces/IKeelDeferredCollectionResolver.sol",
      "interfaces/IKeelDeferredMintSetup.sol",
      "interfaces/IKeelMetadataEvents.sol",
      "interfaces/IKeelMetadataReceiver.sol",
      "libraries/Keel721MetadataFormatting.sol",
      "libraries/KeelSeedBlockEntropy.sol",
      "KeelRevisioned721.sol",
      "KeelRegisteredArtifactFragment721Presentation.sol",
      "interfaces/IKeelDirect721Presentation.sol",
      "interfaces/IKeelCollectionDescription.sol",
      "interfaces/IKeelTokenNameSource.sol"
    ],
    "deployable": [
      "KEEL721",
      "KEEL721Deployer",
      "KeelArtifactTokenRenderer",
      "KeelCreator1155",
      "KeelCreator721",
      "KeelCreator721A",
      "KeelCreatorFactory",
      "KeelFactory",
      "KeelFactorySepolia",
      "KeelShared1155",
      "KeelRawPrepared721",
      "Keel721Presentation",
      "KeelRouted721",
      "KeelCreatorSeeded721A",
      "KeelSeedBlockArchive",
      "KeelSeedVrfAdapter",
      "KeelRevisioned721",
      "KeelRegisteredArtifactFragment721Presentation",
      "Keel721MetadataFormatting"
    ]
  },
  {
    "id": "keel-creator-identity",
    "kind": "module",
    "title": "Creator identity",
    "group": "token",
    "visibility": "private",
    "summary": "Creator profiles, commitments, and attribution records.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-creator-identity",
    "deps": [
      "keel-artifacts",
      "keel-kernel"
    ],
    "contracts": [
      "KeelCreatorProfileRegistry.sol",
      "KeelCreatorCommitmentRegistry.sol",
      "KeelAttributionRegistry.sol",
      "interfaces/IKeelCreatorProfileRegistry.sol"
    ],
    "deployable": [
      "KeelAttributionRegistry",
      "KeelCreatorCommitmentRegistry",
      "KeelCreatorProfileRegistry"
    ]
  },
  {
    "id": "keel-mint-access",
    "kind": "module",
    "title": "Mint access",
    "group": "token",
    "visibility": "private",
    "summary": "Shared mint routes, OneMint admission queues, verifiable queue/reward entropy, and community or achievement reward claims.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-mint-access",
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-creator-identity",
      "keel-hold"
    ],
    "contracts": [
      "KeelMintQueue.sol",
      "QueuePriorityHeap.sol",
      "KeelQueueAccess.sol",
      "KeelRewardClaims.sol",
      "KeelMintRewardEntropy.sol",
      "FrayAuctionIssuer.sol",
      "KeelMintGate.sol",
      "KeelMintRouteRegistry.sol",
      "interfaces/IKeelMintBatchRouteRegistry.sol",
      "interfaces/IKeelMintRouteErrors.sol",
      "interfaces/IKeelMintRouteEvents.sol",
      "OneMintCore.sol",
      "KeelOneMintBatch.sol",
      "interfaces/IKeelOneMintBatch.sol",
      "OneMintController.sol",
      "OpenOneMintController.sol",
      "interfaces/IKeelAccessGate.sol",
      "interfaces/IKeelMintAdapter.sol",
      "interfaces/IKeelMintHook.sol",
      "interfaces/IKeelMintRouteRegistry.sol",
      "interfaces/IKeelOneMintErrors.sol",
      "interfaces/IKeelMintGateErrors.sol",
      "interfaces/IKeelMintGateEvents.sol",
      "libraries/KeelMintPricing.sol",
      "libraries/KeelNftCouponClaims.sol",
      "interfaces/IKeelMintPricingErrors.sol",
      "interfaces/IKeelMintCoupons.sol",
      "interfaces/IKeelOneMintEvents.sol",
      "KeelMintReleases.sol",
      "KeelMintReleaseInspector.sol",
      "libraries/KeelReleasePolicy.sol",
      "interfaces/IKeelReleaseErrors.sol",
      "interfaces/IKeelReleaseEvents.sol",
      "KeelQueueDemand.sol",
      "KeelQueuePriority.sol",
      "KeelQueueReadAdapter.sol",
      "interfaces/IKeelQueueLifecycle.sol",
      "KeelQueueLotteryEngine.sol",
      "KeelQueueLotteryPool.sol",
      "interfaces/IKeelLotteryQueueState.sol",
      "interfaces/IKeelQueueEntropyRecovery.sol",
      "interfaces/IKeelAchievementEligibility.sol",
      "interfaces/IKeelAuctionIssuer.sol",
      "interfaces/IKeelAuctionIssuerErrors.sol",
      "interfaces/IKeelAuctionIssuerEvents.sol",
      "interfaces/IKeelAuctionPublication.sol",
      "interfaces/IKeelAuctionReleaseRouter.sol",
      "interfaces/IKeelDeferredAuctionIssuer.sol",
      "interfaces/IKeelMintQueueErrors.sol",
      "interfaces/IKeelMintQueueEvents.sol",
      "interfaces/IKeelMintRewardEntropyErrors.sol",
      "interfaces/IKeelMintRewardEntropyEvents.sol",
      "interfaces/IKeelQueueAccessErrors.sol",
      "interfaces/IKeelQueueAccessEvents.sol",
      "interfaces/IKeelQueueDemandErrors.sol",
      "interfaces/IKeelQueueDemandEvents.sol",
      "interfaces/IKeelQueueLotteryEngineErrors.sol",
      "interfaces/IKeelQueueLotteryPoolErrors.sol",
      "interfaces/IKeelQueuePeriod.sol",
      "interfaces/IKeelQueuePriorityErrors.sol",
      "interfaces/IKeelQueueReadAdapterErrors.sol",
      "interfaces/IKeelRewardClaimsErrors.sol",
      "interfaces/IKeelRewardClaimsEvents.sol",
      "interfaces/IKeelRewardReceiver.sol",
      "interfaces/IKeelUniqueTarget.sol"
    ],
    "deployable": [
      "FrayAuctionIssuer",
      "KeelMintGate",
      "KeelMintRouteRegistry",
      "KeelOneMintBatch",
      "OneMintController",
      "OpenOneMintController",
      "KeelMintQueue",
      "KeelRewardClaims",
      "KeelMintRewardEntropy",
      "KeelQueueAccess",
      "KeelQueueDemand",
      "KeelQueuePriority",
      "KeelQueueReadAdapter",
      "KeelQueueLotteryEngine",
      "KeelQueueLotteryPool"
    ]
  },
  {
    "id": "keel-market",
    "kind": "module",
    "title": "Market",
    "group": "market",
    "visibility": "private",
    "summary": "The Keel marketplace plugin contract.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-market",
    "deps": [
      "keel-graph",
      "keel-kernel"
    ],
    "contracts": [
      "KeelMarket.sol"
    ],
    "deployable": [
      "KeelMarket"
    ]
  },
  {
    "id": "keel-anchors",
    "kind": "module",
    "title": "Anchors",
    "group": "provenance",
    "visibility": "private",
    "summary": "Cross-chain and off-chain anchoring: portable commitments, permissionless L2 state proofs, and zk verification backends.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-anchors",
    "deps": [
      "keel-kernel",
      "keel-codecs",
      "keel-artifacts",
      "keel-graph",
      "keel-hold"
    ],
    "contracts": [
      "KeelProofUpgradeController.sol",
      "KeelAttestedAnchorRegistry.sol",
      "KeelPortableAnchorRegistry.sol",
      "KeelAnchorReplicationBridge.sol",
      "KeelL2AnchorVerifier.sol",
      "KeelL2StateVerifier.sol",
      "KeelSettlementRegistry.sol",
      "KeelZkAnchorVerifier.sol",
      "KeelZkVerifyProofBackend.sol",
      "KeelZkVerifyProofVerifier.sol",
      "KeelSp1GatewayProofBackend.sol",
      "KeelSp1GatewayProofVerifier.sol",
      "KeelIpfsCidVerifier.sol",
      "KeelNodeRegistry.sol",
      "interfaces/IKeelAnchorProofBackend.sol",
      "interfaces/IKeelAnchorProofVerifier.sol",
      "interfaces/IKeelAnchoredChainQueries.sol",
      "interfaces/IKeelSettlementSource.sol",
      "vendor/sp1/ISP1Verifier.sol",
      "vendor/sp1/v5.0.0/Groth16Verifier.sol",
      "vendor/sp1/v5.0.0/SP1VerifierGroth16.sol"
    ],
    "deployable": [
      "KeelProofUpgradeController",
      "KeelAnchorReplicationBridge",
      "KeelAttestedAnchorRegistry",
      "KeelIpfsCidVerifier",
      "KeelL2AnchorVerifier",
      "KeelL2StateVerifier",
      "KeelNodeRegistry",
      "KeelPortableAnchorRegistry",
      "KeelSettlementRegistry",
      "KeelSp1GatewayProofBackend",
      "KeelSp1GatewayProofVerifier",
      "KeelZkAnchorVerifier",
      "KeelZkVerifyProofBackend",
      "KeelZkVerifyProofVerifier"
    ]
  },
  {
    "id": "keel-crucible",
    "kind": "module",
    "title": "Collection verification",
    "group": "provenance",
    "visibility": "private",
    "summary": "Collection attestation, community replication, and preservation bounties.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-crucible",
    "deps": [
      "keel-kernel",
      "keel-hold",
      "keel-artifacts"
    ],
    "contracts": [
      "KeelCollectionVerificationRegistry.sol",
      "KeelCollectionVerificationHookBase.sol",
      "KeelCollectionAttestationRegistry.sol",
      "KeelCommunityReplicationRegistry.sol",
      "interfaces/IKeelCollectionVerificationHook.sol",
      "interfaces/IKeelCollectionVerificationAdapter.sol",
      "interfaces/ICommunityHold.sol"
    ],
    "deployable": [
      "KeelCollectionAttestationRegistry",
      "KeelCollectionVerificationRegistry",
      "KeelCommunityReplicationRegistry"
    ]
  },
  {
    "id": "keel-ip-control",
    "kind": "module",
    "title": "IP control",
    "group": "provenance",
    "visibility": "private",
    "summary": "On-chain IP rights control, wrapped-721 custody, and the executor that acts on granted rights.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-ip-control",
    "deps": [
      "keel-hold",
      "keel-artifacts",
      "keel-kernel"
    ],
    "contracts": [
      "KeelIPControl.sol",
      "KeelIPActionExecutor.sol",
      "KeelIPWrapped721.sol",
      "interfaces/IKeelIPControl.sol",
      "interfaces/IKeelIPMintTarget.sol"
    ],
    "deployable": [
      "KeelIPActionExecutor",
      "KeelIPControl",
      "KeelIPWrapped721"
    ]
  },
  {
    "id": "keel-sleeve",
    "kind": "module",
    "title": "Metadata resolver",
    "group": "core",
    "visibility": "private",
    "summary": "Token JSON resolution for collections that delegate metadata assembly.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-sleeve",
    "deps": [
      "keel-hold",
      "keel-kernel"
    ],
    "contracts": [
      "KeelSleeve.sol",
      "interfaces/IKeelTokenJSONResolver.sol",
      "KeelStoredTokenJSON.sol",
      "KeelTokenMatrix.sol",
      "interfaces/IKeelMatrixHold.sol",
      "interfaces/IKeelTokenMatrixErrors.sol",
      "interfaces/IKeelTokenMatrixEvents.sol",
      "KeelMetadataRelay.sol",
      "interfaces/IKeelMetadataRelayErrors.sol",
      "interfaces/IKeelMetadataRelayEvents.sol",
      "interfaces/IKeelSleeveErrors.sol",
      "interfaces/IKeelStoredTokenJSONErrors.sol",
      "interfaces/IKeelStoredTokenJSONEvents.sol"
    ],
    "deployable": [
      "KeelSleeve",
      "KeelStoredTokenJSON",
      "KeelTokenMatrix",
      "KeelMetadataRelay"
    ]
  },
  {
    "id": "keel-web3-url",
    "kind": "module",
    "title": "web3:// adapter",
    "group": "render",
    "visibility": "private",
    "summary": "ERC-5219/7617 resource adapter exposing Keel content over web3:// URLs, plus its demos.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-web3-url",
    "deps": [
      "keel-hold"
    ],
    "contracts": [
      "KeelWeb3ResourceAdapter.sol",
      "interfaces/IDecentralizedApp.sol",
      "interfaces/IERC7572.sol"
    ],
    "deployable": [
      "KeelWeb3ResourceAdapter"
    ]
  },
  {
    "id": "keel-cross-chain-mint",
    "kind": "module",
    "title": "Optional cross-chain mint bridge",
    "group": "token",
    "visibility": "private",
    "summary": "Optional attested cross-chain mint requests; not required for storage, publication, or local minting.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-cross-chain-mint",
    "deps": [
      "keel-kernel",
      "keel-mint-access"
    ],
    "contracts": [
      "KeelCrossChainMintBridge.sol"
    ],
    "deployable": [
      "KeelCrossChainMintBridge"
    ]
  },
  {
    "id": "keel-publication",
    "kind": "module",
    "title": "Publication",
    "group": "core",
    "visibility": "private",
    "summary": "Optional upload batching and resumable publication jobs, including the explicitly selected history-inscription mode.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-publication",
    "deps": [
      "keel-hold"
    ],
    "contracts": [
      "KeelCarrierBatcher.sol",
      "KeelHistoryPublicationJob.sol",
      "KeelPublicationJob.sol"
    ],
    "deployable": [
      "KeelCarrierBatcher",
      "KeelHistoryPublicationJob",
      "KeelPublicationJob"
    ]
  },
  {
    "id": "keel-stake",
    "kind": "module",
    "title": "Stake objects",
    "group": "assets",
    "visibility": "private",
    "summary": "Configurable ERC-721 staking custody, frozen terms, and optional token-bound accounts.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-stake",
    "deps": [
      "keel-artifacts",
      "keel-kernel"
    ],
    "contracts": [
      "KeelStakeObjectManager.sol",
      "interfaces/IKeelStakeObjectErrors.sol",
      "interfaces/IKeelStakeObjectEvents.sol",
      "interfaces/IKeelTokenBoundAccountRegistry.sol"
    ],
    "deployable": [
      "KeelStakeObjectManager"
    ]
  }
] as const;

/** Products built on the modules; excluded from the module registry by design. */
export const KEEL_APPS: readonly KeelModule[] = [
  {
    "id": "keel-canvas",
    "kind": "app",
    "title": "Canvas",
    "group": "apps",
    "visibility": null,
    "summary": "Shared canvas renderer/splitter/composer surface that both CoolS and LINE collections render through.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-artifacts"
    ],
    "contracts": [
      "CoolSCanvas721.sol",
      "CoolSCanvasRenderer.sol",
      "CoolSCanvasSplitter.sol",
      "CoolSCanvasMintController.sol",
      "CoolSComposer.sol",
      "interfaces/ICoolSCanvasRenderer.sol",
      "interfaces/ICoolSCanvasSplitter.sol",
      "interfaces/ICoolSCanvasView.sol",
      "interfaces/ILINE721.sol",
      "interfaces/ILINEThumbnailSource.sol",
      "libraries/CoolSCanvasStorage.sol"
    ],
    "deployable": [
      "CoolSCanvas721",
      "CoolSCanvasMintController",
      "CoolSCanvasRenderer",
      "CoolSCanvasSplitter",
      "CoolSComposer"
    ]
  },
  {
    "id": "cool-s",
    "kind": "app",
    "title": "CoolS",
    "group": "apps",
    "visibility": null,
    "summary": "The CoolS collection: generative mint hook, metadata renderer, release resolver, novelty ledger, visual registry.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-presentation"
    ],
    "contracts": [
      "CoolS721.sol",
      "CoolSMetadataRendererV1.sol",
      "CoolSNoveltyLedgerV1.sol",
      "CoolSReleaseResolverV1.sol",
      "CoolSTargetTableV1.sol",
      "CoolSVisualRegistryV1.sol",
      "CoolSLocalVRFCoordinator.sol",
      "KeelGenerativeMintHookBase.sol",
      "interfaces/ICoolSReleaseResolverV1.sol",
      "libraries/CoolSVisualStateCodecV1.sol"
    ],
    "deployable": [
      "CoolS721",
      "CoolSLocalVRFCoordinator",
      "CoolSMetadataRendererV1",
      "CoolSNoveltyLedgerV1",
      "CoolSReleaseResolverV1",
      "CoolSTargetTableV1",
      "CoolSVisualRegistryV1"
    ]
  },
  {
    "id": "line",
    "kind": "app",
    "title": "LINE",
    "group": "apps",
    "visibility": null,
    "summary": "The LINE collection and its on-chain thumbnail renderer.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-die",
      "keel-canvas",
      "keel-artifacts"
    ],
    "contracts": [
      "LINE721.sol",
      "LINEThumbnail.sol",
      "LINEThumbnailRenderer.sol"
    ],
    "deployable": [
      "LINE721",
      "LINEThumbnail",
      "LINEThumbnailRenderer"
    ]
  },
  {
    "id": "vault-runner",
    "kind": "app",
    "title": "Vault Runner",
    "group": "apps",
    "visibility": null,
    "summary": "The Vault Runner game system: characters, packs, items, arcade/achievement registries, run settlement, map auctions.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-artifacts",
      "keel-hold",
      "keel-crucible",
      "keel-harness"
    ],
    "contracts": [
      "VaultCharacter721.sol",
      "VaultCharacterMetadataRenderer.sol",
      "VaultCharacterRegistry.sol",
      "VaultCharacterPackV2.sol",
      "VaultCharacterStarterPack.sol",
      "VaultItem1155.sol",
      "VaultGameCard.sol",
      "VaultArcadeRegistry.sol",
      "VaultAchievementRegistry.sol",
      "VaultMapAuction.sol",
      "VaultRunLeaderboard.sol",
      "VaultRunLootExtraction.sol",
      "VaultRunSignatureAuthority.sol",
      "VaultSpriteAssetRegistry.sol",
      "interfaces/IVaultRunSource.sol",
      "interfaces/IVaultHardcoreRunSource.sol",
      "interfaces/IVaultRunSignatureAuthority.sol"
    ],
    "deployable": [
      "VaultAchievementRegistry",
      "VaultArcadeRegistry",
      "VaultCharacter721",
      "VaultCharacterMetadataRenderer",
      "VaultCharacterPackV2",
      "VaultCharacterRegistry",
      "VaultCharacterStarterPack",
      "VaultGameCard",
      "VaultItem1155",
      "VaultMapAuction",
      "VaultRunLeaderboard",
      "VaultRunLootExtraction",
      "VaultRunSignatureAuthority",
      "VaultSpriteAssetRegistry"
    ]
  }
] as const;

export const KEEL_DEPLOYMENTS: readonly KeelDeployment[] = [
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelArtifactRegistry",
    "address": "0x44AeAEBe72a28C9fd59a1633Ed69d1eB5c421270",
    "block": "11831485",
    "txHash": "0x6dc207be9132761ff4010ce04925053ac2c2dabb9f1cfae06215376f241dd077",
    "runtimeCodeHash": "0x998f0f57c7450d4b3395b851b2b4aad783dc5095dd16dfcdba84b9506624de7d"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelRawFragmentValidationRegistry",
    "address": "0xbBD281E72167D33261EBe9aa78F34907EFC2861D",
    "block": "11831486",
    "txHash": "0x7d104cfc22df5f3a41024f3364f4d0b66b9bf02a72696480e6537ad9a6e1f4a9",
    "runtimeCodeHash": "0x9447e8d5d3e74d95d9a336b17617ab5a0d44ae09adf25a0ab7c05de27726de57"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelArtifactFragmentResolver",
    "address": "0x0C3b49efE400Cb1b098D978B1512ca609F4DA6b6",
    "block": "11844873",
    "txHash": "0x215bf52b0192b825ffc211deb1f0f02f77391d7919463109ce9374817e1d3e2a",
    "runtimeCodeHash": "0x75eb06954b81ea50128cc36d15ff102a1000302bb1654cdb1a013191084573ae"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelArtifactRegistry",
    "address": "0x44AeAEBe72a28C9fd59a1633Ed69d1eB5c421270",
    "block": "11831485",
    "txHash": "0x6dc207be9132761ff4010ce04925053ac2c2dabb9f1cfae06215376f241dd077",
    "runtimeCodeHash": "0x998f0f57c7450d4b3395b851b2b4aad783dc5095dd16dfcdba84b9506624de7d"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelHarnessRegistry",
    "address": "0x813c962d99A0789aBc31b98C51251b81C54b9f2D",
    "block": "11831727",
    "txHash": "0xb0704ac2175f182e909ab5ecc35bdeff3b0724be2f7a92f762008ba6c2760388",
    "runtimeCodeHash": "0x881be821105e6c12518ba03df010d51db868c698cd40022add1cdba6b2991740"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelRawFragmentRevisionPolicy",
    "address": "0xE1d19BDC56757Eb7F37F1028c467E55881f7add7",
    "block": "11831488",
    "txHash": "0xd153f5a1eeaded8d7ddfc5deb848e727ab661efa89ecb62e5c3aadf403bc6dbb",
    "runtimeCodeHash": "0x1a58b0c7b98bbebb9b7c9c34dad7a841b7beb8022d02b8df1bb24916eb93575e"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelRawFragmentValidationRegistry",
    "address": "0xbBD281E72167D33261EBe9aa78F34907EFC2861D",
    "block": "11831486",
    "txHash": "0x7d104cfc22df5f3a41024f3364f4d0b66b9bf02a72696480e6537ad9a6e1f4a9",
    "runtimeCodeHash": "0x9447e8d5d3e74d95d9a336b17617ab5a0d44ae09adf25a0ab7c05de27726de57"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelRawImageRevisionPolicy",
    "address": "0xCd987AD1496A3a449306068A88B282A9516C853A",
    "block": "11831489",
    "txHash": "0x14affd3cf9f9db4a0e2fa656561e6573ee03896eaeae0497a5fe9e4e6032f50c",
    "runtimeCodeHash": "0x8a14c0bed9e98c438ec72e0b8c94a17f5b6d7c10ad92fbbb7963b3a4c4e534e9"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelRegisteredArtifactFragmentResolver",
    "address": "0x5c296077d507b8fBEC06462AAF2D580640016C04",
    "block": "11844874",
    "txHash": "0xefaafbfde6cf3e0de648e51a9f1fa04a486d0ad8bc841633960d9d85a4d20cb1",
    "runtimeCodeHash": "0x43d8a05edc8cf2317508c39b158e226e70d436b3b41a01b51770ce0612b04864"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelSeedRegistry",
    "address": "0xc71A56300Ae327c3262dF247639a7b5730a78224",
    "block": "11831728",
    "txHash": "0x313ba30c2d442368f661f36db4089119556784cfe0fe63a0666620e42365452f",
    "runtimeCodeHash": "0x5db74651e301a313c38c892cf0f34e84c4c1cde92d83b7e7b4cae96d209d3df5"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelTestOwnerManager",
    "address": "0xff0C324E076BD0E4d866cE564AD494a5e9B4398D",
    "block": "11831476",
    "txHash": "0xb9d53a40cb94fc6f34bb486a26c8f923638f4ceb2d751eb00b5e41058dd77f28",
    "runtimeCodeHash": "0x7d23ceb5a487f08b5d6771025cb8784237bbb0e73edab08a86d4116fb0b5d2ee"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelArtifactRegistry",
    "address": "0xe85884ba2af3932d4f98507668ed5fe8fed6db92",
    "block": "11629038",
    "txHash": "0x235a86349768f288282f939b4decfa211bf45acf691a74dc1490c70ea0037d41"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelHarnessRegistry",
    "address": "0xa5d6ae35c327f998403aa1eb713df3741e3f3136",
    "block": "11629039",
    "txHash": "0xf7e21d4950805b330a8e11f532695586353ae1c41121efc237daee979bded83f"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelLinkRegistry",
    "address": "0xc2b94319334359171a653c93e402b12b93e24102",
    "block": "11629040",
    "txHash": "0x2ede42b1097011f7485c99e85d0eefbd2d69fbe1234d52858bdd8f68e8c42f7e"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelManager",
    "address": "0x940004faaee674c99b20ca7ecce6f877b996c3e5",
    "block": "11629033",
    "txHash": "0x0f0d3bbd3aa1266c13c763235b4fefaf999849ac971c78a9574f7a89b0d8229e"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelManagerProxy",
    "address": "0x7cb6d62cdd968ba45a8a1f0d99a02e5e274fe6e3",
    "block": "11476924",
    "txHash": "0xd651408d7ec6f222aa5a47655ce34e7f92fd02a92c58bee1f1f69c69d25455c2"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelSeedRegistry",
    "address": "0xf6b301e56c813692aeb75b9659864c7e76cf4c8b",
    "block": "11629041",
    "txHash": "0xc44f7d534294cf1f47c46c9751fa56f007fff6ee09b06080918f20e2a302e672"
  },
  {
    "module": "keel-creator-identity",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelCreatorProfileRegistry",
    "address": "0xa4112eda52ca519adaeebee7c12c4770594529fa",
    "block": "11476926",
    "txHash": "0x09edbc01e0f41681c211e2781d54ba5f8a7931ea14224bb730b24773365c51a6"
  },
  {
    "module": "keel-crucible",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelCommunityReplicationRegistry",
    "address": "0xe8a4618e7327c75631afcdd2ff7b0f4a73d42595",
    "block": "11629043",
    "txHash": "0x10993ef95265d08e7beabc0c88584f2963ddc3a021c6c4e25a50c847277d8717"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelArtifactTokenRenderer",
    "address": "0x315368393AfAd4b1EDcbFC6E82152aCeB3b9263d",
    "block": "11852701",
    "txHash": "0xd8c04513d1c4b8a0994f2ef695be1c65a3ceba1a9b78ea0820bc0c38b5e6665a",
    "runtimeCodeHash": "0x29f552e26df31950fe44c1c5d4f2804935b947aad82fca2bf85f0862d7f7621d"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelCreator1155",
    "address": "0x14BE3D519Cb72F6613F8D0a8AaCba0e788D00a37",
    "block": "11852735",
    "txHash": "0x05e403f4af41b377c0941570a84fe1bf891badff431106f42a83327ca1d684c1",
    "runtimeCodeHash": "0x8f21138bacb1ad7267632eabb124b147a2216ed39242b21aef6c64d627952b3a"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelCreator721",
    "address": "0x2E714D7E056395Fa8B1e08EecCf591Ad800E468A",
    "block": "11852733",
    "txHash": "0x132a26dfa4e3457d78865f364eb39fb208840dbd8479f0e5e80d6de7bc2468f4",
    "runtimeCodeHash": "0xb6159e4c11a2c81ae99a829cc6c7404c674620d4fc413057f157c5b3df735f08"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelCreator721A",
    "address": "0x1d1F5133113d832b8e7f5beBC17A3850656ADa8e",
    "block": "11852732",
    "txHash": "0x5924fb73bf0ed48f3c7a6d1d886f6ea290477553098d12208655d29a9ada2711",
    "runtimeCodeHash": "0xbc0d654213c8d70f30ed073db4228c164ae99d2f7d6859737d97497d6fbedbae"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelCreatorFactory",
    "address": "0x5828eBA761ab5eA72A349284da5658AD0ECD8416",
    "block": "11852738",
    "txHash": "0x2a5f34a7084db09da2c4d83b7a9eec1955e4f12078cbb713b7e9bd1858def02a",
    "runtimeCodeHash": "0x0b4179995be5ba969fc5dbce1f092fff110fa251f36a03767d4a5c01b41a19f2"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelCreatorSeeded721A",
    "address": "0xd96CA5ed492BF3442Aa3fDFe27aff2202879CcaD",
    "block": "11852737",
    "txHash": "0xc9ec520bbf0e09d09db5bfc0a7e1d65581c43cb1571206fe94e5c856f488509d",
    "runtimeCodeHash": "0x5fb0457e4cd0c122397189eacf9b4b175cd93d61deb5fbe0df03c0caae923be0"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelSeedBlockArchive",
    "address": "0xB8ECaA39B4f8777B27996914992a69C752D17023",
    "block": "11852736",
    "txHash": "0xdb528ef0685890f430c2ccf6d7546b90e68507b9e2109a9761461bdc2f9df56e",
    "runtimeCodeHash": "0x35cba7fd1c83c46dac95f47bbf874b94cbfbbb2c869a9d5a63acee35334d6a65"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KEEL721",
    "address": "0x71B25649E8A27992494eDAD355497c0Bea50A8e0",
    "block": "11476935",
    "txHash": "0x77739909a00b20931c21517d1594dbe386ad94ce0fdced4f6321aec16db03bde"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelFactory",
    "address": "0x8839dab4505128378947aa2f75a0556554043ce6",
    "block": "11629044",
    "txHash": "0xba468375724a1f02bc2baec26da7a57592c89dd16e734ae7d2fc7ced562671cd"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelGraphRegistry",
    "address": "0x5b86439598d2091bf45971c3676eb25c5d64dca4",
    "block": "11476949",
    "txHash": "0x894cb84bf69f040db859ad9dd018c7fb62059282015e384422f6c73114ef2a72"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelPluginRegistry",
    "address": "0xb7a4f9d0ef9d81ab4190d847e804e27c1ea820fd",
    "block": "11476951",
    "txHash": "0x555896b004c2cf657d46ba545436dfaa7e3ea30b5ffaa06b8dd15b034ea6730f"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "trusted-runtime",
    "contract": "KeelGraphRegistry",
    "address": "0x5b86439598d2091bf45971c3676eb25c5d64dca4",
    "block": null,
    "txHash": null
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "trusted-runtime",
    "contract": "KeelModuleReviewRegistry",
    "address": "0x9abb1f929a05e0ddf558aa9f594ec7775e28f8b2",
    "block": null,
    "txHash": null
  },
  {
    "module": "keel-harness",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelHarnessBuilder",
    "address": "0x3c70931E0cc22EeEd3716d2a8BB86Eb34e13Ce65",
    "block": "11852677",
    "txHash": "0xe0120eb1574f1ec13885bfed637cff9a35683ffd278a361c44e15fb52e688fda",
    "runtimeCodeHash": "0x4bff03ee7dbafa5b02bebae51065d2ed57f2e4342d0244acb3b78320d36ed99c"
  },
  {
    "module": "keel-harness",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelRawInlineShellRegistry",
    "address": "0x7879cB175ef93c22A1E99bceD6868d3e7bC5A3D6",
    "block": "11852676",
    "txHash": "0xb2c792c92098ae992de0cc059d81c8da9c61c3e3883f1fbfa5fd2102eef0807b",
    "runtimeCodeHash": "0xcd950bd1582022b4b14b697676e5bea70a8c572532d3ee18d242ec4037fa8478"
  },
  {
    "module": "keel-harness",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelRawTokenURIBuilder",
    "address": "0x1AB38f8c568FD373AEf05618C0ab387b30707AaE",
    "block": "11831483",
    "txHash": "0x6d60bc832a15f560b322ce5c81e1edd4ab50c91f73aa364fa9da5aed06c4c7c7",
    "runtimeCodeHash": "0x4751a10e95fce5b2c195cf16dac31b4b3bbce11bc8b8671feb6ef11c2977ae44"
  },
  {
    "module": "keel-harness",
    "chainId": 11155111,
    "instance": "raw-copy",
    "contract": "KeelRawTokenURIBuilder",
    "address": "0x70b5984c19baec22beefb1c2e0bd75a41e1452e0",
    "block": "11663945",
    "txHash": "0x95500ae2ad8ce53b592a8b9b580285af06d75b7a12cbf1e4f1e9b3bb71d4c697",
    "runtimeCodeHash": "0xfc35825b6d03672a971906cc6ed6e53b58ec84386ee9b410cb437a69242e57db"
  },
  {
    "module": "keel-harness",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelRawInlineShellRegistry",
    "address": "0x4D2450C58442162921E8d4d5A2A2C6DA403b94c0",
    "block": "11844862",
    "txHash": "0xb39ad9a69a7dac30a0fb50b76cc61cfff0cf3de83d06d128d08a64555a456df1",
    "runtimeCodeHash": "0xcd950bd1582022b4b14b697676e5bea70a8c572532d3ee18d242ec4037fa8478"
  },
  {
    "module": "keel-harness",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelRawTokenURIBuilder",
    "address": "0x1AB38f8c568FD373AEf05618C0ab387b30707AaE",
    "block": "11831483",
    "txHash": "0x6d60bc832a15f560b322ce5c81e1edd4ab50c91f73aa364fa9da5aed06c4c7c7",
    "runtimeCodeHash": "0x4751a10e95fce5b2c195cf16dac31b4b3bbce11bc8b8671feb6ef11c2977ae44"
  },
  {
    "module": "keel-harness",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelHarnessBuilder",
    "address": "0x7ac86609d6781e896c541210fdd8d1d919c5584a",
    "block": "11631488",
    "txHash": "0x822a9256583393e43a4fbca24adbc5bf8ba8f5611ae889fcdb08ae46f4a7e2d6"
  },
  {
    "module": "keel-hold",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelHold",
    "address": "0xD820e337692A6Eb7a4878e42ce88CBCFF49B55CF",
    "block": "11831482",
    "txHash": "0x98228e828e8b5167e7ef49311a2a8d36543907c33b051f8b4699f4e664598a2c",
    "runtimeCodeHash": "0xce80e0ef810ed22ef959d62cf47c19f9f7e2c7ec0d22f4304489abc368d9720e"
  },
  {
    "module": "keel-hold",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelHold",
    "address": "0xD820e337692A6Eb7a4878e42ce88CBCFF49B55CF",
    "block": "11831482",
    "txHash": "0x98228e828e8b5167e7ef49311a2a8d36543907c33b051f8b4699f4e664598a2c",
    "runtimeCodeHash": "0xce80e0ef810ed22ef959d62cf47c19f9f7e2c7ec0d22f4304489abc368d9720e"
  },
  {
    "module": "keel-hold",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelHold",
    "address": "0x0a4f31d5ab08029e4c68f6f3227d9fa3a2d66267",
    "block": "11559677",
    "txHash": "0xae9e37ce8705258f4395498747e03682207d3a4e04e23e734086fedd01d404ef"
  },
  {
    "module": "keel-hold",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelIndex",
    "address": "0x2b706ded15fb27a582da256321f2b3295413b8ac",
    "block": "11559678",
    "txHash": "0x93bdfd7694deb532a01aee4092020b8aad25a1720317d609949ab68166e944fc"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPActionExecutor",
    "address": "0x82548953d1a8baba9f4902844877FFA747ff243D",
    "block": "11491417",
    "txHash": "0xf5fcae22f51b8f381ef67c80b4f6f399e3c176936e45ba36813f49aaad8e3347"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPControl",
    "address": "0x9f62Aec9E1bd5117864C6A19a7FC8C4e51F39aD0",
    "block": "11491416",
    "txHash": "0x924da433760a9ecbfbf1d146a328c065bdf04960d8133c13401763f82293113d"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPWrapped721",
    "address": "0xD6290b9777B1Be895719e32900552107aADD674c",
    "block": "11491418",
    "txHash": "0x8d2653dcc830a8a400ac5c6cd10d543d3d289fc3e1a1c34701c76e79f009888d"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelIPControl",
    "address": "0x1b982718504aef51423f20856b79c62378cb62eb",
    "block": "11629049",
    "txHash": "0x6372164607cc4ac7322669f4938909cc34821ffc04c357cb808e51c008d6ba50"
  },
  {
    "module": "keel-kernel",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelFeeTreasury",
    "address": "0xee1ab4dF9EFE27AB92Dd5B5ED9310C1eB7Ac3b7F",
    "block": "11831479",
    "txHash": "0xbb5e344159a46e85195a2026cd8df3708adb23984ad8b1bf2a247ab942991b8c",
    "runtimeCodeHash": "0x4a80aee7404a845c918e952f68514cbdc7304fa9e4b69a4f2a0a26d4f96ace1e"
  },
  {
    "module": "keel-market",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelMarket",
    "address": "0x4f9c6ea07aed067c3f04d798bf22a1e6c5c524a8",
    "block": "11629048",
    "txHash": "0x58e89f90f505e167890dba648ede9e1811083a7fd7461dafa3abc2e5fd93c0ac"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelMintRouteRegistry",
    "address": "0xB3CD12cEf903B889Bc6C500726411d4c04f62bC1",
    "block": "11852705",
    "txHash": "0x420dc8294b5a9243d6aae643e1a9c8eb671981949cc07a157226f2b7c13013ac",
    "runtimeCodeHash": "0xe66621ec52c726a358dc740216f24abe2dbb658d16d80d2623d234275477928d"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelMintGate",
    "address": "0x9f21416da06edddb7f21a70bcbc91cd732803262",
    "block": "11629047",
    "txHash": "0x8ed484bcf0319f0ecf56a3b727f0b8d7f6562d10ec81dc93bdd4fc924ea5b62f"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelMintRouteRegistry",
    "address": "0x4dcc1132decf43ce72bbfad6f3ae109e85196fde",
    "block": "11629045",
    "txHash": "0xa2dd281009ab971aa62c2cd5fc58f09059075fb7615ad04c8273a2c469fb792f"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "OneMintController",
    "address": "0xc5a82b8320b6ad23cda749f079e3d7ad7b45cec9",
    "block": "11629046",
    "txHash": "0xb261303956960015186934bf8ca1131ed4f1284d3f771621897cfd4c34e5f867"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "studio-audience-checkout-20261006",
    "contract": "KeelMintRouteRegistry",
    "address": "0x96Cef44bDd8647F42c66d1B82e69334a9b4aDcB3",
    "block": "11860361",
    "txHash": "0x73b06797679e78d74eacf3c25dd50b2e25965256a414ee5e4c049c09a63e1d4c",
    "runtimeCodeHash": "0xaf8ae20faf322f9c1f4e05aa15b8c9daf3e326c38a12a1241347b1f19a99ff6c"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "studio-audience-checkout-20261006",
    "contract": "KeelOneMintBatch",
    "address": "0xF3F919f9841eAcd166E49EBc42660e1F48491018",
    "block": "11860363",
    "txHash": "0x2b353f0a5c17e5f55a86a661cd71287bf0148bc45e92357977936676f4564d95",
    "runtimeCodeHash": "0xa460048aa67eecce1f61733a005a16f3655aca832797e14eb1681adf5bf3eae3"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "studio-audience-checkout-20261006",
    "contract": "OpenOneMintController",
    "address": "0xEF3306378895a9B49ed16416A8fCb767E79b8595",
    "block": "11860365",
    "txHash": "0x653fc27e4b519864ba76db379fa6beef5fb17bfe4a8c9869395a3fd47671d894",
    "runtimeCodeHash": "0x9ffeb1f1302e98b028184673c50ba3bb869fa52f0be1533c5c948c9f7ca6a4bf"
  },
  {
    "module": "keel-publication",
    "chainId": 11155111,
    "instance": "creator-inline-20261005",
    "contract": "KeelCarrierBatcher",
    "address": "0x1854858Ea4574f4e293466DD0309BB3178d568E3",
    "block": "11831595",
    "txHash": "0xe29fc6aa8bca6b986b266eb5e69a13c6e72f1966ccb3ce42cc42411424c48739",
    "runtimeCodeHash": "0x14e1b4260b30e4240c062b1c4562e2caefd45d0f70acaf086a31f695db8f0d21"
  },
  {
    "module": "keel-publication",
    "chainId": 11155111,
    "instance": "redline-reference-20261004",
    "contract": "KeelCarrierBatcher",
    "address": "0x1854858Ea4574f4e293466DD0309BB3178d568E3",
    "block": "11831595",
    "txHash": "0xe29fc6aa8bca6b986b266eb5e69a13c6e72f1966ccb3ce42cc42411424c48739",
    "runtimeCodeHash": "0x14e1b4260b30e4240c062b1c4562e2caefd45d0f70acaf086a31f695db8f0d21"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultArcadeRegistry",
    "address": "0xC5356FfEBE287145AF9d52300cCd39d0A5787e01",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultCharacter721",
    "address": "0xf9EaE6838C718BbeF224c4846b01e35306B60520",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultCharacterPackV2",
    "address": "0xdBC33a7633130f11E2A5E020d7029E68402AC489",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  }
] as const;
