// GENERATED BY `keel sync` — DO NOT EDIT BY HAND.
// Source: packages/contracts/modules/*/keel.module.json and */deployments/*.json

/** Reusable protocol infrastructure. Each module ships as its own repository. */
export type KeelModuleId = "keel-kernel" | "keel-codecs" | "keel-hold" | "keel-artifacts" | "keel-graph" | "keel-harness" | "keel-presentation" | "keel-die" | "keel-creator-identity" | "keel-mint-access" | "keel-market" | "keel-anchors" | "keel-crucible" | "keel-ip-control" | "keel-sleeve" | "keel-web3-url" | "keel-cross-chain-mint" | "keel-stake";

/**
 * Concrete products built on the modules. Apps consume modules exactly as an
 * outside integrator does, and no module may depend on one.
 */
export type KeelAppId = "keel-canvas" | "cool-s" | "line" | "vault-runner";

/** Anything with contracts on a chain — a module or an app. */
export type KeelUnitId = KeelModuleId | KeelAppId;

/** Role labels units are grouped and browsed by. */
export type KeelModuleGroup = "apps" | "assets" | "core" | "market" | "provenance" | "render" | "token";

export interface KeelModule {
  readonly id: KeelUnitId;
  /** "module" is reusable infrastructure; "app" is a product built on it. */
  readonly kind: "module" | "app";
  readonly title: string;
  /** Role label; the topic this module's repository is tagged with. */
  readonly group: KeelModuleGroup;
  readonly summary: string;
  readonly version: string;
  /** Repository this module is published from once split out of the monorepo. */
  readonly repo: string | null;
  /** Repository visibility, when known. Affects installation, not resolution. */
  readonly visibility: "public" | "private" | null;
  readonly deps: readonly KeelUnitId[];
  readonly contracts: readonly string[];
  /** Contracts with creation bytecode — the ones a release actually deploys. */
  readonly deployable: readonly string[];
}

export interface KeelDeployment {
  readonly module: KeelUnitId;
  readonly chainId: number;
  /** Named instance: one chain can carry several deployments of a module. */
  readonly instance: string;
  readonly contract: string;
  readonly address: `0x${string}`;
  readonly block: string | null;
  readonly txHash: string | null;
}

export const KEEL_MODULES: readonly KeelModule[] = [
  {
    "id": "keel-kernel",
    "kind": "module",
    "title": "Kernel",
    "group": "core",
    "visibility": "private",
    "summary": "Admin/access primitives and encoding helpers every other module is allowed to import.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-kernel",
    "deps": [],
    "contracts": [
      "SafeAdminAccessControl.sol",
      "libraries/JsonEscape.sol",
      "libraries/KeelCodeIdentity.sol",
      "libraries/KeelUriEscape.sol",
      "KeelFeeTreasury.sol",
      "libraries/KeelPlatformFees.sol",
      "libraries/KeelGovernance.sol",
      "KeelAccessGroups.sol",
      "KeelLocalPause.sol",
      "libraries/KeelPause.sol",
      "libraries/KeelTokenURIEnvelope.sol",
      "libraries/KeelMintSeeded.sol",
      "libraries/KeelMintSeededBatches.sol",
      "interfaces/IKeelMintSeededBatchErrors.sol",
      "interfaces/IKeelMintSeededErrors.sol",
      "interfaces/IKeelMintSeededData.sol",
      "interfaces/IKeelVrfV2Plus.sol",
      "interfaces/IKeelGovernanceErrors.sol", "interfaces/IKeelPlatformFeeErrors.sol", "interfaces/IKeelFeeTreasuryErrors.sol", "interfaces/IKeelFeeTreasuryEvents.sol",
      "interfaces/IKeelAccessGroupErrors.sol",
      "interfaces/IKeelAccessGroupEvents.sol",
      "KeelRecoveryGroups.sol",
      "interfaces/IKeelRecoveryErrors.sol"
    ],
    "deployable": [
      "KeelFeeTreasury",
      "KeelAccessGroups",
      "KeelRecoveryGroups"
    ]
  },
  {
    "id": "keel-codecs",
    "kind": "module",
    "title": "Codecs",
    "group": "core",
    "visibility": "private",
    "summary": "Pure, stateless decoders: RLP, Merkle-Patricia, block headers, IPFS CIDs, base32/58, BLS12-381.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-codecs",
    "deps": [],
    "contracts": [
      "libraries/KeelRlp.sol",
      "libraries/KeelBlockHeader.sol",
      "libraries/KeelMerklePatricia.sol",
      "libraries/KeelEthAccount.sol",
      "libraries/KeelOpOutputRoot.sol",
      "libraries/KeelIpfsCid.sol",
      "libraries/KeelDagPb.sol",
      "libraries/KeelBase32.sol",
      "libraries/KeelBase58.sol",
      "libraries/Bls12381.sol"
    ],
    "deployable": []
  },
  {
    "id": "keel-hold",
    "kind": "module",
    "title": "Storage",
    "group": "core",
    "visibility": "private",
    "summary": "Immutable content-addressed chunk storage and the artifact registry that activates revisions.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-hold",
    "deps": [
      "keel-kernel"
    ],
    "contracts": [
      "KeelHold.sol",
      "Ingot.sol",
      "KeelIndex.sol",
      "interfaces/IKeelHold.sol",
      "interfaces/IKeelHoldLimits.sol",
      "interfaces/IKeelHoldSeal.sol",
      "libraries/KeelSealValidation.sol",
      "libraries/KeelCastDispatch.sol",
      "interfaces/IKeelIndex.sol",
      "interfaces/IKeelHoldHarness.sol",
      "interfaces/IKeelHoldEvents.sol",
      "libraries/KeelHoldMetadata.sol",
      "interfaces/IKeelHoldErrors.sol",
      "interfaces/IKeelIndexErrors.sol",
      "interfaces/IKeelIndexEvents.sol"
    ],
    "deployable": [
      "Ingot",
      "KeelHold",
      "KeelIndex"
    ]
  },
  {
    "id": "keel-artifacts",
    "kind": "module",
    "title": "Object model",
    "group": "core",
    "visibility": "private",
    "summary": "The Keel object graph: objects, viewers, links, seeds, and the manager that fronts them.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-artifacts",
    "deps": [
      "keel-hold",
      "keel-kernel"
    ],
    "contracts": [
      "KeelArtifactRegistry.sol",
      "KeelManager.sol",
      "KeelManagerProxy.sol",
      "KeelHarnessRegistry.sol",
      "KeelLinkRegistry.sol",
      "KeelSeedRegistry.sol",
      "interfaces/IKeelMintSeedSource.sol",
      "interfaces/IKeelSeedRegistryErrors.sol",
      "interfaces/IKeelSeedRegistryEvents.sol",
      "interfaces/IKeelArtifactRegistry.sol",
      "interfaces/IKeelManager.sol",
      "interfaces/IKeelArtifactRevisionPolicy.sol",
      "interfaces/IKeelHarnessRegistry.sol",
      "interfaces/IKeelHarnessRegistryErrors.sol",
      "interfaces/IKeelHarnessRegistryEvents.sol",
      "KeelManagerRecovery.sol",
      "KeelManagerRpcPolicy.sol",
      "interfaces/IKeelManagerErrors.sol",
      "interfaces/IKeelManagerEvents.sol",
      "interfaces/IKeelManagerRecoveryErrors.sol",
      "interfaces/IKeelManagerRecoveryEvents.sol",
      "interfaces/IKeelManagerRpcErrors.sol",
      "interfaces/IKeelManagerRpcEvents.sol",
      "interfaces/IKeelManagerTypes.sol",
      "libraries/KeelManagerGovernorState.sol",
      "KeelLinkURIBuilder.sol",
      "interfaces/IKeelLinkURIBuilder.sol",
      "interfaces/IKeelLinkURIBuilderErrors.sol",
      "interfaces/IKeelLinkRegistryErrors.sol",
      "interfaces/IKeelLinkRegistryEvents.sol"
    ],
    "deployable": [
      "KeelArtifactRegistry",
      "KeelHarnessRegistry",
      "KeelLinkRegistry",
      "KeelManager",
      "KeelManagerProxy",
      "KeelSeedRegistry",
      "KeelManagerRecovery",
      "KeelManagerRpcPolicy",
      "KeelLinkURIBuilder"
    ]
  },
  {
    "id": "keel-graph",
    "kind": "module",
    "title": "Graph trust lattice",
    "group": "core",
    "visibility": "private",
    "summary": "Graph/plugin/library/module registries \u2014 the on-chain trust lattice the runtime re-derives against.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-graph",
    "deps": [],
    "contracts": [
      "KeelGraphRegistry.sol",
      "KeelPluginRegistry.sol",
      "KeelModuleReviewRegistry.sol",
      "KeelLibraryRegistry.sol",
      "KeelAssetTagRegistry.sol",
      "interfaces/IKeelGraphRegistry.sol",
      "interfaces/IKeelContractPlugin.sol"
    ],
    "deployable": [
      "KeelAssetTagRegistry",
      "KeelGraphRegistry",
      "KeelLibraryRegistry",
      "KeelModuleReviewRegistry",
      "KeelPluginRegistry"
    ]
  },
  {
    "id": "keel-harness",
    "kind": "module",
    "title": "On-chain HTML builder",
    "group": "render",
    "visibility": "private",
    "summary": "Assembles viewer HTML from chunk-stored resources entirely on chain.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-harness",
    "deps": [
      "keel-hold",
      "keel-kernel"
    ],
    "contracts": [
      "KeelHarnessBuilder.sol",
      "KeelPercentTokenURIBuilder.sol",
      "interfaces/IKeelHarnessBuilder.sol",
      "interfaces/IKeelPercentTokenURIBuilder.sol",
      "libraries/KeelHarnessContextDispatch.sol",
      "libraries/KeelPreEncodedTokenURI.sol",
      "libraries/KeelPreparedTokenURI.sol",
      "KeelObjectURIBuilder.sol",
      "KeelRawTokenURIBuilder.sol",
      "interfaces/IKeelObjectURIBuilder.sol",
      "interfaces/IKeelRawTokenURIBuilder.sol"
    ],
    "deployable": [
      "KeelHarnessBuilder",
      "KeelPercentTokenURIBuilder",
      "KeelObjectURIBuilder",
      "KeelRawTokenURIBuilder"
    ]
  },
  {
    "id": "keel-presentation",
    "kind": "module",
    "title": "Presentation state",
    "group": "core",
    "visibility": "private",
    "summary": "Presentation/visual state ledgers that record what a token currently renders as.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-presentation",
    "deps": [],
    "contracts": [
      "KeelPresentationStateRegistry.sol",
      "KeelVisualStateLedger.sol",
      "interfaces/IKeelPresentationRegistry.sol"
    ],
    "deployable": [
      "KeelPresentationStateRegistry",
      "KeelVisualStateLedger"
    ]
  },
  {
    "id": "keel-die",
    "kind": "module",
    "title": "Token base",
    "group": "token",
    "visibility": "private",
    "summary": "Compact creator-owned ERC-721/ERC-1155 collections, a shared multi-creator ERC-1155, renderer boundaries, and factories that organize them.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-die",
    "deps": [
      "keel-kernel",
      "keel-harness",
      "keel-presentation",
      "keel-artifacts",
      "keel-hold",
      "keel-codecs"
    ],
    "contracts": [
      "KEEL721.sol",
      "KeelMintSeeded721.sol",
      "KeelMintSeeded721A.sol",
      "KEEL721Deployer.sol",
      "KeelFactory.sol",
      "KeelFactorySepolia.sol",
      "KeelCreator721.sol",
      "KeelCreator721A.sol",
      "KeelCreatorSeeded721A.sol",
      "KeelSeedBlockArchive.sol",
      "KeelSeedVrfAdapter.sol",
      "interfaces/IKeelSeedVrf.sol",
      "interfaces/IKeelSeedVrfErrors.sol",
      "interfaces/IKeelSeedVrfEvents.sol",
      "interfaces/IKeelCreatorSeedErrors.sol",
      "interfaces/IKeelCreatorSeedEvents.sol",
      "KeelCreator1155.sol",
      "interfaces/IKeelCreatorLifecycleEvents.sol",
      "interfaces/IKeelCreatorItemErrors.sol",
      "interfaces/IKeelItemCapacityEvents.sol",
      "interfaces/IKeelCreator1155Events.sol",
      "KeelShared1155.sol",
      "interfaces/IKeelItemBatchMintTarget.sol",
      "interfaces/IKeelMintBatchErrors.sol",
      "interfaces/IKeelShared1155Errors.sol",
      "interfaces/IKeelShared1155Events.sol",
      "KeelCreatorFactory.sol",
      "interfaces/IKeelCreatorFactoryErrors.sol",
      "interfaces/IKeelCreatorFactoryEvents.sol",
      "KeelArtifactTokenRenderer.sol",
      "interfaces/IKeelMintable.sol",
      "interfaces/IKeelMintDataSource.sol",
      "interfaces/IKeelMintCapacity.sol",
      "interfaces/IKeelCampaignAuthorizer.sol",
      "interfaces/IKeelItemMintTarget.sol",
      "interfaces/IKeelTokenRenderer.sol",
      "interfaces/IKeelCreatorDirectory.sol",
      "KeelRawPrepared721.sol",
      "Keel721Presentation.sol",
      "interfaces/IKeel721Errors.sol",
      "interfaces/IKeel721Events.sol",
      "interfaces/IKeelCreatorCollectionErrors.sol",
      "interfaces/IKeelCreatorCollectionEvents.sol",
      "interfaces/IKeelMintTargetErrors.sol",
      "interfaces/IKeelStrikeCapacityEvents.sol",
      "interfaces/IKeel721PresentationEvents.sol",
      "KeelRouted721.sol",
      "libraries/KeelSeedBlockEntropy.sol",
      "interfaces/IKeelDeferredCollectionResolver.sol",
      "interfaces/IKeelDeferredMintSetup.sol"
    ],
    "deployable": [
      "KEEL721",
      "KEEL721Deployer",
      "KeelArtifactTokenRenderer",
      "KeelCreator1155",
      "KeelCreator721",
      "KeelCreator721A",
      "KeelCreatorSeeded721A",
      "KeelSeedBlockArchive",
      "KeelSeedVrfAdapter",
      "KeelCreatorFactory",
      "KeelFactory",
      "KeelFactorySepolia",
      "KeelShared1155",
      "KeelRawPrepared721",
      "Keel721Presentation",
      "KeelRouted721"
    ]
  },
  {
    "id": "keel-creator-identity",
    "kind": "module",
    "title": "Creator identity",
    "group": "token",
    "visibility": "private",
    "summary": "Creator profiles, commitments, and attribution records.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-creator-identity",
    "deps": [
      "keel-artifacts",
      "keel-kernel"
    ],
    "contracts": [
      "KeelCreatorProfileRegistry.sol",
      "KeelCreatorCommitmentRegistry.sol",
      "KeelAttributionRegistry.sol",
      "interfaces/IKeelCreatorProfileRegistry.sol"
    ],
    "deployable": [
      "KeelAttributionRegistry",
      "KeelCreatorCommitmentRegistry",
      "KeelCreatorProfileRegistry"
    ]
  },
  {
    "id": "keel-mint-access",
    "kind": "module",
    "title": "Mint access",
    "group": "token",
    "visibility": "private",
    "summary": "Shared mint routes, OneMint admission queues, verifiable queue/reward entropy, and community or achievement reward claims.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-mint-access",
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-creator-identity",
      "keel-hold"
    ],
    "contracts": [
      "KeelMintQueue.sol",
      "QueuePriorityHeap.sol",
      "KeelQueueAccess.sol",
      "KeelRewardClaims.sol",
      "KeelMintRewardEntropy.sol",
      "FrayAuctionIssuer.sol",
      "KeelMintGate.sol",
      "KeelMintRouteRegistry.sol",
      "interfaces/IKeelMintBatchRouteRegistry.sol",
      "interfaces/IKeelMintRouteErrors.sol",
      "interfaces/IKeelMintRouteEvents.sol",
      "OneMintCore.sol",
      "KeelOneMintBatch.sol",
      "interfaces/IKeelOneMintBatch.sol",
      "OneMintController.sol",
      "OpenOneMintController.sol",
      "interfaces/IKeelAccessGate.sol",
      "interfaces/IKeelMintAdapter.sol",
      "interfaces/IKeelMintHook.sol",
      "interfaces/IKeelMintRouteRegistry.sol",
      "interfaces/IKeelOneMintErrors.sol",
      "interfaces/IKeelMintGateErrors.sol",
      "interfaces/IKeelMintGateEvents.sol",
      "libraries/KeelMintPricing.sol",
      "libraries/KeelNftCouponClaims.sol",
      "interfaces/IKeelMintPricingErrors.sol",
      "interfaces/IKeelMintCoupons.sol",
      "interfaces/IKeelOneMintEvents.sol",
      "KeelMintReleases.sol",
      "KeelMintReleaseInspector.sol",
      "libraries/KeelReleasePolicy.sol",
      "interfaces/IKeelReleaseErrors.sol",
      "interfaces/IKeelReleaseEvents.sol",
      "KeelQueueDemand.sol",
      "KeelQueuePriority.sol",
      "KeelQueueReadAdapter.sol",
      "interfaces/IKeelQueueLifecycle.sol",
      "KeelQueueLotteryEngine.sol",
      "KeelQueueLotteryPool.sol",
      "interfaces/IKeelLotteryQueueState.sol",
      "interfaces/IKeelQueueEntropyRecovery.sol",
      "interfaces/IKeelMintRewardEntropyErrors.sol",
      "interfaces/IKeelMintRewardEntropyEvents.sol",
      "interfaces/IKeelQueueAccessErrors.sol",
      "interfaces/IKeelQueueAccessEvents.sol",
      "interfaces/IKeelQueueLotteryEngineErrors.sol",
      "interfaces/IKeelQueueLotteryPoolErrors.sol",
      "interfaces/IKeelQueueDemandErrors.sol",
      "interfaces/IKeelQueuePriorityErrors.sol",
      "interfaces/IKeelQueueReadAdapterErrors.sol",
      "interfaces/IKeelQueueDemandEvents.sol",
      "interfaces/IKeelQueuePeriod.sol",
      "interfaces/IKeelMintQueueErrors.sol",
      "interfaces/IKeelMintQueueEvents.sol",
      "interfaces/IKeelAuctionIssuer.sol",
      "interfaces/IKeelAuctionIssuerErrors.sol",
      "interfaces/IKeelAuctionIssuerEvents.sol",
      "interfaces/IKeelAuctionReleaseRouter.sol",
      "interfaces/IKeelUniqueTarget.sol",
      "interfaces/IKeelDeferredAuctionIssuer.sol",
      "interfaces/IKeelAuctionPublication.sol"
    ],
    "deployable": [
      "FrayAuctionIssuer",
      "KeelMintGate",
      "KeelMintRouteRegistry",
      "KeelOneMintBatch",
      "OneMintController",
      "OpenOneMintController",
      "KeelMintQueue",
      "KeelRewardClaims",
      "KeelMintRewardEntropy",
      "KeelQueueAccess",
      "KeelQueueDemand",
      "KeelQueuePriority",
      "KeelQueueReadAdapter",
      "KeelQueueLotteryEngine",
      "KeelQueueLotteryPool"
    ]
  },
  {
    "id": "keel-market",
    "kind": "module",
    "title": "Market",
    "group": "market",
    "visibility": "private",
    "summary": "The Keel marketplace plugin contract.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-market",
    "deps": [
      "keel-graph",
      "keel-kernel"
    ],
    "contracts": [
      "KeelMarket.sol"
    ],
    "deployable": [
      "KeelMarket"
    ]
  },
  {
    "id": "keel-anchors",
    "kind": "module",
    "title": "Anchors",
    "group": "provenance",
    "visibility": "private",
    "summary": "Cross-chain and off-chain anchoring: portable commitments, permissionless L2 state proofs, and zk verification backends.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-anchors",
    "deps": [
      "keel-kernel",
      "keel-codecs",
      "keel-artifacts",
      "keel-graph",
      "keel-hold"
    ],
    "contracts": [
      "KeelProofUpgradeController.sol",
      "KeelAttestedAnchorRegistry.sol",
      "KeelPortableAnchorRegistry.sol",
      "KeelAnchorReplicationBridge.sol",
      "KeelL2AnchorVerifier.sol",
      "KeelL2StateVerifier.sol",
      "KeelSettlementRegistry.sol",
      "KeelZkAnchorVerifier.sol",
      "KeelZkVerifyProofBackend.sol",
      "KeelZkVerifyProofVerifier.sol",
      "KeelSp1GatewayProofBackend.sol",
      "KeelSp1GatewayProofVerifier.sol",
      "KeelIpfsCidVerifier.sol",
      "KeelNodeRegistry.sol",
      "interfaces/IKeelAnchorProofBackend.sol",
      "interfaces/IKeelAnchorProofVerifier.sol",
      "interfaces/IKeelAnchoredChainQueries.sol",
      "interfaces/IKeelSettlementSource.sol"
    ],
    "deployable": [
      "KeelProofUpgradeController",
      "KeelAnchorReplicationBridge",
      "KeelAttestedAnchorRegistry",
      "KeelIpfsCidVerifier",
      "KeelL2AnchorVerifier",
      "KeelL2StateVerifier",
      "KeelNodeRegistry",
      "KeelPortableAnchorRegistry",
      "KeelSettlementRegistry",
      "KeelSp1GatewayProofBackend",
      "KeelSp1GatewayProofVerifier",
      "KeelZkAnchorVerifier",
      "KeelZkVerifyProofBackend",
      "KeelZkVerifyProofVerifier"
    ]
  },
  {
    "id": "keel-crucible",
    "kind": "module",
    "title": "Collection verification",
    "group": "provenance",
    "visibility": "private",
    "summary": "Collection attestation, community replication, and preservation bounties.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-crucible",
    "deps": [
      "keel-kernel",
      "keel-hold",
      "keel-artifacts"
    ],
    "contracts": [
      "KeelCollectionVerificationRegistry.sol",
      "KeelCollectionVerificationHookBase.sol",
      "KeelCollectionAttestationRegistry.sol",
      "KeelCommunityReplicationRegistry.sol",
      "interfaces/IKeelCollectionVerificationHook.sol",
      "interfaces/IKeelCollectionVerificationAdapter.sol",
      "interfaces/ICommunityHold.sol"
    ],
    "deployable": [
      "KeelCollectionAttestationRegistry",
      "KeelCollectionVerificationRegistry",
      "KeelCommunityReplicationRegistry",
    ]
  },
  {
    "id": "keel-ip-control",
    "kind": "module",
    "title": "IP control",
    "group": "provenance",
    "visibility": "private",
    "summary": "On-chain IP rights control, wrapped-721 custody, and the executor that acts on granted rights.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-ip-control",
    "deps": [
      "keel-hold",
      "keel-artifacts",
      "keel-kernel"
    ],
    "contracts": [
      "KeelIPControl.sol",
      "KeelIPActionExecutor.sol",
      "KeelIPWrapped721.sol",
      "interfaces/IKeelIPControl.sol",
      "interfaces/IKeelIPMintTarget.sol"
    ],
    "deployable": [
      "KeelIPActionExecutor",
      "KeelIPControl",
      "KeelIPWrapped721"
    ]
  },
  {
    "id": "keel-sleeve",
    "kind": "module",
    "title": "Metadata resolver",
    "group": "core",
    "visibility": "private",
    "summary": "Token JSON resolution for collections that delegate metadata assembly.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-sleeve",
    "deps": [
      "keel-hold"
    ],
    "contracts": [
      "KeelSleeve.sol",
      "interfaces/IKeelTokenJSONResolver.sol",
      "KeelStoredTokenJSON.sol",
      "KeelTokenMatrix.sol"
    ],
    "deployable": [
      "KeelSleeve",
      "KeelStoredTokenJSON",
      "KeelTokenMatrix"
    ]
  },
  {
    "id": "keel-web3-url",
    "kind": "module",
    "title": "web3:// adapter",
    "group": "render",
    "visibility": "private",
    "summary": "ERC-5219/7617 resource adapter exposing Keel content over web3:// URLs, plus its demos.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-web3-url",
    "deps": [
      "keel-hold"
    ],
    "contracts": [
      "KeelWeb3ResourceAdapter.sol",
      "interfaces/IDecentralizedApp.sol",
      "interfaces/IERC7572.sol"
    ],
    "deployable": [
      "KeelWeb3ResourceAdapter"
    ]
  },
  {
    "id": "keel-cross-chain-mint",
    "kind": "module",
    "title": "Cross-chain mint",
    "group": "token",
    "visibility": "private",
    "summary": "Bridged mint intents and the batcher that carries them between chains.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-cross-chain-mint",
    "deps": [
      "keel-kernel",
      "keel-mint-access",
      "keel-hold"
    ],
    "contracts": [
      "KeelCrossChainMintBridge.sol",
      "KeelCarrierBatcher.sol",
      "KeelHistoryPublicationJob.sol",
      "KeelPublicationJob.sol"
    ],
    "deployable": [
      "KeelCarrierBatcher",
      "KeelCrossChainMintBridge",
      "KeelHistoryPublicationJob",
      "KeelPublicationJob"
    ]
  },
  {
    "id": "keel-stake",
    "kind": "module",
    "title": "Stake objects",
    "group": "assets",
    "visibility": "private",
    "summary": "Stake-object custody and the seasonal grove state that consumes it.",
    "version": "0.3.0",
    "repo": "keel-web3/keel-stake",
    "deps": [
      "keel-artifacts",
      "keel-kernel"
    ],
    "contracts": [
      "KeelStakeObjectManager.sol"
    ],
    "deployable": [
      "KeelStakeObjectManager"
    ]
  }
] as const;

/** Products built on the modules; excluded from the module registry by design. */
export const KEEL_APPS: readonly KeelModule[] = [
  {
    "id": "keel-canvas",
    "kind": "app",
    "title": "Canvas",
    "group": "apps",
    "visibility": null,
    "summary": "Shared canvas renderer/splitter/composer surface that both CoolS and LINE collections render through.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-artifacts"
    ],
    "contracts": [
      "CoolSCanvas721.sol",
      "CoolSCanvasRenderer.sol",
      "CoolSCanvasSplitter.sol",
      "CoolSCanvasMintController.sol",
      "CoolSComposer.sol",
      "interfaces/ICoolSCanvasRenderer.sol",
      "interfaces/ICoolSCanvasSplitter.sol",
      "interfaces/ICoolSCanvasView.sol",
      "interfaces/ILINE721.sol",
      "interfaces/ILINEThumbnailSource.sol",
      "libraries/CoolSCanvasStorage.sol"
    ],
    "deployable": [
      "CoolSCanvas721",
      "CoolSCanvasMintController",
      "CoolSCanvasRenderer",
      "CoolSCanvasSplitter",
      "CoolSComposer"
    ]
  },
  {
    "id": "cool-s",
    "kind": "app",
    "title": "CoolS",
    "group": "apps",
    "visibility": null,
    "summary": "The CoolS collection: generative mint hook, metadata renderer, release resolver, novelty ledger, visual registry.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-presentation"
    ],
    "contracts": [
      "CoolS721.sol",
      "CoolSMetadataRendererV1.sol",
      "CoolSNoveltyLedgerV1.sol",
      "CoolSReleaseResolverV1.sol",
      "CoolSTargetTableV1.sol",
      "CoolSVisualRegistryV1.sol",
      "CoolSLocalVRFCoordinator.sol",
      "KeelGenerativeMintHookBase.sol",
      "interfaces/ICoolSReleaseResolverV1.sol",
      "libraries/CoolSVisualStateCodecV1.sol"
    ],
    "deployable": [
      "CoolS721",
      "CoolSLocalVRFCoordinator",
      "CoolSMetadataRendererV1",
      "CoolSNoveltyLedgerV1",
      "CoolSReleaseResolverV1",
      "CoolSTargetTableV1",
      "CoolSVisualRegistryV1"
    ]
  },
  {
    "id": "line",
    "kind": "app",
    "title": "LINE",
    "group": "apps",
    "visibility": null,
    "summary": "The LINE collection and its on-chain thumbnail renderer.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-die",
      "keel-canvas",
      "keel-artifacts"
    ],
    "contracts": [
      "LINE721.sol",
      "LINEThumbnail.sol",
      "LINEThumbnailRenderer.sol"
    ],
    "deployable": [
      "LINE721",
      "LINEThumbnail",
      "LINEThumbnailRenderer"
    ]
  },
  {
    "id": "vault-runner",
    "kind": "app",
    "title": "Vault Runner",
    "group": "apps",
    "visibility": null,
    "summary": "The Vault Runner game system: characters, packs, items, arcade/achievement registries, run settlement, map auctions.",
    "version": "0.3.0",
    "repo": null,
    "deps": [
      "keel-kernel",
      "keel-die",
      "keel-artifacts",
      "keel-hold",
      "keel-crucible",
      "keel-harness"
    ],
    "contracts": [
      "VaultCharacter721.sol",
      "VaultCharacterMetadataRenderer.sol",
      "VaultCharacterRegistry.sol",
      "VaultCharacterPackV2.sol",
      "VaultCharacterStarterPack.sol",
      "VaultItem1155.sol",
      "VaultGameCard.sol",
      "VaultArcadeRegistry.sol",
      "VaultAchievementRegistry.sol",
      "VaultMapAuction.sol",
      "VaultRunLeaderboard.sol",
      "VaultRunLootExtraction.sol",
      "VaultRunSignatureAuthority.sol",
      "VaultSpriteAssetRegistry.sol",
      "interfaces/IVaultRunSource.sol",
      "interfaces/IVaultHardcoreRunSource.sol",
      "interfaces/IVaultRunSignatureAuthority.sol"
    ],
    "deployable": [
      "VaultAchievementRegistry",
      "VaultArcadeRegistry",
      "VaultCharacter721",
      "VaultCharacterMetadataRenderer",
      "VaultCharacterPackV2",
      "VaultCharacterRegistry",
      "VaultCharacterStarterPack",
      "VaultGameCard",
      "VaultItem1155",
      "VaultMapAuction",
      "VaultRunLeaderboard",
      "VaultRunLootExtraction",
      "VaultRunSignatureAuthority",
      "VaultSpriteAssetRegistry"
    ]
  }
] as const;

export const KEEL_DEPLOYMENTS: readonly KeelDeployment[] = [
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelArtifactRegistry",
    "address": "0xe85884ba2af3932d4f98507668ed5fe8fed6db92",
    "block": "11629038",
    "txHash": "0x235a86349768f288282f939b4decfa211bf45acf691a74dc1490c70ea0037d41"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelHarnessRegistry",
    "address": "0xa5d6ae35c327f998403aa1eb713df3741e3f3136",
    "block": "11629039",
    "txHash": "0xf7e21d4950805b330a8e11f532695586353ae1c41121efc237daee979bded83f"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelLinkRegistry",
    "address": "0xc2b94319334359171a653c93e402b12b93e24102",
    "block": "11629040",
    "txHash": "0x2ede42b1097011f7485c99e85d0eefbd2d69fbe1234d52858bdd8f68e8c42f7e"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelManager",
    "address": "0x940004faaee674c99b20ca7ecce6f877b996c3e5",
    "block": "11629033",
    "txHash": "0x0f0d3bbd3aa1266c13c763235b4fefaf999849ac971c78a9574f7a89b0d8229e"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelManagerProxy",
    "address": "0x7cb6d62cdd968ba45a8a1f0d99a02e5e274fe6e3",
    "block": "11476924",
    "txHash": "0xd651408d7ec6f222aa5a47655ce34e7f92fd02a92c58bee1f1f69c69d25455c2"
  },
  {
    "module": "keel-artifacts",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelSeedRegistry",
    "address": "0xf6b301e56c813692aeb75b9659864c7e76cf4c8b",
    "block": "11629041",
    "txHash": "0xc44f7d534294cf1f47c46c9751fa56f007fff6ee09b06080918f20e2a302e672"
  },
  {
    "module": "keel-creator-identity",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelCreatorProfileRegistry",
    "address": "0xa4112eda52ca519adaeebee7c12c4770594529fa",
    "block": "11476926",
    "txHash": "0x09edbc01e0f41681c211e2781d54ba5f8a7931ea14224bb730b24773365c51a6"
  },
  {
    "module": "keel-crucible",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelCommunityReplicationRegistry",
    "address": "0xe8a4618e7327c75631afcdd2ff7b0f4a73d42595",
    "block": "11629043",
    "txHash": "0x10993ef95265d08e7beabc0c88584f2963ddc3a021c6c4e25a50c847277d8717"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KEEL721",
    "address": "0x71B25649E8A27992494eDAD355497c0Bea50A8e0",
    "block": "11476935",
    "txHash": "0x77739909a00b20931c21517d1594dbe386ad94ce0fdced4f6321aec16db03bde"
  },
  {
    "module": "keel-die",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelFactory",
    "address": "0x8839dab4505128378947aa2f75a0556554043ce6",
    "block": "11629044",
    "txHash": "0xba468375724a1f02bc2baec26da7a57592c89dd16e734ae7d2fc7ced562671cd"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelGraphRegistry",
    "address": "0x5b86439598d2091bf45971c3676eb25c5d64dca4",
    "block": "11476949",
    "txHash": "0x894cb84bf69f040db859ad9dd018c7fb62059282015e384422f6c73114ef2a72"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelPluginRegistry",
    "address": "0xb7a4f9d0ef9d81ab4190d847e804e27c1ea820fd",
    "block": "11476951",
    "txHash": "0x555896b004c2cf657d46ba545436dfaa7e3ea30b5ffaa06b8dd15b034ea6730f"
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "trusted-runtime",
    "contract": "KeelGraphRegistry",
    "address": "0x5b86439598d2091bf45971c3676eb25c5d64dca4",
    "block": null,
    "txHash": null
  },
  {
    "module": "keel-graph",
    "chainId": 11155111,
    "instance": "trusted-runtime",
    "contract": "KeelModuleReviewRegistry",
    "address": "0x9abb1f929a05e0ddf558aa9f594ec7775e28f8b2",
    "block": null,
    "txHash": null
  },
  {
    "module": "keel-harness",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelHarnessBuilder",
    "address": "0x7ac86609d6781e896c541210fdd8d1d919c5584a",
    "block": "11631488",
    "txHash": "0x822a9256583393e43a4fbca24adbc5bf8ba8f5611ae889fcdb08ae46f4a7e2d6"
  },
  {
    "module": "keel-hold",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelHold",
    "address": "0x0a4f31d5ab08029e4c68f6f3227d9fa3a2d66267",
    "block": "11559677",
    "txHash": "0xae9e37ce8705258f4395498747e03682207d3a4e04e23e734086fedd01d404ef"
  },
  {
    "module": "keel-hold",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelIndex",
    "address": "0x2b706ded15fb27a582da256321f2b3295413b8ac",
    "block": "11559678",
    "txHash": "0x93bdfd7694deb532a01aee4092020b8aad25a1720317d609949ab68166e944fc"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPActionExecutor",
    "address": "0x82548953d1a8baba9f4902844877FFA747ff243D",
    "block": "11491417",
    "txHash": "0xf5fcae22f51b8f381ef67c80b4f6f399e3c176936e45ba36813f49aaad8e3347"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPControl",
    "address": "0x9f62Aec9E1bd5117864C6A19a7FC8C4e51F39aD0",
    "block": "11491416",
    "txHash": "0x924da433760a9ecbfbf1d146a328c065bdf04960d8133c13401763f82293113d"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "ip-v1",
    "contract": "KeelIPWrapped721",
    "address": "0xD6290b9777B1Be895719e32900552107aADD674c",
    "block": "11491418",
    "txHash": "0x8d2653dcc830a8a400ac5c6cd10d543d3d289fc3e1a1c34701c76e79f009888d"
  },
  {
    "module": "keel-ip-control",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelIPControl",
    "address": "0x1b982718504aef51423f20856b79c62378cb62eb",
    "block": "11629049",
    "txHash": "0x6372164607cc4ac7322669f4938909cc34821ffc04c357cb808e51c008d6ba50"
  },
  {
    "module": "keel-market",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelMarket",
    "address": "0x4f9c6ea07aed067c3f04d798bf22a1e6c5c524a8",
    "block": "11629048",
    "txHash": "0x58e89f90f505e167890dba648ede9e1811083a7fd7461dafa3abc2e5fd93c0ac"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelMintGate",
    "address": "0x9f21416da06edddb7f21a70bcbc91cd732803262",
    "block": "11629047",
    "txHash": "0x8ed484bcf0319f0ecf56a3b727f0b8d7f6562d10ec81dc93bdd4fc924ea5b62f"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "KeelMintRouteRegistry",
    "address": "0x4dcc1132decf43ce72bbfad6f3ae109e85196fde",
    "block": "11629045",
    "txHash": "0xa2dd281009ab971aa62c2cd5fc58f09059075fb7615ad04c8273a2c469fb792f"
  },
  {
    "module": "keel-mint-access",
    "chainId": 11155111,
    "instance": "showcase",
    "contract": "OneMintController",
    "address": "0xc5a82b8320b6ad23cda749f079e3d7ad7b45cec9",
    "block": "11629046",
    "txHash": "0xb261303956960015186934bf8ca1131ed4f1284d3f771621897cfd4c34e5f867"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultArcadeRegistry",
    "address": "0xC5356FfEBE287145AF9d52300cCd39d0A5787e01",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultCharacter721",
    "address": "0xf9EaE6838C718BbeF224c4846b01e35306B60520",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  },
  {
    "module": "vault-runner",
    "chainId": 11155111,
    "instance": "vault-runner",
    "contract": "VaultCharacterPackV2",
    "address": "0xdBC33a7633130f11E2A5E020d7029E68402AC489",
    "block": "11484773",
    "txHash": "0x1ee75da2e0e69fb136c9d6cfb9dac31d33b0eaeb22380a074347a876dfa9ce7a"
  }
] as const;
