import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';
import {createPublicClient,createWalletClient,http,parseAbi,keccak256,encodeAbiParameters} from 'viem';import {layeredTokenSeed} from '../../sdk/dist/layered-chain.js';
const require=createRequire(import.meta.url);const solc=require('solc');
const source=readFileSync(new URL('../contracts/KeelLayerReveal.sol',import.meta.url),'utf8');
const mocks=`pragma solidity ^0.8.24;import './KeelLayerReveal.sol';contract Allocation is IKeelLayerAllocation {bytes32 public m;bytes32 public a;bool public frozen;constructor(bytes32 x,bytes32 y){m=x;a=y;}function freeze(bool v) external{frozen=v;}function layerAllocation() external view returns(bytes32,bytes32,uint256,bool){return(m,a,10,frozen);}function layerTokenExists(uint256 id) external pure returns(bool){return id>0&&id<=10;}} contract Coordinator {uint256 public calls; bytes public extra;function requestRandomWords(ILayerVRFCoordinator.RandomWordsRequest calldata r) external returns(uint256){calls++;extra=r.extraArgs;return calls;}function fulfill(address target,uint256 id,uint256 word) external {uint256[] memory words=new uint256[](1);words[0]=word;KeelLayerReveal(target).rawFulfillRandomWords(id,words);}}`;
const compiled=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'KeelLayerReveal.sol':{content:source},'Mocks.sol':{content:mocks}},settings:{optimizer:{enabled:true,runs:200},outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}})));
assert.deepEqual((compiled.errors??[]).filter(e=>e.severity==='error'),[]);console.log('Local Solidity build passed:',solc.version());
const node=spawn('/Users/ravonus/.foundry/bin/anvil',['--port','0'],{stdio:['ignore','pipe','pipe']});
let output='';const port=await new Promise((resolve,reject)=>{node.stdout.on('data',b=>{output+=b;const match=output.match(/Listening on [^:]+:(\d+)/);if(match)resolve(match[1]);});node.stderr.on('data',b=>output+=b);node.on('error',reject);node.on('exit',code=>reject(Error('Isolated Anvil exited '+code+': '+output)));});
try{
 const client=createPublicClient({transport:http(`http://127.0.0.1:${port}`)});let accounts;for(let i=0;i<60;i++){if(node.exitCode!==null)throw Error(output);try{accounts=await client.request({method:'eth_accounts'});break;}catch{await new Promise(r=>setTimeout(r,100));}}if(!accounts)throw Error('Isolated chain did not start');const wallet=createWalletClient({account:accounts[0],transport:http(`http://127.0.0.1:${port}`)});
 const deploy=async(file,name,args=[])=>{const c=compiled.contracts[file][name];const hash=await wallet.deployContract({abi:c.abi,bytecode:'0x'+c.evm.bytecode.object,args,chain:null});return (await client.waitForTransactionReceipt({hash})).contractAddress;};
 const read=(address,file,name,functionName,args=[])=>client.readContract({address,abi:compiled.contracts[file][name].abi,functionName,args});
 const write=async(address,file,name,functionName,args=[])=>{const abi=compiled.contracts[file][name].abi;const {request}=await client.simulateContract({account:accounts[0],address,abi,functionName,args});const hash=await wallet.writeContract({...request,chain:null});const receipt=await client.waitForTransactionReceipt({hash});assert.equal(receipt.status,'success');return receipt;};
 const manifest='0x'+'1'.repeat(64),allocation='0x'+'2'.repeat(64),key='0x'+'3'.repeat(64);const {createHash}=await import('node:crypto');const digest=x=>'0x'+createHash('sha256').update(Buffer.from(x.slice(2),'hex')).digest('hex');
 const collection=await deploy('Mocks.sol','Allocation',[manifest,allocation]);const coordinator=await deploy('Mocks.sol','Coordinator');
 const config={creator:accounts[0],collection,manifestDigest:manifest,allocationDigest:allocation,ciphertextDigest:'0x'+'4'.repeat(64),keyCommitment:digest(key),creatorSeedCommitment:digest(key),supply:10n,revealAt:0n,mode:2,coordinator,keyHash:manifest,subscriptionId:1n,confirmations:3,callbackGasLimit:100000,nativePayment:true};
 const reveal=await deploy('KeelLayerReveal.sol','KeelLayerReveal',[config]);const rr=(fn,args=[])=>read(reveal,'KeelLayerReveal.sol','KeelLayerReveal',fn,args);const rw=(fn,args=[])=>write(reveal,'KeelLayerReveal.sol','KeelLayerReveal',fn,args);
 await assert.rejects(()=>rw('requestReveal'));await write(collection,'Mocks.sol','Allocation','freeze',[true]);await rw('requestReveal');await assert.rejects(()=>rw('requestReveal'));assert.equal(await read(coordinator,'Mocks.sol','Coordinator','calls'),1n);assert.equal(await read(coordinator,'Mocks.sol','Coordinator','extra'),'0x92fd1338'+'0'.repeat(63)+'1');await assert.rejects(()=>rw('publishKey',[key]));await assert.rejects(()=>rw('rawFulfillRandomWords',[1n,[0n]]));await assert.rejects(()=>write(coordinator,'Mocks.sol','Coordinator','fulfill',[reveal,2n,0n]));await write(coordinator,'Mocks.sol','Coordinator','fulfill',[reveal,1n,0n]);assert.equal(await rr('fulfilled'),true);assert.equal(await rr('rootSeed'),'0x'+'0'.repeat(64));await assert.rejects(()=>write(coordinator,'Mocks.sol','Coordinator','fulfill',[reveal,1n,5n]));await assert.rejects(()=>rw('publishKey',[manifest]));await rw('publishKey',[key]);await assert.rejects(()=>rw('publishKey',[key]));assert.equal(await rr('seedOf',[1n]),layeredTokenSeed({chainId:31337n,reveal,collection,manifest,allocation,supply:10n,rootSeed:'0x'+'0'.repeat(64),tokenId:1n}));await assert.rejects(()=>rr('seedOf',[11n]));await write(collection,'Mocks.sol','Allocation','freeze',[false]);await assert.rejects(()=>rr('seedOf',[1n]));await write(collection,'Mocks.sol','Allocation','freeze',[true]);
 const future=await deploy('KeelLayerReveal.sol','KeelLayerReveal',[{...config,mode:1}]);await write(future,'KeelLayerReveal.sol','KeelLayerReveal','requestReveal');await client.request({method:'anvil_mine',params:['0x104']});await assert.rejects(()=>write(future,'KeelLayerReveal.sol','KeelLayerReveal','settleFutureBlock'));await assert.rejects(()=>write(future,'KeelLayerReveal.sol','KeelLayerReveal','requestReveal'));
 const creator=await deploy('KeelLayerReveal.sol','KeelLayerReveal',[{...config,mode:0}]);await write(creator,'KeelLayerReveal.sol','KeelLayerReveal','requestReveal');await assert.rejects(()=>write(creator,'KeelLayerReveal.sol','KeelLayerReveal','revealCreatorSeed',[manifest]));await write(creator,'KeelLayerReveal.sol','KeelLayerReveal','revealCreatorSeed',[key]);assert.equal(await read(creator,'KeelLayerReveal.sol','KeelLayerReveal','rootSeed'),key);
 console.log('PASS: frozen allocation gate, official VRF tuple/extraArgs, authenticated request, zero word, once-only seed/key, wrong keys, token domain parity, mutable allocation refusal, future expiry without reroll, creator commitment. Local mock coordinator only.');
}finally{if(node.exitCode===null){const ended=new Promise(r=>node.once('exit',r));node.kill('SIGTERM');await ended;}}
