import assert from 'node:assert/strict';import test from 'node:test';
import {createPinnedKeelSepoliaSimulationTransport,assertKeelSimulationEnvelopes} from '../packages/sdk/dist/simulation-connection.js';
const gas='0xbebc200';const program={method:'eth_simulateV1',params:[{blockStateCalls:[{calls:[{gas,data:'0x1234'}]}],validation:true},'0x12']};
function socket({version='Geth/v1.17.7-stable/test',cap=gas,programCap=cap,revert=false}={}){const requests=[];let closed=0;return{requests,get closed(){return closed},socket:{readyState:1},close(){closed++;this.socket.readyState=3},async requestAsync({body}){requests.push(body);if(body.method==='web3_clientVersion')return{result:version};if(body.method==='eth_chainId')return{result:'0xaa36a7'};if(body.method==='eth_getBlockByNumber')return{result:{number:'0x12',timestamp:'0x6ac79200',gasLimit:gas}};if(body.method==='eth_simulateV1'){const isProgram=body.params[0].blockStateCalls[0].calls[0].data==='0x1234';return{result:body.params[0].blockStateCalls.map(b=>({transactions:b.calls.map(c=>({gas:isProgram?programCap:cap})),calls:b.calls.map(()=>({status:isProgram&&revert?'0x0':'0x1'}))}))};}throw Error('Unexpected method')}}}
test('selects on the retained socket and rejects low-capacity or incompatible connections before project calldata',async()=>{const nodes=[socket({version:'reth/v2.7.0'}),socket({cap:'0x2faf080'}),socket()];let i=0;const t=createPinnedKeelSepoliaSimulationTransport(async()=>nodes[i++]);await t.request(program);assert.equal(i,3);for(const node of nodes.slice(0,2)){assert.equal(node.closed,1);assert.ok(node.requests.every(r=>r.method!=='eth_simulateV1'||r.params[0].blockStateCalls[0].calls[0].data==='0x'));}assert.equal(nodes[2].requests.at(-1).params[0].validation,true);assert.equal(nodes[2].requests.at(-1).params[0].returnFullTransactions,true);await t.close();});
test('silent clamping of an actual program is provider-limit and never replays on another connection',async()=>{const node=socket({programCap:'0x2faf080',revert:true});let count=0;const t=createPinnedKeelSepoliaSimulationTransport(async()=>{count++;return node});await assert.rejects(t.request(program),e=>e.kind==='provider-limit'&&e.diagnostic.providerGasCap==='50000000');assert.equal(count,1);assert.equal(node.requests.filter(r=>r.method==='eth_simulateV1').length,2);await t.close();});
test('an actual program revert stays a revert; closed sockets fail without implicit replacement',async()=>{const node=socket({revert:true});let count=0;const t=createPinnedKeelSepoliaSimulationTransport(async()=>{count++;return node});assert.equal((await t.request(program))[0].calls[0].status,'0x0');assert.equal(count,1);node.socket.readyState=3;await assert.rejects(t.request(program),e=>e.kind==='rpc-unavailable');assert.equal(count,1);await t.close();});
test('missing or enlarged envelopes are unavailable evidence',()=>{assert.throws(()=>assertKeelSimulationEnvelopes(program,[{calls:[]}]),e=>e.kind==='unsupported-simulation');assert.throws(()=>assertKeelSimulationEnvelopes(program,[{transactions:[{gas:'0xbebc201'}]}]),e=>e.kind==='unsupported-simulation');});
test('all capped probes stop after eight public attempts without sending a program',async()=>{const nodes=[];const t=createPinnedKeelSepoliaSimulationTransport(async()=>{const n=socket({cap:'0x2faf080'});nodes.push(n);return n});await assert.rejects(t.request(program),e=>e.kind==='unsupported-simulation');assert.equal(nodes.length,8);assert.ok(nodes.every(n=>n.closed===1&&n.requests.every(r=>r.method!=='eth_simulateV1'||r.params[0].blockStateCalls[0].calls[0].data==='0x')));await t.close();});
