import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createHash} from 'node:crypto';
import {gzipSync,gunzipSync} from 'node:zlib';
const dist=process.env.KEEL_OFFLINE_SDK_DIST??new URL('../packages/sdk/dist',import.meta.url).pathname;
const {createKeelEmbeddedContainerReader}=await import(`${dist}/embedded-container-reader.js`);
const {validateKeelEmbeddedContainerContext}=await import(`${dist}/embedded-container-context.js`);
const {assertKeelInlineDeliveryProfile}=await import(`${dist}/inline-delivery-profile.js`);
const hash=bytes=>'0x'+createHash('sha256').update(bytes).digest('hex');
const integrity=bytes=>({algorithm:'sha256',digest:hash(bytes),byteLength:bytes.length});
const canonical=value=>({algorithm:value.algorithm,byteLength:value.byteLength,digest:value.digest});
const chainId=11155111,store='0x'+'11'.repeat(20);
const verify=async(bytes,commit,label)=>{assert.equal(bytes.length,commit.byteLength,label+' length');assert.equal(hash(bytes),commit.digest,label+' SHA');return bytes;};
function tableBytes(payloads){const table=Buffer.alloc(64+128*payloads.length);table.writeBigUInt64BE(32n,24);table.writeBigUInt64BE(BigInt(payloads.length),56);payloads.forEach((p,i)=>{const o=64+i*128;table.writeBigUInt64BE(BigInt(p.storedIntegrity.byteLength),o+24);Buffer.from(p.storedIntegrity.digest.slice(2),'hex').copy(table,o+32);Buffer.from(p.objectId.slice(2),'hex').copy(table,o+64);Buffer.from((p.containerId??'0x'+'00'.repeat(32)).slice(2),'hex').copy(table,o+96);});return table;}
function fixture(){const source=Buffer.from('water 🔥 deterministic member bytes');const stored=gzipSync(source);const binding={chainId,compression:'gzip',integrity:integrity(source),objectId:'0x'+'22'.repeat(32),store,storedIntegrity:integrity(stored)};const id=hash(Buffer.from(JSON.stringify({chainId,compression:binding.compression,integrity:canonical(binding.integrity),objectId:binding.objectId,store,storedIntegrity:canonical(binding.storedIntegrity)})));const container={id,...binding};const items=[{id:'test.first',role:'module',mediaType:'text/javascript',aliases:['first'],integrity:integrity(source.subarray(0,7)),onchain:{containerId:id,offset:0},containerBindings:[container]},{id:'test.second',role:'entrypoint',mediaType:'text/html',aliases:['second'],integrity:integrity(source.subarray(7)),onchain:{containerId:id,offset:7}}];const payloads=[{containerId:id,objectId:binding.objectId,storedBase64:stored.toString('base64'),storedIntegrity:binding.storedIntegrity}];return{source,stored,items,payloads,containers:[container]};}
function reader(f,extra={}){return createKeelEmbeddedContainerReader({chainId,store,containers:f.containers,payloads:f.payloads,items:f.items,tableDigest:hash(tableBytes(f.payloads)),verify,decompress:async(codec,bytes)=>codec==='gzip'?gunzipSync(bytes):bytes,...extra});}
test('real gzip Unicode members resolve exactly once; returned Buffer views cannot mutate siblings',async()=>{const f=fixture(),r=reader(f);const [a,b]=await Promise.all(f.items.map(item=>r.resolve(item)));assert.deepEqual(Buffer.concat([a,b]),f.source);a.fill(0);assert.deepEqual(Buffer.from(await r.resolve(f.items[0])),f.source.subarray(0,7));assert.equal(r.snapshot().decodeCount,1);});
test('unused declared binding may omit payload; referenced missing bytes fail closed',async()=>{const f=fixture();const missing=structuredClone(f.containers[0]);missing.objectId='0x'+'33'.repeat(32);const core={...missing};delete core.id;missing.id=hash(Buffer.from(JSON.stringify({chainId,compression:core.compression,integrity:canonical(core.integrity),objectId:core.objectId,store,storedIntegrity:canonical(core.storedIntegrity)})));f.containers.push(missing);f.items[0].containerBindings.push(missing);await reader(f).resolve(f.items[0]);f.items[1].onchain.containerId=missing.id;assert.throws(()=>reader(f),/Missing/);});
test('table-first unused standalone superset is SHA-checked but never decoded',async()=>{const f=fixture();const unused=Buffer.from('unused rollout bytes');f.payloads.push({objectId:'0x'+'44'.repeat(32),storedBase64:unused.toString('base64'),storedIntegrity:integrity(unused)});const r=reader(f);await r.resolve(f.items[0]);assert.equal(r.snapshot().decodeCount,1);const bad=structuredClone(f);bad.payloads[1].storedBase64=Buffer.from('unused rollout bytex').toString('base64');await assert.rejects(reader(bad).resolve(bad.items[0]),/SHA/);const unknown=structuredClone(f);delete unknown.payloads[1].storedIntegrity;assert.throws(()=>reader(f,{payloads:unknown.payloads}),/commitment/);});
test('typed table artifact digest and row order are replayed before any decode',async()=>{const f=fixture();let count=0;const r=reader(f,{tableDigest:'0x'+'ff'.repeat(32),decompress:async()=>{count++;return f.source;}});await assert.rejects(r.resolve(f.items[0]),/packtable artifact SHA/);assert.equal(count,0);});
test('stored, decoded and member SHA each fail closed; repeated failures do not redo decode',async()=>{for(const level of ['stored','decoded','member']){const f=fixture();let count=0;if(level==='stored')f.payloads[0].storedBase64=Buffer.alloc(f.stored.length,1).toString('base64');if(level==='decoded'){const c=f.containers[0];c.integrity.digest='0x'+'aa'.repeat(32);c.id=hash(Buffer.from(JSON.stringify({chainId,compression:c.compression,integrity:canonical(c.integrity),objectId:c.objectId,store,storedIntegrity:canonical(c.storedIntegrity)})));f.payloads[0].containerId=c.id;for(const item of f.items)item.onchain.containerId=c.id;}if(level==='member')f.items[0].integrity.digest='0x'+'aa'.repeat(32);const r=reader(f,{decompress:async(_codec,bytes)=>{count++;return gunzipSync(bytes);}});await assert.rejects(r.resolve(f.items[0]));await assert.rejects(r.resolve(f.items[0]));assert.ok(count<=1);}});
test('exact table/descriptor snapshot, chain, object IDs and ranges reject mutation',async()=>{const f=fixture();assert.throws(()=>reader(f,{containers:[]}),/count/);assert.throws(()=>reader(f,{containers:structuredClone(f.containers).reverse().concat(f.containers)}),/differs/);const r=reader(f);f.items[0].aliases.push('changed');await assert.rejects(r.resolve(f.items[0]),/changed/);const range=fixture();range.items[1].onchain.offset=Number.MAX_SAFE_INTEGER;assert.throws(()=>reader(range),/offset/);const chain=fixture();chain.containers[0].chainId=1;assert.throws(()=>reader(chain),/binding/);});
test('canonical Base64 pad bits, duplicate rows and zero commitments reject before work',()=>{const f=fixture();const bad=structuredClone(f);bad.payloads[0].storedBase64='Zh==';bad.payloads[0].storedIntegrity=integrity(Buffer.from('f'));assert.throws(()=>reader(bad),/pad bits/);const duplicate=structuredClone(f);duplicate.payloads.push(duplicate.payloads[0]);assert.throws(()=>reader(duplicate),/duplicate/);const empty=structuredClone(f);empty.items[0].integrity.byteLength=0;assert.throws(()=>reader(empty),/Empty/);});
test('standalone revision uses exact committed object bytes without changing old table',async()=>{const f=fixture();const source=Buffer.from('standalone new member');const p={objectId:'0x'+'55'.repeat(32),storedBase64:source.toString('base64'),storedIntegrity:integrity(source)};f.payloads.push(p);const item={id:'test.revision',role:'module',mediaType:'text/javascript',aliases:[],integrity:integrity(source),chainId,store,objectId:p.objectId,onchain:{storeKind:'keel-hold',compression:'none',storedIntegrity:p.storedIntegrity}};f.items.push(item);assert.deepEqual(Buffer.from(await reader(f).resolve(item)),source);});
const context=()=>({protocol:'keel-context@1',chainId:String(chainId),collection:'0x'+'66'.repeat(20),tokenId:'1',derivedTokenSeed:'0x'+'77'.repeat(32),seedRegistry:'0x'+'88'.repeat(20),seedSetId:'0x'+'99'.repeat(32),seedSourceCollection:'0x'+'66'.repeat(20),seedSourceTokenId:'1',composerManager:'0x'+'aa'.repeat(20),composerModuleId:'0x'+'bb'.repeat(32),composerAddress:'0x'+'cc'.repeat(20),composerRevision:'1',composerCodeHash:'0x'+'dd'.repeat(32),containerTableHandle:'0x'+'ee'.repeat(32),containerTableRevision:'1',containerTableObjectId:'0x'+'ff'.repeat(32),containerTableDigest:'0x'+'10'.repeat(32),presentationDigest:'0x'+'20'.repeat(32),presentationDigestType:'keccak256:keel.evm-binary-fragment-presentation@1'});
test('exact 20-field typed context preserves token/seed and rejects unknown fields/domain/chain/range',()=>{assert.equal(validateKeelEmbeddedContainerContext(context(),chainId).tokenId,'1');for(const [key,value]of[['extra','no'],['chainId','1'],['tokenId','01'],['seedSourceTokenId','2'],['composerRevision',String(1n<<64n)],['presentationDigestType','keccak256:hybrid']]){const c=context();c[key]=value;assert.throws(()=>validateKeelEmbeddedContainerContext(c,chainId));}});
test('Inline delivery preflight rejects hybrid browser-RPC delivery',()=>{assertKeelInlineDeliveryProfile();assertKeelInlineDeliveryProfile('embedded-assembled');assert.throws(()=>assertKeelInlineDeliveryProfile('onchain-recursive'),/hybrid/);});

const {encodeKeelDenseTransport,decodeKeelDenseTransport}=await import(`${dist}/dense-transport.js`);
for(const profile of ['base90-v1','base91-v1']){
 test(`${profile} uses unchanged bindings and verifies each byte before decompressing`,async()=>{
  const f=fixture();f.payloads=f.payloads.map(({storedBase64,...p})=>({...p,storedDense:encodeKeelDenseTransport(Buffer.from(storedBase64,'base64'),profile)}));
  const extra={transportProfile:profile,decodeTransport:(text,byteLength)=>decodeKeelDenseTransport(text,{profile,byteLength})};
  const r=reader(f,extra);assert.deepEqual(Buffer.concat(await Promise.all(f.items.map(item=>r.resolve(item)))),f.source);assert.equal(r.snapshot().decodeCount,1);
  assert.throws(()=>reader(f),/encoding/);assert.throws(()=>reader(f,{transportProfile:profile}),/decoder/);
  const legacy=fixture();assert.throws(()=>reader(legacy,extra),/encoding/);
  const bad=structuredClone(f);const wrong=f.stored.slice();wrong[5]^=1;bad.payloads[0].storedDense=encodeKeelDenseTransport(wrong,profile);
  let calls=0;await assert.rejects(reader(bad,{...extra,decompress:async()=>{calls++;return f.source;}}).resolve(bad.items[0]),/SHA/);assert.equal(calls,0);
 });
}
