import test from 'node:test';import assert from 'node:assert/strict';
import {chunkDirectImageObject,reconstructDirectImageObject,directImageRecipe,parseDirectImageSettings} from '@keel/sdk/direct-image';
import {newLayeredArt} from '@keel/sdk/layered-art';
import {mkdtemp,readFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {exportDirectImagePackage} from '../src/direct-image-export.mjs';
const binary=Uint8Array.from({length:512},(_,i)=>i%256);
test('raw chunks deduplicate and reconstruct without base64, with tamper rejection',async()=>{for(const type of ['image/png','image/svg+xml','image/gif','image/webp']){const {object,chunks}=await chunkDirectImageObject(binary,type,256);assert.equal(chunks.length,1);assert.equal(object.chunks.length,2);assert.equal(JSON.stringify(object).includes('base64'),false);assert.deepEqual(await reconstructDirectImageObject(object,async id=>chunks.find(c=>c.digest===id).bytes),binary);await assert.rejects(()=>reconstructDirectImageObject(object,async()=>new Uint8Array(256)),/integrity/);await assert.rejects(()=>reconstructDirectImageObject({...object,byteLength:513},async()=>binary),/lengths/);}await assert.rejects(()=>chunkDirectImageObject(binary,'image/png',0),/budget/);});
test('direct format selection does not change the HTML renderer and preserves complete rules',()=>{const art=newLayeredArt();const original=JSON.stringify(art);for(const settings of [{format:'apng',motion:'still'},{format:'apng',motion:'animation'},{format:'png',motion:'still'},{format:'svg',motion:'still'},{format:'gif',motion:'animation'},{format:'webp',motion:'animation'},{format:'webp',motion:'still'}]){const recipe=directImageRecipe(art,settings);assert.deepEqual(recipe.output,settings);assert.deepEqual(recipe.manifest,art);assert.equal(recipe.publicationReady,false);assert.equal(JSON.stringify(art),original);}assert.throws(()=>parseDirectImageSettings({format:'png',motion:'animation'}),/Choose/);assert.throws(()=>parseDirectImageSettings({format:'gif',motion:'still'}),/Choose/);});
test('direct preparation writes only raw chunk files and reconstructible recipe',async()=>{const folder=await mkdtemp(path.join(os.tmpdir(),'keel-direct-'));try{const art=newLayeredArt();const project={id:'test',layered:art,directImage:{format:'svg',motion:'still'},objectIds:[],contractIds:[]};const store={read:()=>({state:{objects:[]}})};const result=await exportDirectImagePackage(store,project,folder);assert.equal(result.plan.storageEncoding,'raw-bytes');const recipeObject=result.plan.resources.find(o=>o.role==='recipe');const bytes=await reconstructDirectImageObject(recipeObject,async id=>new Uint8Array(await readFile(path.join(result.directory,'chunks',id))));const recipe=JSON.parse(new TextDecoder().decode(bytes));assert.deepEqual(recipe.manifest,art);assert.equal(recipe.publicationReady,false);const privateProject={...project,layered:{...art,reveal:{mode:'creator',encrypted:true,revealAt:0}}};await assert.rejects(()=>exportDirectImagePackage(store,privateProject,folder),/private/);}finally{await rm(folder,{recursive:true,force:true});}});
