const {app,BrowserWindow}=require('electron');
const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const assert=require('node:assert/strict');
process.env.KEEL_DESKTOP_TEST_HIDDEN='1';process.env.KEEL_DESKTOP_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'keel-agent-native-'));
BrowserWindow.prototype.show=function(){};BrowserWindow.prototype.focus=function(){};
app.on('browser-window-created',(_event,window)=>{window.hide();window.webContents.setBackgroundThrottling(false);});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(check,label){for(let i=0;i<150;i++){if(await check())return;await sleep(50);}throw Error(label);}
void(async()=>{
  require('../artifacts/agent-native/main.cjs');
  await until(()=>BrowserWindow.getAllWindows().length,'Window missing');
  const window=BrowserWindow.getAllWindows()[0];const errors=[];window.webContents.on('console-message',event=>{if(event.level==='error'&&!event.message.includes('Electron Security Warning'))errors.push(event.message);});
  const run=source=>window.webContents.executeJavaScript(source,true);const request=(name,input)=>run(`window.keel.request(${JSON.stringify(name)},${JSON.stringify(input)})`);
  const text=()=>run('document.body.innerText');
  const click=async label=>{await until(async()=>await run(`[...document.querySelectorAll('button')].some(e=>e.textContent.trim()===${JSON.stringify(label)}&&!e.disabled)`),`Button not ready: ${label}`);return run(`(()=>{const button=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===${JSON.stringify(label)});if(!button)throw Error('Button missing: '+${JSON.stringify(label)});button.click();})()`);};
  const fill=(selector,value,type='HTMLInputElement')=>run(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Input missing');Object.getOwnPropertyDescriptor(${type}.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await until(async()=>(await text()).includes('Make it yours.'),'Home missing');
  await run(`[...document.querySelectorAll('.nav-item')].find(e=>e.textContent.includes('Chats')).click()`);
  await until(async()=>await run('!!document.querySelector(".agent-workspace")'),'Chats missing');
  await click('Start a chat ↗');
  await until(async()=>await run('!!document.querySelector(".chat-composer textarea")'),'Composer missing');
  await fill('.chat-composer textarea','Create a local artwork','HTMLTextAreaElement');await run('document.querySelector(".chat-composer").requestSubmit()');
  await until(async()=>(await request('workspace')).state.projects.length===1,'Agent did not create artwork');
  await until(async()=>(await text()).includes('Created Native Sketch'),'Reply missing');
  const originalChat=(await request('agentChats',{})).chats[0];
  window.setSize(1440,960);await sleep(150);
  fs.writeFileSync(path.resolve(__dirname,'../artifacts/agents-desktop.png'),(await window.webContents.capturePage()).toPNG());
  assert.equal(await run('document.documentElement.scrollWidth<=innerWidth'),true,'Desktop overflow');
  await click('Open in editor');await until(async()=>(await text()).includes('All projects'),'Agent navigation failed');
  const project=(await request('workspace')).state.projects[0];assert.equal(project.presentation.shell,'canonical');
  await until(async()=>window.webContents.mainFrame.frames.length>0,'Preview missing');
  assert.equal(await window.webContents.mainFrame.frames[0].executeJavaScript('typeof window.keel'),'undefined');
  await click('New chat');await until(async()=>(await request('agentChats',{})).total===2,'Project chat missing');await until(async()=>await run('document.querySelector(".chat-heading h2")?.textContent==="New chat" && !!document.querySelector(".chat-composer textarea")'),'Project chat form missing');
  await fill('.chat-composer textarea','Please edit metadata','HTMLTextAreaElement');await run('document.querySelector(".chat-composer").requestSubmit()');
  await until(async()=>(await text()).includes('Apply to project'),'Edit review missing');
  await click('Apply to project');await until(async()=>(await request('workspace')).state.projects[0].metadata.description==='A violet garden of light.','Edit failed');await until(async()=>await run('document.querySelector(".agent-action.project-edit .badge")?.textContent==="applied"'),'Edit review did not settle');
  await click('Save memory');await until(async()=>(await request('workspace')).state.memories.length===1,'Memory failed');
  const note=(await request('workspace')).state.memories[0];assert.equal(note.projectId,project.id);
  await fill('.chat-composer textarea','Please show metadata','HTMLTextAreaElement');await run('document.querySelector(".chat-composer").requestSubmit()');
  await until(async()=>await run('document.querySelector(".tabs .selected")?.textContent==="Metadata"'),'Agent did not switch project tab');
  assert.equal((await request('workspace')).state.projects[0].metadata.description,'A violet garden of light.','Stale editor overwrote agent edit');
  await click('All chats ↗');
  await until(async()=>await run('!!document.querySelector(".chat-list")'),'Full chat view missing');
  await click('•••');
  await until(async()=>await run('!!document.querySelector(".chat-settings")'),'Chat settings missing');
  await run(`document.querySelector('input[aria-label="Use saved work in this chat"]').click()`);
  await until(async()=>(await text()).includes('Saved work is off for this chat'),'Context setting did not turn off');
  await click('Inspect context');await until(async()=>await run('!!document.querySelector(".composer-context-detail")'),'Context inspector missing');
  assert.equal(await run('document.querySelector(".composer-context-detail").textContent.includes("Visual direction")'),false,'Disabled context included saved memory');
  await fill('.chat-composer textarea','Search my memory','HTMLTextAreaElement');await run('document.querySelector(".chat-composer").requestSubmit()');
  await until(async()=>(await text()).includes('Use saved work above the message box to search your memories.'),'Restricted chat guidance missing');
  await click('Use saved work');await until(async()=>!(await text()).includes('Saved work is off for this chat'),'Context did not re-enable');
  assert.equal(await run('!!document.querySelector(".composer-context-detail")'),false,'Old context inspection remained visible');
  await fill('.chat-composer textarea','Search my memory','HTMLTextAreaElement');await run('document.querySelector(".chat-composer").requestSubmit()');
  await until(async()=>(await text()).includes('Found your saved memory: Use violet and cream in this piece.'),'Memory lookup did not recover');
  assert.equal(await run('[...document.querySelectorAll(".agent-tool-log p")].some(e=>e.textContent.includes("failed"))'),false,'Permission failure loop returned');
  await click('Archive chat');await until(async()=>(await text()).includes('This chat is archived'),'Archive failed');await click('Restore & continue');
  await until(async()=>!(await text()).includes('This chat is archived'),'Restore failed');
  await fill('.chat-composer textarea','slow request','HTMLTextAreaElement');await run('document.querySelector(".chat-composer").requestSubmit()');
  await until(async()=>(await text()).includes('Stop reply'),'Stop missing');await click('Stop reply');
  await until(async()=>(await text()).includes('Reply stopped'),'Cancellation missing');
  const draft='Keep this unsent thought';await fill('.chat-composer textarea',draft,'HTMLTextAreaElement');await sleep(650);
  await run(`[...document.querySelectorAll('.chat-list-item')].find(e=>e.textContent.includes('Create a local artwork')).click()`);await sleep(150);await run(`[...document.querySelectorAll('.chat-list-item')].find(e=>e.textContent.includes('Please edit metadata')).click()`);
  await until(async()=>await run(`document.querySelector('.chat-composer textarea')?.value===${JSON.stringify(draft)}`),'Draft did not restore');
  if(await run('!!document.querySelector(".chat-settings")'))await click('•••');
  window.setMinimumSize(600,500);window.setSize(980,760);await sleep(150);
  assert.equal(await run('document.documentElement.scrollWidth<=innerWidth'),true,'Small window overflow');
  assert.equal(await run('document.querySelector(".chat-list-heading button").getBoundingClientRect().right<=document.querySelector(".chat-list").getBoundingClientRect().right'),true,'New chat button clipped');
  fs.writeFileSync(path.resolve(__dirname,'../artifacts/agents-small.png'),(await window.webContents.capturePage()).toPNG());
  assert.equal((await request('agentHistory',{id:originalChat.id})).runs.length,1,'Chat histories mixed');
  assert.deepEqual(errors,[],'Renderer errors');
  console.log('PASS native agent chats, creation, canonical preview, edit review, memory access recovery, navigation, archive/restore, cancellation, drafts, isolation and responsive layout.');app.exit(0);
})().catch(async error=>{console.error(error);const window=BrowserWindow.getAllWindows()[0];if(window){console.error(await window.webContents.executeJavaScript('document.body.innerText'));fs.writeFileSync(path.resolve(__dirname,'../artifacts/agents-failure.png'),(await window.webContents.capturePage()).toPNG());}app.exit(1);});
