const { app, BrowserWindow, session } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
process.env.KEEL_DESKTOP_TEST_HIDDEN = '1';
BrowserWindow.prototype.show = function() {};
BrowserWindow.prototype.focus = function() {};
app.on('browser-window-created', (_event,window) => { window.hide(); window.webContents.setBackgroundThrottling(false); });
const reportPath = path.resolve(__dirname, '../artifacts/smoke-report.json');
const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
process.env.KEEL_DESKTOP_DATA_DIR = report.workspaceDir;
require('../dist/main.cjs');
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function until(fn) { for (let i=0;i<100;i++) { if (await fn()) return; await wait(100); } throw new Error('Restart check timed out.'); }
void (async () => {
  await until(() => BrowserWindow.getAllWindows().length > 0);
  const editor = BrowserWindow.getAllWindows()[0];
  await until(async () => { try { return await editor.webContents.executeJavaScript('!!window.keel && document.body.innerText.includes("Make it yours.")'); } catch { return false; } });
  const result = await editor.webContents.executeJavaScript('window.keel.request("walletExtensions")');
  const record = result.installed[0];
  assert.equal(record.loaded, true); assert.equal(record.extensionId, report.extensionId);
  assert.equal(record.installationId, report.installationId);
  assert.equal(session.defaultSession.extensions.getAllExtensions().length, 0);
  await editor.webContents.executeJavaScript(`window.keel.request('openWalletExtension', ${JSON.stringify(record.installationId)})`);
  const popup = BrowserWindow.getAllWindows().find((window) => window !== editor);
  assert.equal(await popup.webContents.executeJavaScript('localStorage.getItem("fixture-continuity")'), 'retained-no-keys');
  const workspace = await editor.webContents.executeJavaScript('window.keel.request("workspace")');
  assert.equal(workspace.state.projects[0].title, 'Signal Garden');
  assert.equal(workspace.state.contracts[0].name, 'Signal Garden Controls');
  assert.equal(workspace.state.projects.length, 2);
  const networks = await editor.webContents.executeJavaScript('window.keel.request("networkProfiles")');
  assert.equal(networks.length, 1); assert.equal(networks[0].id, workspace.state.projects[0].targetNetworkId);
  assert.equal(networks[0].rpcUrl, undefined);
  assert.equal(workspace.state.projects[0].presentation.shell, 'canonical');
  assert.ok(workspace.state.projects[0].presentation.entryObjectId);
  assert.ok(workspace.state.objects.find((object) => object.name === 'large-test.gif')); 
  assert.equal(workspace.state.moduleSelections[0].name, 'Signal palette');
  assert.equal(workspace.state.projects[0].metadata.name, 'Signal Garden');
  assert.equal(workspace.state.projects[0].metadata.attributes[0].value, 2027);
  assert.equal(workspace.state.projects[0].metadata.properties.customFixture, true);
  const checks = await editor.webContents.executeJavaScript(`window.keel.request('projectChecks', ${JSON.stringify(workspace.state.projects[0].id)})`);
  assert.ok(checks.length >= 2); assert.ok(checks.some((check) => check.onchain?.block === '42'));
  report.evidence.push('metadata-custom-fields-and-check-history-survive-native-restart');
  report.evidence.push('native-process-restart-restores-project-contract-extension-id-and-profile-storage');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));
  console.log(JSON.stringify({ status: 'passed', restart: report.evidence.at(-1) })); app.exit(0);
})().catch((error) => { console.error(error); app.exit(1); });
