// Native Electron checks use local RPC fixtures and a keyless extension only.
const { app, BrowserWindow, dialog, session } = require('electron');
process.env.KEEL_DESKTOP_TEST_HIDDEN = '1';
BrowserWindow.prototype.show = function() {};
BrowserWindow.prototype.focus = function() {};
app.on('browser-window-created', (_event,window) => { window.hide(); window.webContents.setBackgroundThrottling(false); });
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const syncFs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { createServer } = require('node:http');
const { randomBytes } = require('node:crypto');

let screenshotDir;
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function until(check, message) { for (let attempt = 0; attempt < 100; attempt++) { if (await check()) return; await wait(100); } throw new Error(message); }
void (async () => {
  const dir = syncFs.mkdtempSync(path.join(os.tmpdir(), 'keel-electron-smoke-'));
  process.env.KEEL_DESKTOP_DATA_DIR = dir;
  screenshotDir = path.resolve(__dirname, '../artifacts');
  syncFs.mkdirSync(screenshotDir, { recursive: true });
  const abi = [{ type: 'function', name: 'owner', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] }, { type: 'function', name: 'setValue', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] }];
  const fixture = path.join(dir, 'custom-abi.json');
  syncFs.writeFileSync(fixture, JSON.stringify(abi));
  dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [fixture] });
  require('../dist/main.cjs');
  await until(() => BrowserWindow.getAllWindows().length > 0, 'Editor window did not start.');
  const window = BrowserWindow.getAllWindows()[0];
  window.webContents.setBackgroundThrottling(false);
  const errors = [];
  window.webContents.on('console-message', (event) => { if (event.level === 'error' && !event.message.includes('Electron Security Warning')) errors.push(event.message); });
  const run = async (source) => { try { return await window.webContents.executeJavaScript(source, true); } catch (cause) { throw new Error(`Native UI script failed: ${source.slice(0, 280)}`, { cause }); } };
  const text = () => run('document.body.innerText');
  await until(async () => (await text()).includes('Make it yours.'), 'Editor failed to render the project home.');
  const prefs = window.webContents.getLastWebPreferences();
  assert.equal(prefs.nodeIntegration, false); assert.equal(prefs.contextIsolation, true); assert.equal(prefs.sandbox, true);
  const fill = (selector, value) => run(`(() => { const e=document.querySelector(${JSON.stringify(selector)}); if(!e)throw new Error('Missing input'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)}); e.dispatchEvent(new Event('input',{bubbles:true})); })()`);
  const clickText = async (label) => { await until(async () => await run('document.querySelector(".main-panel").getAttribute("aria-busy")') === 'false', `Previous action did not settle before ${label}.`); await until(async()=>await run(`[...document.querySelectorAll('button')].some(e=>e.textContent.trim()===${JSON.stringify(label)}&&!e.disabled)`),`Button not ready: ${label}`); return run(`(() => { const e=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===${JSON.stringify(label)}); if(!e)throw new Error('Missing button: '+${JSON.stringify(label)}); e.click(); })()`); };
  await fs.writeFile(path.join(screenshotDir, 'projects-desktop.png'), (await window.webContents.capturePage()).toPNG());
  await run('document.querySelector(".blank-project").open=true');
  await fill('input[name=title]', 'Signal Garden');
  await run('document.querySelector(".new-project").requestSubmit()');
  await until(async () => (await text()).includes('All projects'), 'Creating a project did not open the editor.');
  await until(async () => window.webContents.mainFrame.frames.length > 0, 'Preview frame did not load.');
  const frame = window.webContents.mainFrame.frames[0];
  await until(async () => { try { return await frame.executeJavaScript('!!document.querySelector("#verify-seal") && document.body.dataset.verification === "verified"'); } catch { return false; } }, 'Canonical verification shell did not mount by default.');
  assert.equal(await frame.executeJavaScript('typeof window.keel'), 'undefined');
  assert.equal(await frame.executeJavaScript('typeof require'), 'undefined');
  assert.equal(await frame.executeJavaScript('typeof process'), 'undefined');
  assert.equal(await frame.executeJavaScript('fetch("https://example.com").then(()=>"allowed",()=>"blocked")'), 'blocked');
  assert.equal(await run('!!document.querySelector(".code-editor")'), false, 'Code should be optional in the artist preview.');
  await clickText('Show code');
  const modulePath = path.join(dir, 'sketch.js');
  await fs.writeFile(modulePath, 'window.modulePreviewReady = "local-module-loaded";');
  dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [modulePath] });
  await clickText('+ Import file');
  await until(async () => (await text()).includes('sketch.js'), 'Local script import failed.');
  await clickText('index.html');
  await run(`(() => { const e=document.querySelector('.code-editor'); Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(e, '<!doctype html><html><body style="background:#0c0d10;color:#a5afff;display:grid;place-items:center;height:95vh;font:32px Georgia"><main>Signal Garden<br><small style="font:12px system-ui;color:#9aa0ab">Local creator preview</small></main><script type="module" src="./sketch.js"></script></body></html>'); e.dispatchEvent(new Event('input',{bubbles:true})); })()`);
  await until(async () => (await text()).includes('Unsaved changes'), 'Source edit was not captured.');
  let closePrompt = false;
  dialog.showMessageBoxSync = () => { closePrompt = true; return 0; };
  window.close(); await until(() => closePrompt, 'Closing a dirty editor did not protect unsaved work.');
  assert.equal(window.isDestroyed(), false);
  const beforeSaveRace = await run('window.keel.request("workspace")');
  await run(`(() => {
    const editor = document.querySelector('.code-editor');
    const save = [...document.querySelectorAll('button')].find(button => button.textContent.trim() === 'Save & preview');
    save.click(); save.click();
    Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(editor, editor.value + '\\n<!-- Edited while save was pending -->');
    editor.dispatchEvent(new Event('input', { bubbles: true }));
  })()`);
  await until(async () => (await run('document.querySelector(".main-panel").getAttribute("aria-busy")')) === 'false', 'Pending save did not settle.');
  const duringSave = await run('window.keel.request("workspace")');
  assert.equal(duringSave.revision, beforeSaveRace.revision + 1, 'Duplicate save clicks wrote more than once.');
  assert.equal(duringSave.state.projects[0].files[0].content.includes('Edited while save was pending'), false);
  assert.equal(await run('document.querySelector(".code-editor").value.includes("Edited while save was pending")'), true);
  assert.ok((await text()).includes('Unsaved changes'), 'Edits made during a save were lost or marked saved.');
  await clickText('Save & preview');
  await until(async () => !(await text()).includes('Unsaved changes'), 'Saving the source failed.');
  await until(async () => { try { return await window.webContents.mainFrame.frames[0].frames[0].executeJavaScript('window.modulePreviewReady === "local-module-loaded"'); } catch { return false; } }, 'Project ES module did not run in the sandbox.');
  await clickText('Viewing');
  await run('document.querySelectorAll(".shell-choice-grid button")[1].click()');
  await until(async () => (await run('window.keel.request("workspace")')).state.projects[0].presentation.shell === 'none', 'Direct display selection did not persist.');
  await clickText('Preview');
  await until(async () => { try { return await window.webContents.mainFrame.frames[0].executeJavaScript('window.modulePreviewReady === "local-module-loaded"'); } catch { return false; } }, 'Direct source preview did not run.');
  const moduleFrame = window.webContents.mainFrame.frames[0];
  assert.equal(await moduleFrame.executeJavaScript('fetch("./sketch.js").then(r=>r.ok)'), true);
  assert.equal(await moduleFrame.executeJavaScript('fetch("keel-preview://00000000-0000-4000-8000-000000000000/index.html").then(()=>"allowed",()=>"blocked")'), 'blocked');
  await clickText('Viewing'); await run('document.querySelectorAll(".shell-choice-grid button")[0].click()'); await clickText('Preview');
  await until(async () => { try { return await window.webContents.mainFrame.frames[0].executeJavaScript('document.body.dataset.verification === "verified"'); } catch { return false; } }, 'Canonical shell did not restore.');
  await fs.writeFile(path.join(screenshotDir, 'editor-desktop.png'), (await window.webContents.capturePage()).toPNG());
  await run(`[...document.querySelectorAll('.nav-item')].find(e=>e.textContent.includes('Contracts')).click()`);
  await until(async () => (await text()).includes('Track a contract'), 'Contract workspace did not open.');
  await clickText('+ Track a contract');
  await fill('input[name=name]', 'Signal Garden Controls');
  await fill('input[name=address]', '0x1111111111111111111111111111111111111111');
  await fill('input[name=chainId]', '11155111');
  dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [fixture] });
  await clickText('Import ABI or artifact');
  await until(async () => (await text()).includes('2 ABI entries'), 'ABI import did not generate entries.');
  await run('document.querySelector(".contract-form").requestSubmit()');
  await until(async () => (await text()).includes('CONTRACT INSPECTOR'), 'Tracked contract did not open in inspector.');
  assert.ok((await text()).includes('owner()'));
  await run(`[...document.querySelectorAll('.contract-panel .tabs button')].find(e=>e.textContent.includes('Write review')).click()`);
  await until(async () => (await text()).includes('setValue(uint256)'), 'Write method was not generated.');
  await run('document.querySelector(".method-list button").click()');
  await fill('.control-form input', '9007199254740993');
  await clickText('Prepare unsigned call');
  await until(async () => (await text()).includes('UNSIGNED CALL REVIEW'), 'Unsigned write review was not generated.');
  assert.ok((await text()).includes('review-only'));
  assert.ok((await text()).includes('not-performed'));
  const nativeLayout = await run('({ width:innerWidth, scroll:document.documentElement.scrollWidth, mainWidth:document.querySelector(".main-panel").clientWidth, mainScroll:document.querySelector(".main-panel").scrollWidth })');
  assert.ok(nativeLayout.scroll <= nativeLayout.width); assert.ok(nativeLayout.mainScroll <= nativeLayout.mainWidth);
  await fs.writeFile(path.join(screenshotDir, 'contracts-desktop.png'), (await window.webContents.capturePage()).toPNG());
  window.setSize(1000, 800);
  await wait(300);
  assert.equal(await run('document.documentElement.scrollWidth <= innerWidth'), true);
  await fs.writeFile(path.join(screenshotDir, 'contracts-compact.png'), (await window.webContents.capturePage()).toPNG());
  const snapshot = await run('window.keel.request("workspace")');
  assert.equal(snapshot.state.projects[0].title, 'Signal Garden');
  assert.equal(snapshot.state.contracts[0].name, 'Signal Garden Controls');
  assert.equal(snapshot.state.contracts[0].authority, 'unverified');
  assert.equal(snapshot.state.contracts[0].abi.length, 2);
  let publishedMetadata = { name: 'Signal Garden', description: 'Fixture metadata' };
  const encodeMetadata = () => require('viem').encodeAbiParameters([{ type: 'string' }], ['data:application/json;base64,' + Buffer.from(JSON.stringify(publishedMetadata)).toString('base64')]);
  const observedRpcMethods = []; let fixtureGasPrice = '0x77359400';
  let holdRpc; let releaseRpc;
  const fixtureStudio = createServer((request, response) => {
    response.setHeader('content-type', 'application/json');
    if (request.method === 'POST') {
      let body = ''; request.on('data', (chunk) => { body += chunk; }); request.on('end', () => {
        const rpc = JSON.parse(body); observedRpcMethods.push(rpc.method);
        const result = rpc.method === 'eth_chainId' ? '0xaa36a7' : rpc.method === 'eth_blockNumber' ? '0x2a' : rpc.method === 'eth_getBlockByNumber' ? { number: '0x2a', gasLimit: '0x2aea540', timestamp: `0x${Math.floor(Date.now()/1000).toString(16)}`, baseFeePerGas: '0x3b9aca00' } : rpc.method === 'eth_gasPrice' ? fixtureGasPrice : rpc.method === 'eth_maxPriorityFeePerGas' ? '0x3b9aca00' : rpc.method === 'eth_estimateGas' ? '0x5208' : rpc.method === 'eth_getCode' ? '0x6000' : rpc.method === 'eth_getStorageAt' ? '0x'+'0'.repeat(64) : rpc.method === 'eth_call' ? (rpc.params[0].data.startsWith('0xc87b56dd') ? encodeMetadata() : rpc.params[0].data === '0x8da5cb5b' ? '0x'+'0'.repeat(24)+'2'.repeat(40) : '0x') : null;
        const send = () => response.end(JSON.stringify({ jsonrpc: '2.0', id: rpc.id, result }));
        if (holdRpc === rpc.method) { holdRpc = undefined; releaseRpc = send; } else send();
      }); return;
    }
    if (request.url.startsWith('/.well-known/')) response.end(JSON.stringify({ schema: 'keel-studio-capabilities@2', generatedAt: '2026-09-07T00:00:00.000Z', chainId: 11155111, staging: { endpoint: '/api/agent/staging', transport: 'multipart-form-data', authentication: 'bearer', maxSourceBytes: 1000000, maximumRetentionSeconds: 3600, resumable: false, oneUseHandoff: false }, wallet: { signing: false, submission: false }, publication: { readiness: 'requires-project-verification', canonicalShellRequired: true } }));
    else if (request.url.startsWith('/api/library')) response.end(JSON.stringify({ assets: [{ name: 'Signal palette', chainId: 11155111, assetId: '0x123', license: 'Fixture test license' }] }));
    else response.end(JSON.stringify({ modules: [{ name: 'Signal helpers', version: '1.0.0' }] }));
  });
  await new Promise((resolve) => fixtureStudio.listen(0, '127.0.0.1', resolve));
  const fixtureOrigin = `http://127.0.0.1:${fixtureStudio.address().port}`;
  await fill('.contract-panel input[type=url]', fixtureOrigin);
  await fill('.simulation input', '0x2222222222222222222222222222222222222222');
  await clickText('Simulate unsigned call');
  await until(async () => (await text()).includes('succeeded-at-observed-block'), 'Unsigned simulation did not complete.');
  await fill('.control-form input', '2');
  assert.equal((await text()).includes('succeeded-at-observed-block'), false, 'An edited argument retained stale simulation evidence.');
  holdRpc = 'eth_call'; releaseRpc = undefined;
  await clickText('Simulate unsigned call');
  await until(() => !!releaseRpc, 'Delayed contract simulation did not start.');
  await fill('.control-form input', '3');
  releaseRpc();
  await until(async () => (await run('document.querySelector(".main-panel").getAttribute("aria-busy")')) === 'false', 'Contract request did not settle.');
  assert.equal((await text()).includes('succeeded-at-observed-block'), false, 'A late simulation overwrote edited arguments.');
  await run(`document.querySelectorAll('.contract-panel .tabs button')[0].click()`);
  await until(async () => (await text()).includes('owner()'), 'Read controls missing.');
  await run('document.querySelector(".method-list button").click()');
  await clickText('Read from this chain');
  await until(async () => (await text()).includes('0x2222222222222222222222222222222222222222'), 'Pinned RPC read failed.');
  assert.ok(observedRpcMethods.includes('eth_call'));
  assert.ok(observedRpcMethods.every((method) => ['eth_chainId','eth_blockNumber','eth_getCode','eth_getStorageAt','eth_call'].includes(method)));
  await run(`[...document.querySelectorAll('.nav-item')].find(e=>e.textContent.includes('Setup')).click()`);
  await until(async () => (await text()).includes('Connect your Studio.'), 'Connections page failed.');
  await fill('input[aria-label="Studio URL"]', fixtureOrigin);
  await clickText('Check & connect Studio');
  await until(async () => (await text()).includes('Studio connected'), 'Capability negotiation failed.');
  const backupPath = path.join(dir, 'workspace.keel.json');
  dialog.showSaveDialog = async () => ({ canceled: false, filePath: backupPath });
  await clickText('Export workspace');
  await until(async () => (await text()).includes('Saved workspace.keel.json'), 'Native backup export failed.');
  dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [backupPath] });
  const discardedReview = await run('window.keel.request("reviewWorkspaceImport")');
  await run(`window.keel.request('discardWorkspaceImport', ${JSON.stringify(discardedReview.token)})`);
  const discardedError = await run(`window.keel.request('importWorkspace', ${JSON.stringify({ token: discardedReview.token, digest: discardedReview.digest, revision: snapshot.revision })}).then(()=>'unexpected import', error=>error.message)`);
  assert.match(discardedError, /Review this import again/);
  await clickText('Import workspace');
  await until(async () => (await text()).includes('Add imported workspace'), 'Backup import review did not appear.');
  await clickText('Add imported workspace');
  await until(async () => (await text()).includes('Workspace imported as additional projects.'), 'Backup merge failed.');
  await run(`[...document.querySelectorAll('.nav-item')].find(e=>e.textContent.includes('Library')).click()`);
  await until(async () => (await text()).includes('Find a reusable module.'), 'Module search missing.');
  await fill('input[aria-label="Library query"]', 'signal');
  await clickText('Search Studio library');
  await until(async () => (await text()).includes('Signal palette'), 'Shared MCP library search failed.');
  await run(`(() => {const element=document.querySelector('select[aria-label="Save reference to project"]'); element.value=${JSON.stringify(snapshot.state.projects[0].id)}; element.dispatchEvent(new Event('change',{bubbles:true})); })()`);
  await clickText('Save reference to project');
  await until(async () => (await run('window.keel.request("workspace")')).state.moduleSelections.length === 1, 'Module reference was not persisted.');
  const backedUp = await run('window.keel.request("workspace")');
  assert.equal(backedUp.state.projects.length, 2); assert.equal(backedUp.state.contracts.length, 1);
  await fs.writeFile(path.join(screenshotDir, 'modules-desktop.png'), (await window.webContents.capturePage()).toPNG());
  await run(`[...document.querySelectorAll('.nav-item')].find(e=>e.textContent.includes('My work')).click()`);
  await until(async () => (await text()).includes('All projects') || (await text()).includes('Make it yours.'), 'Project workspace did not reopen.');
  if ((await text()).includes('Make it yours.')) await run('document.querySelector(".project-card").click()');
  await until(async () => (await text()).includes('+ Import file'), 'Project editor did not reopen.');
  const gifPath = path.join(dir, 'large-test.gif');
  const gifBytes = Buffer.concat([Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7', 'base64'), randomBytes(2_000_000)]);
  await fs.writeFile(gifPath, gifBytes);
  dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [gifPath] });
  await clickText('+ Import file');
  await until(async () => (await text()).includes('Displaying large-test.gif'), 'General importer did not route GIF to an asset.');
  await until(async () => { try { return await window.webContents.mainFrame.frames[0].executeJavaScript('document.body.dataset.verification === "verified"'); } catch { return false; } }, 'Large GIF did not verify in the canonical shell.');
  assert.equal(await window.webContents.mainFrame.frames[0].frames[0].executeJavaScript('document.querySelector("img").naturalWidth'), 1);
  assert.equal(await run('document.querySelector(".project-heading .badge").textContent'), 'Saved locally');
  await clickText('Viewing');
  await until(async () => (await text()).includes('View the complete size breakdown'), 'Size breakdown did not load.');
  await run('[...document.querySelectorAll("summary")].find(e=>e.textContent==="View the complete size breakdown").click()');
  await until(async () => (await text()).includes('RPC reconstruction') && (await text()).includes('2.00 MB'), 'Measured GIF delivery route missing.');
  assert.ok((await text()).includes('1.75 MB'));
  await run('document.querySelector(".contract-retrieval").open=true');
  assert.ok((await text()).includes('haulObject')); assert.ok((await text()).includes('readSlug'));
  await run('document.querySelector(".network-disclosure").open=true');
  await fill('.network-form input[name=label]', 'Fixture test network');
  await fill('.network-form input[name=rpcUrl]', fixtureOrigin);
  await fill('.network-form input[name=chainId]', '11155111');
  await clickText('Check & use network');
  await until(async () => (await text()).includes('Live RPC facts') && (await text()).includes('2 Gwei'), 'Live target network and fees did not connect.');
  assert.ok((await text()).includes('45,000,000'));
  assert.equal(await run('document.querySelector(".project-heading .badge").textContent'), 'Saved locally');
  fixtureGasPrice = '0xee6b2800'; await clickText('Refresh network');
  await until(async () => (await text()).includes('4 Gwei'), 'Network fee refresh used a stale quote.');
  await run('document.querySelector(".network-estimate").open=true');
  await fill('.network-estimate input[name=to]', '0x1111111111111111111111111111111111111111');
  await clickText('Estimate on selected network');
  await until(async () => (await text()).includes('21,000 gas'), 'Exact prepared-call gas estimate did not render.');
  assert.ok((await text()).includes('84,000,000,000,000 native base units'));
  await fill('.network-estimate input[name=value]', '0x1');
  assert.equal(await run('!!document.querySelector(".network-estimate .result")'), false);
  holdRpc = 'eth_estimateGas'; releaseRpc = undefined;
  await clickText('Estimate on selected network');
  await until(() => !!releaseRpc, 'Delayed fee estimate did not start.');
  await fill('.network-estimate input[name=value]', '0x2');
  releaseRpc();
  await until(async () => (await run('document.querySelector(".main-panel").getAttribute("aria-busy")')) === 'false', 'Estimate request did not settle.');
  assert.equal(await run('!!document.querySelector(".network-estimate .result")'), false, 'A late gas estimate overwrote changed call values.');
  await run('document.querySelector(".network-estimate").open=false');
  assert.equal(await run('document.documentElement.scrollWidth <= innerWidth && document.querySelector(".main-panel").scrollWidth <= document.querySelector(".main-panel").clientWidth'), true);
  await fs.writeFile(path.join(screenshotDir, 'shell-and-delivery-desktop.png'), (await window.webContents.capturePage()).toPNG());
  await run('document.querySelectorAll(".shell-choice-grid button")[1].click()');
  await until(async () => (await run('window.keel.request("workspace")')).state.projects[0].presentation.shell === 'none', 'Asset shell bypass did not persist.');
  await clickText('Preview');
  await until(async () => { try { return await window.webContents.mainFrame.frames[0].executeJavaScript('!document.querySelector("#verify-seal") && document.querySelector("img")?.naturalWidth === 1'); } catch { return false; } }, 'Direct GIF display failed.');
  await clickText('Viewing'); await run('document.querySelectorAll(".shell-choice-grid button")[0].click()'); await clickText('Preview');
  await until(async () => { try { return await window.webContents.mainFrame.frames[0].executeJavaScript('document.body.dataset.verification === "verified"'); } catch { return false; } }, 'Canonical GIF shell did not restore.');
  await fs.writeFile(path.join(screenshotDir, 'gif-canonical-shell.png'), (await window.webContents.capturePage()).toPNG());
  const finalWorkspace = await run('window.keel.request("workspace")');
  const gifObject = finalWorkspace.state.objects.find((object) => object.name === 'large-test.gif');
  const exportedGif = path.join(dir, 'round-trip.gif');
  dialog.showSaveDialog = async () => ({ canceled: false, filePath: exportedGif });
  await run(`window.keel.request('exportObject', ${JSON.stringify(gifObject.id)})`);
  assert.deepEqual(await fs.readFile(exportedGif), gifBytes);
  // Artist workflow: real metadata covers, portable JSON, guided release and pinned checks.
  const setField = (label, value, kind = 'input') => run(`(() => { const field = [...document.querySelectorAll('label.field')].find(e => e.querySelector('span')?.textContent === ${JSON.stringify(label)}); const e = field?.querySelector(${JSON.stringify(kind)}); if (!e) throw new Error('Missing artist field: ' + ${JSON.stringify(label)}); Object.getOwnPropertyDescriptor(e instanceof HTMLSelectElement ? HTMLSelectElement.prototype : e instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype, 'value').set.call(e, ${JSON.stringify(value)}); e.dispatchEvent(new Event(e instanceof HTMLSelectElement ? 'change' : 'input', { bubbles: true })); })()`);
  const artworkSvg = '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800"><rect width="1200" height="800" fill="#102722"/><g fill="none" stroke="#a5cbbb" stroke-width="2">' + Array.from({length: 18}, (_, i) => `<ellipse cx="600" cy="400" rx="${65+i*20}" ry="${250-i*7}" transform="rotate(${i*11} 600 400)"/>`).join('') + '</g><circle cx="600" cy="400" r="72" fill="#dfb07c"/><text x="55" y="725" fill="#c7dcd2" font-family="serif" font-size="30">Signal Garden / native test artwork</text></svg>';
  const metadataPath = path.join(dir, 'artwork-metadata.json');
  const document = { name: 'Signal Garden', description: 'A field of overlapping signals. Metadata and artwork remain together.', image: 'data:image/svg+xml,' + encodeURIComponent(artworkSvg), artist: 'Test artist', attributes: [{ trait_type: 'Year', value: 2026, display_type: 'number' }], properties: { customFixture: true } };
  await fs.writeFile(metadataPath, JSON.stringify(document));
  await clickText('Metadata');
  dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [metadataPath] });
  await clickText('Import metadata JSON');
  await until(async () => (await run('document.querySelector(".metadata-preview img")?.naturalWidth')) === 1200, 'Metadata image did not replace the fallback cover.');
  await setField('Project name', '');
  assert.equal(await run('!!document.querySelector(".metadata-form")'), true, 'Clearing a project title crashed the editor.');
  await setField('Project name', 'Signal Garden');
  await setField('Description', document.description + ' Reviewed in the editor.', 'textarea');
  await fill('input[aria-label="Trait 1 value"]', '2027');
  const metadataExport = path.join(dir, 'metadata-export.json');
  dialog.showSaveDialog = async () => ({ canceled: false, filePath: metadataExport });
  await clickText('Export metadata JSON');
  await until(() => syncFs.existsSync(metadataExport), 'Metadata export failed.');
  publishedMetadata = JSON.parse(await fs.readFile(metadataExport, 'utf8'));
  assert.equal(publishedMetadata.attributes[0].value, 2027);
  assert.equal(publishedMetadata.properties.customFixture, true);
  window.setSize(1512, 982);
  await wait(300);
  await fs.writeFile(path.join(screenshotDir, 'artist-metadata.png'), (await window.webContents.capturePage()).toPNG());
  await clickText('← All projects');
  await until(async () => (await run('document.querySelector(".project-card img")?.naturalWidth')) === 1200, 'Home card did not show the metadata image.');
  assert.equal(await run('document.querySelector(".project-card img").getAttribute("alt")'), 'Signal Garden');
  await fs.writeFile(path.join(screenshotDir, 'artist-project-covers.png'), (await window.webContents.capturePage()).toPNG());
  await run('document.querySelector(".project-card").click()');
  await clickText('Phone');
  assert.equal(await run('Math.round(document.querySelector(".preview-stage iframe").getBoundingClientRect().width)'), 390);
  await clickText('Desktop');
  assert.equal(await run('Math.round(document.querySelector(".preview-stage iframe").getBoundingClientRect().width)'), 1280);
  await clickText('Focus view'); assert.equal(await run('!!document.querySelector(".focus-preview")'), true);
  await run('window.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape" }))');
  assert.equal(await run('!!document.querySelector(".focus-preview")'), false); await clickText('Fit');
  await clickText('Release');
  await run('document.querySelector(".creation-main .disclosure").open=true');
  await setField('What would you like to do?', 'release', 'select');
  await setField('How should the work be preserved?', 'inline', 'select');
  await clickText('An edition'); await setField('Number of copies', '25');
  await clickText('Continue to collection →');
  await until(async () => await run('!!document.querySelector(".release-options")'), 'The saved collection step did not open.');
  await run('document.querySelector(".release-options").open=true');
  await setField('Collection type', 'erc1155', 'select');
  await run('[...document.querySelectorAll(".access-cards label")].find(e=>e.textContent.includes("People on a list")).querySelector("input").click()');
  await run('[...document.querySelectorAll(".access-cards label")].find(e=>e.textContent.includes("Collection holders")).querySelector("input").click()');
  await setField('How should these rules combine?', 'any', 'select'); await setField('Extra authorization', 'none', 'select');
  await clickText('Save & preview');
  await until(async () => !(await text()).includes('Unsaved changes'), 'Wizard did not save.');
  let artistProject = (await run('window.keel.request("workspace")')).state.projects[0];
  assert.deepEqual(artistProject.intent.access, ['allowlist', 'erc721']); assert.equal(artistProject.intent.gateLogic, 'any');
  assert.equal(artistProject.intent.chainId, 11155111); assert.ok(artistProject.targetNetworkId);
  await fs.writeFile(path.join(screenshotDir, 'artist-release-access.png'), (await window.webContents.capturePage()).toPNG());
  await setField('How will people collect?', 'one-mint', 'select');
  await clickText('+ Allowlist'); await clickText('+ Public');
  await run(`document.querySelector('button[aria-label="Move public earlier"]').click()`);
  await clickText('Save & preview');
  await until(async () => !(await text()).includes('Unsaved changes'), 'Phase order did not save.');
  artistProject = (await run('window.keel.request("workspace")')).state.projects[0];
  assert.deepEqual(artistProject.intent.stages, ['public', 'allowlist']); assert.equal(artistProject.intent.access, undefined);
  await clickText('Manage');
  await setField('Collection contract', '0x1111111111111111111111111111111111111111'); await setField('Token ID', '7');
  await setField('Token network chain ID', '11155111'); await clickText('Use this token in draft');
  await clickText('Save & check onchain');
  await until(async () => (await text()).includes('JSON was embedded in the contract response.'), 'Pinned onchain metadata check did not appear.');
  assert.ok((await text()).includes('A successful token URI read alone does not prove the full work is onchain.'));
  const metadataReport = await run(`window.keel.request('projectChecks', ${JSON.stringify(artistProject.id)})`);
  assert.equal(metadataReport[0].current, true); assert.equal(metadataReport[0].onchain.block, '42');
  assert.equal(metadataReport[0].onchain.checks.find(check=>check.id==='draft-match').status, 'pass');
  await fs.writeFile(path.join(screenshotDir, 'artist-project-management.png'), (await window.webContents.capturePage()).toPNG());
  await run('document.querySelector(".checks-panel").scrollIntoView({ block: "start" })');
  await fs.writeFile(path.join(screenshotDir, 'artist-project-checks.png'), (await window.webContents.capturePage()).toPNG());
  await clickText('Metadata'); await setField('Description', 'A changed draft.', 'textarea'); await clickText('Manage');
  assert.ok((await text()).includes('Earlier check · project has changed'));
  assert.equal((await text()).includes('JSON was embedded in the contract response.'), false, 'Old metadata proof remained in the current rating.');
  await clickText('Save & check files');
  await until(async () => (await text()).includes('original files checked using SHA-256.'), 'Original file hash checks did not complete.');
  await clickText('Viewing'); await fill('input[aria-label="Project index query"]', 'Signal'); await clickText('Check Studio index');
  await until(async () => (await text()).includes('match an attached file fingerprint'), 'Artist index result coverage was not shown.');
  assert.ok((await text()).includes('Viewer counts')); assert.ok((await text()).includes('Not connected'));
  window.setSize(1000, 800); await wait(200);
  for (const tab of ['Metadata', 'Release', 'Manage', 'Viewing', 'Preview']) { await clickText(tab); await wait(50); assert.equal(await run('document.documentElement.scrollWidth <= innerWidth && document.querySelector(".main-panel").scrollWidth <= document.querySelector(".main-panel").clientWidth'), true, `${tab} overflowed the compact window.`); }
  await clickText('Metadata');
  await fs.writeFile(path.join(screenshotDir, 'artist-metadata-compact.png'), (await window.webContents.capturePage()).toPNG());
  await new Promise((resolve) => fixtureStudio.close(resolve));
  const extensionFolder = path.join(dir, 'fixture-extension'); await fs.mkdir(extensionFolder);
  await fs.writeFile(path.join(extensionFolder, 'manifest.json'), JSON.stringify({ manifest_version: 3, name: 'KEEL test wallet · no keys', version: '1.0.0', permissions: ['storage'], action: { default_popup: 'popup.html' }, content_scripts: [{ matches: ['<all_urls>'], js: ['content.js'] }] }));
  await fs.writeFile(path.join(extensionFolder, 'popup.html'), '<!doctype html><h1>Wallet fixture only</h1>');
  await fs.writeFile(path.join(extensionFolder, 'content.js'), 'globalThis.fixtureWalletInjected = true;');
  dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [extensionFolder] });
  await run(`[...document.querySelectorAll('.nav-item')].find(e=>e.textContent.includes('Wallets')).click()`);
  await until(async () => (await text()).includes('Your wallets.'), 'Wallet area failed to render.');
  await run('document.querySelector(".extension-lab").open=true');
  await clickText('Choose extension folder');
  await until(async () => (await text()).includes('Install KEEL test wallet'), 'Extension permissions were not shown.');
  await run('document.querySelector(".wallet-review details").open=true');
  assert.ok((await text()).includes('<all_urls>'));
  assert.equal(await run(`[...document.querySelectorAll('button')].find(e=>e.textContent==='Install & open wallet').disabled`), true);
  await run('document.querySelector(".wallet-review input[type=checkbox]").click()');
  await clickText('Install & open wallet');
  await until(async () => (await text()).includes('Ready to connect'), 'Fixture extension did not load.');
  assert.equal(session.defaultSession.extensions.getAllExtensions().length, 0);
  assert.equal(await run('typeof fixtureWalletInjected'), 'undefined');
  await clickText('Open wallet');
  await until(() => BrowserWindow.getAllWindows().length === 2, 'Wallet extension window failed to open.');
  const popup = BrowserWindow.getAllWindows().find((entry) => entry !== window);
  await until(async () => (await popup.webContents.executeJavaScript('document.body.innerText')).includes('Wallet fixture only'), 'Extension start page failed.');
  assert.equal(await popup.webContents.executeJavaScript('typeof window.keel'), 'undefined');
  assert.equal(await popup.webContents.executeJavaScript('typeof require'), 'undefined');
  await popup.webContents.executeJavaScript('localStorage.setItem("fixture-continuity","retained-no-keys")');
  await popup.webContents.session.flushStorageData();
  const installed = (await run('window.keel.request("walletExtensions")')).installed[0];
  assert.equal(installed.compatibility, 'unverified');
  assert.equal(installed.signingBridge, 'not-connected');
  await run('document.querySelector(".connected-wallet .button-row>details").open=true');
  await clickText('Disable');
  await until(() => BrowserWindow.getAllWindows().length === 1, 'Disable did not close the extension window.');
  await until(async () => await run('[...document.querySelectorAll("button")].some(e=>e.textContent.trim()==="Enable" && !e.disabled)'), 'Disabled wallet controls did not settle.');
  await clickText('Enable');
  await until(async () => (await text()).includes('Ready to connect'), 'Extension did not re-enable.');
  window.setSize(1512, 982); await wait(250);
  await fs.writeFile(path.join(screenshotDir, 'wallets-desktop.png'), (await window.webContents.capturePage()).toPNG());
  const report = { status: 'passed', workspaceDir: dir, extensionId: installed.extensionId, installationId: installed.installationId, evidence: ['native-electron-render','artist-metadata-image-precedence-json-import-export-and-custom-fields','artist-phone-desktop-focus-preview','guided-access-combinations-and-ordered-drop-phases','pinned-metadata-readback-local-drift-and-history','artist-index-coverage-and-no-fake-view-counts', 'duplicate-save-blocked-and-edits-during-save-preserved', 'pending-contract-and-gas-results-discarded-after-input-edit', 'canonical-shell-default-and-explicit-bypass', 'custom-network-encrypted-profile-live-fee-refresh-and-exact-gas-estimate', 'large-GIF-import-verified-display-and-exact-export', 'compressed-delivery-policy-and-direct-contract-guidance', 'project-create-edit-save', 'unsaved-close-keeps-editor-open', 'preview-has-no-node-or-ipc', 'preview-network-blocked', 'local-ES-module-and-local-fetch', 'cross-project-fetch-blocked', 'native-file-dialog-ABI-import', 'ABI-read-write-controls', 'exact-integer-unsigned-review', 'pinned-RPC-read-and-unsigned-simulation', 'edited-call-invalidates-old-simulation', 'Studio-capability-and-shared-MCP-search', 'module-reference-persistence', 'dismissed-backup-review-releases-pending-import', 'native-workspace-export-and-preserving-import', 'desktop-and-compact-no-overflow', 'extension-permission-review-install', 'extension-separate-profile-no-editor-injection', 'extension-no-node-or-editor-bridge', 'disable-and-reenable'], screenshotDir, rendererErrors: errors };
  // Expected CSP violations from the deliberate network probe are security evidence.
  assert.ok(errors.every((message) => /Content Security Policy|connect-src|Refused to connect/.test(message)), errors.join('\n'));
  await fs.writeFile(path.join(screenshotDir, 'smoke-report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report));
  app.exit(0);
})().catch(async (error) => {
  console.error(error);
  const window = BrowserWindow.getAllWindows()[0];
  if (window) console.error('Failure state', await window.webContents.executeJavaScript('({ tab:[...document.querySelectorAll(".tabs .selected")].map(e=>e.textContent), metadata:!!document.querySelector(".metadata-form"), images:[...document.images].map(e=>({src:e.src.slice(0,70),width:e.naturalWidth})), alert:document.querySelector("[role=alert]")?.textContent })').catch(()=>null));
  if (window && screenshotDir) await fs.writeFile(path.join(screenshotDir, 'failure.png'), (await window.webContents.capturePage()).toPNG()).catch(() => {});
  app.exit(1);
});
