const {app,BrowserWindow,dialog}=require('electron');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const assert=require('node:assert/strict');
process.env.KEEL_DESKTOP_TEST_HIDDEN='1';BrowserWindow.prototype.show=function(){};BrowserWindow.prototype.focus=function(){};
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,label){for(let i=0;i<160;i++){if(await fn())return;await wait(80);}throw Error(label);}
const timeout=setTimeout(()=>{console.error('Layer tests timed out');app.exit(1)},120000);
(async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'keel-layer-test-'));process.env.KEEL_DESKTOP_DATA_DIR=directory;
require('../dist/main.cjs');await until(()=>BrowserWindow.getAllWindows().length,'No editor');const window=BrowserWindow.getAllWindows()[0];window.setSize(1512,982);window.webContents.setBackgroundThrottling(false);const run=async s=>{try{return await window.webContents.executeJavaScript(s,true);}catch(e){console.error('Failed fixture script:',s.slice(0,350));throw e;}};await until(()=>run('document.querySelectorAll(".template-card").length===6'),'No layered template');
const errors=[];window.webContents.on('console-message',e=>{if(e.level==='error'&&!e.message.includes('Electron Security Warning')){errors.push(e.message);console.error('Renderer:',e.message)}});
const idle=()=>until(()=>run('document.querySelector(".main-panel")?.getAttribute("aria-busy")==="false"'),'UI busy');const click=async text=>{await idle();await until(()=>run(`[...document.querySelectorAll('button')].some(b=>b.textContent.trim()===${JSON.stringify(text)}&&!b.disabled)`),'Button unavailable: '+text);await run(`[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)}&&!b.disabled).click()`);await idle();};
await run(`[...document.querySelectorAll('.template-card')].find(b=>b.innerText.includes('Layered PFPs')).click()`);await idle();await until(()=>run('!!document.querySelector(".layer-workbench")'),'No layer editor');
await run(`(()=>{const input=document.querySelector('input[aria-label="New attribute"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Background');input.dispatchEvent(new Event('input',{bubbles:true}));input.form.requestSubmit();})()`);
const makePNG=async(name,script)=>{const data=await run(`(()=>{const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');${script};return c.toDataURL().split(',')[1]})()`);const file=path.join(directory,name+'.png');fs.writeFileSync(file,Buffer.from(data,'base64'));return file;};
const background=await makePNG('Lilac',"ctx.fillStyle='#b2a4d6';ctx.fillRect(0,0,128,128)");dialog.showOpenDialog=async()=>({canceled:false,filePaths:[background]});await click('＋ Add item image');await until(()=>run('document.querySelector(".layer-canvas canvas")?.style.visibility==="visible"'),'Layer import failed to render');
await click('Save & preview');const saved=await run('window.keel.request("workspace")');let project=saved.state.projects.at(-1);assert.equal(project.layered.attributes[0].items[0].name,'Lilac');const layerObject=saved.state.objects.find(o=>o.id===project.layered.attributes[0].items[0].variants[0].objectId);assert.equal(layerObject.type,'image/png');assert.ok(saved.state.objects.some(o=>o.type==='image/png'));assert.equal(await run('document.querySelector(".layer-png-preview").src.startsWith("data:image/png;base64,")'),true);assert.equal(project.presentation.shell,'canonical');assert.equal(project.files.length,0);
const {build}=require('esbuild');const bundle=await build({stdin:{contents:"import * as art from '@keel/sdk/layered-art';import * as renderer from '@keel/sdk/layered-renderer';import {renderLayeredSVG} from '@keel/sdk/layered-svg';window.layerTest={...art,...renderer,renderLayeredSVG};",resolveDir:path.resolve(__dirname,'..'),loader:'js'},bundle:true,write:false,format:'iife',platform:'browser'});await run(bundle.outputFiles[0].text);
// Prove actual canvas composition, clipping, mesh and committed byte verification.
const proof=await run(`(async()=>{const t=window.layerTest;const source=document.createElement('canvas');source.width=source.height=64;const s=source.getContext('2d');s.fillStyle='red';s.fillRect(0,0,64,64);const red=new Uint8Array(await(await new Promise(r=>source.toBlob(r))).arrayBuffer());s.fillStyle='blue';s.fillRect(0,0,64,64);const blue=new Uint8Array(await(await new Promise(r=>source.toBlob(r))).arrayBuffer());const rid=await t.layerDigest(red),bid=await t.layerDigest(blue);const item=(id,objectId,p)=>({id,name:id,weight:1,variants:[{id:'v',name:'v',objectId,weight:1}],placements:p,rules:[],usage:{scope:'public',renderer:'',license:'CC0',tags:[]}});const art={...t.newLayeredArt(),width:64,height:64,attributes:[{id:'back',name:'Back',items:[item('red',rid,[t.defaultPlacement('back',1)])]},{id:'front',name:'Front',items:[item('blue',bid,[{...t.defaultPlacement('front',5),mask:[[0,0],[.5,0],[.5,1],[0,1]],mesh:{source:[[0,0],[1,0],[1,1],[0,1]],target:[[0,0],[1,0],[1,1],[0,1]],triangles:[[0,1,2],[0,2,3]]}}])]}]};const canvas=document.createElement('canvas');const selection=await t.selectLayeredArt(art,'test','1');const resolve=async id=>({bytes:id===rid?red:blue,type:'image/png'});await t.renderLayeredArt(canvas,art,selection,resolve);const pixel=x=>Array.from(canvas.getContext('2d').getImageData(x,32,1,1).data);const left=pixel(8),right=pixel(56);let tamper=false;try{await t.renderLayeredArt(canvas,art,selection,async()=>({bytes:red,type:'image/png'}))}catch(e){tamper=/digest/.test(e.message)};const outputs=[];for(const format of ['image/png','image/webp','image/jpeg'])outputs.push((await t.encodeLayeredCanvas(canvas,{...art,format,background:'#ffffff'})).type);const svg=await t.renderLayeredSVG(art,selection,resolve);const url='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg.source);const image=new Image();await new Promise((ok,fail)=>{image.onload=ok;image.onerror=fail;image.src=url;});const dest=document.createElement('canvas');dest.width=dest.height=64;dest.getContext('2d').drawImage(image,0,0);const svgLeft=Array.from(dest.getContext('2d').getImageData(8,32,1,1).data),svgRight=Array.from(dest.getContext('2d').getImageData(56,32,1,1).data);return {left,right,tamper,outputs,svgLeft,svgRight,svgSafe:!/<script|foreignObject/.test(svg.source)};})()`);
assert.deepEqual(proof.left,[0,0,255,255]);assert.deepEqual(proof.right,[255,0,0,255]);assert.equal(proof.tamper,true);assert.deepEqual(proof.outputs,['image/png','image/webp','image/jpeg']);assert.deepEqual(proof.svgLeft,proof.left);assert.deepEqual(proof.svgRight,proof.right);assert.equal(proof.svgSafe,true);
// Exception slot changes are measured in actual rendered pixels, not only manifest fields.
const exceptionProof=await run(`(async()=>{const t=window.layerTest,c=document.createElement('canvas');c.width=c.height=16;const ctx=c.getContext('2d');const assets={};const attributes=[];for(const [id,color,slot] of [['red','red',1],['blue','blue',5]]){ctx.fillStyle=color;ctx.fillRect(0,0,16,16);const bytes=new Uint8Array(await(await new Promise(r=>c.toBlob(r))).arrayBuffer());const objectId=await t.layerDigest(bytes);assets[objectId]={bytes,type:'image/png'};attributes.push({id,name:id,items:[{id,name:id,weight:1,variants:[{id:'v',name:'v',objectId,weight:1}],placements:[t.defaultPlacement('whole',slot)],rules:[],usage:{scope:'public',renderer:'',license:'CC0',tags:[]}}]});}const art={...t.newLayeredArt(),width:16,height:16,attributes,exceptions:[{id:'move',name:'Red in front',enabled:true,match:'all',conditions:attributes.map(a=>({attributeId:a.id,itemIds:[a.id],mode:'include'})),actions:[{kind:'move',attributeId:'red',itemId:'red',slot:8}]}]};const selections=await t.selectLayeredArt(art,'test','1');await t.renderLayeredArt(c,art,selections,async id=>assets[id]);const after=[...ctx.getImageData(8,8,1,1).data];art.exceptions[0].enabled=false;await t.renderLayeredArt(c,art,selections,async id=>assets[id]);return {after,before:[...ctx.getImageData(8,8,1,1).data]};})()`);
assert.deepEqual(exceptionProof.after,[255,0,0,255]);assert.deepEqual(exceptionProof.before,[0,0,255,255]);
// Add portrait-like fixtures through original object storage, then inspect the real artist UI.
const face=await makePNG('Terracotta',"ctx.fillStyle='#bd795d';ctx.beginPath();ctx.roundRect(24,20,80,102,30);ctx.fill();ctx.fillStyle='#e4a184';ctx.fillRect(28,55,10,23)");
const eyes=await makePNG('Wide eyes',"ctx.fillStyle='#fff5dc';ctx.fillRect(38,60,18,15);ctx.fillRect(73,60,18,15);ctx.fillStyle='#292431';ctx.fillRect(46,63,8,10);ctx.fillRect(73,63,8,10);ctx.fillRect(55,92,18,4)");
const hair=await makePNG('Cobalt curls',"ctx.fillStyle='#293d78';for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(27+i*19,32,18,0,Math.PI*2);ctx.fill();}ctx.fillRect(12,37,15,53);ctx.fillRect(99,37,15,50)");
for(const [name,file] of [['Face',face],['Expression',eyes],['Hair',hair]]){await run(`(()=>{const input=document.querySelector('input[aria-label="New attribute"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,${JSON.stringify(name)});input.dispatchEvent(new Event('input',{bubbles:true}));input.form.requestSubmit();})()`);dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});await click('＋ Add item image');}
await until(()=>run('document.querySelector(".layer-canvas canvas").style.visibility==="visible"'),'Portrait did not render');await click('＋ Another piece of this image');await click('Draw boundary');await until(()=>run('!!document.querySelector(".layer-canvas svg")'),'Boundary overlay did not appear');for(const [x,y] of [[.5,0],[1,0],[1,1],[.5,1]]){await run(`(()=>{const svg=document.querySelector('.layer-canvas svg');const b=svg.getBoundingClientRect();svg.dispatchEvent(new PointerEvent('pointerdown',{clientX:b.left+${x}*b.width,clientY:b.top+${y}*b.height,bubbles:true}));})()`);await wait(40);}await click('Finish boundary');await click('Test 100 combinations');await until(()=>run('document.querySelectorAll(".layer-contact-sheet img").length===12'),'No visual sample sheet');await click('Save & preview');
const result=await run('window.keel.request("workspace")');project=result.state.projects.at(-1);assert.equal(project.layered.attributes.length,4);assert.equal(project.layered.attributes[3].items[0].placements.length,2);assert.equal(project.layered.attributes[3].items[0].placements[1].mask.length,4);
// Create and edit the visual combination builder, then persist it through the real bridge.
await click('＋ Add combination rule');await until(()=>run('document.querySelectorAll(".layer-exception-card").length===1'),'No combination card');
await click('＋ Add condition');await run(`(()=>{for(const input of [document.querySelectorAll('select[aria-label=\"Condition item\"]')[1],document.querySelector('select[aria-label=\"Action item\"]')]){Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(input,input.options[input.options.length-1].value);input.dispatchEvent(new Event('change',{bubbles:true}));}})()`);await run(`(()=>{const input=document.querySelector('input[aria-label="Exception layer"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'35');input.dispatchEvent(new Event('input',{bubbles:true}));})()`);
await until(()=>run('document.querySelector(".layer-exception-heading [role=status]").textContent.includes("Applied")'),'Exception not applied');
await click('Save & preview');const ruled=await run('window.keel.request("workspace")');const ruleProject=ruled.state.projects.at(-1);assert.equal(ruleProject.layered.exceptions[0].conditions.length,2);assert.equal(ruleProject.layered.exceptions[0].actions[0].slot,35);assert.equal(ruleProject.runtimeModules.find(r=>r.id.startsWith('keel-layered')).id,'keel-layered-runtime-v3');
const rightClicked=path.join(directory,'right-click.png');dialog.showSaveDialog=async()=>({canceled:false,filePath:rightClicked});await run(`document.querySelector('.layer-canvas svg').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))`);await until(()=>fs.existsSync(rightClicked),'Right-click PNG was not saved');assert.equal(fs.readFileSync(rightClicked).subarray(0,8).toString('hex'),'89504e470d0a1a0a');
const exported=path.join(directory,'rendered.png');dialog.showSaveDialog=async()=>({canceled:false,filePath:exported});await click('Export this image');assert.equal(fs.readFileSync(exported).subarray(0,8).toString('hex'),'89504e470d0a1a0a');
fs.writeFileSync(path.resolve(__dirname,'../artifacts/layers-editor.png'),(await window.webContents.capturePage()).toPNG());window.setSize(920,850);await wait(200);const layout=await run('({width:innerWidth,scroll:document.documentElement.scrollWidth,main:document.querySelector(".main-panel").clientWidth,mainScroll:document.querySelector(".main-panel").scrollWidth})');assert.ok(layout.scroll<=layout.width&&layout.mainScroll<=layout.main,JSON.stringify(layout));fs.writeFileSync(path.resolve(__dirname,'../artifacts/layers-compact.png'),(await window.webContents.capturePage()).toPNG());
window.setSize(1512,982);await run('document.querySelector(".layer-exceptions").scrollIntoView({block:"start"})');await wait(200);fs.writeFileSync(path.resolve(__dirname,'../artifacts/layer-exceptions-desktop.png'),(await window.webContents.capturePage()).toPNG());window.setSize(920,850);await run('document.querySelector(".layer-exceptions").scrollIntoView({block:"start"})');await wait(200);const rulesLayout=await run('({width:innerWidth,scroll:document.documentElement.scrollWidth,main:document.querySelector(".main-panel").clientWidth,mainScroll:document.querySelector(".main-panel").scrollWidth})');assert.ok(rulesLayout.scroll<=rulesLayout.width&&rulesLayout.mainScroll<=rulesLayout.main,JSON.stringify(rulesLayout));assert.equal(await run(`(()=>{const row=document.querySelector('.layer-exceptions .layer-rule'),select=row.querySelector('select');return select.getBoundingClientRect().width>parseFloat(getComputedStyle(row).gridTemplateColumns)*.95;})()`),true);fs.writeFileSync(path.resolve(__dirname,'../artifacts/layer-exceptions-compact.png'),(await window.webContents.capturePage()).toPNG());
// Direct choices are persisted separately from HTML settings; SVG opens as a real image.
await click('Set up direct image');await run(`(()=>{const s=[...document.querySelectorAll('.direct-image-settings select')].at(-1);Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(s,'svg');s.dispatchEvent(new Event('change',{bubbles:true}));})()`);await idle();await until(()=>run('[...document.querySelectorAll("button")].some(b=>b.textContent==="Save SVG of this preview"&&!b.disabled)'),'SVG action missing');
const svgFile=path.join(directory,'preview.svg');dialog.showSaveDialog=async()=>({canceled:false,filePath:svgFile});await click('Save SVG of this preview');assert.match(fs.readFileSync(svgFile,'utf8'),/^<svg xmlns="http:\/\/www.w3.org\/2000\/svg"/);const directProject=(await run('window.keel.request("workspace")')).state.projects.at(-1);assert.equal(directProject.directImage.format,'svg');assert.equal(directProject.layered.format,'image/png');assert.equal(directProject.presentation.shell,'canonical');
// Exercise the real pool, ordered set, rarity controls, persistence and private export.
window.setSize(1512,982);await run('document.querySelector(".layer-curation").scrollIntoView({block:"start"})');
await run(`(()=>{const i=document.querySelector('.layer-curation .curation-controls input[type=number]:last-of-type');const inputs=document.querySelectorAll('.layer-curation .curation-controls input[type=number]');const count=inputs[1];Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(count,'3');count.dispatchEvent(new Event('input',{bubbles:true}));})()`);
await click('Generate candidates');await until(()=>run('document.querySelectorAll(".curation-card").length===3'),'Candidates were not generated');
await click('Keep this preview');await until(()=>run('document.querySelectorAll(".curation-card").length===4'),'Preview was not retained');
await click('Add to set');assert.equal(await run('document.querySelectorAll(".curation-set .curation-card").length'),1);
await run(`(()=>{const cards=document.querySelectorAll('.curation-columns > div:first-child .curation-card');const transfer=new DataTransfer();cards[0].dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));document.querySelector('.curation-set').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));})()`);await idle();await until(()=>run('document.querySelectorAll(".curation-set .curation-card").length===2'),'Drag to set failed');
await run(`(()=>{const cards=document.querySelectorAll('.curation-set .curation-card');const transfer=new DataTransfer();cards[1].dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));cards[0].dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));})()`);await idle();
await run(`(()=>{const section=[...document.querySelectorAll('.layer-curation details')].find(d=>d.querySelector('summary').textContent.includes('Rarity'));section.open=true;})()`);await click('Check pool and set rarity');assert.equal(await run('document.querySelector(".layer-curation details [role=status]")?.textContent.includes("0 broken candidates")'),true);
await click('Save & preview');const curated=(await run('window.keel.request("workspace")')).state.projects.at(-1);assert.equal(curated.layerCuration.candidates.length,4);assert.deepEqual(curated.layerCuration.set,curated.layerCuration.candidates.slice(0,2).reverse().map(c=>c.id));
await run('document.querySelector(".curation-columns").scrollIntoView({block:"center"})');await until(()=>run('[...document.querySelectorAll(".curation-card img")].length===4'),'PNG thumbnails missing');assert.equal(await run('[...document.querySelectorAll(".curation-card img")].every(i=>i.src.startsWith("data:image/png;base64,"))'),true);
fs.writeFileSync(path.resolve(__dirname,'../artifacts/layer-curation-desktop.png'),(await window.webContents.capturePage()).toPNG());window.setSize(920,850);await wait(150);await run('document.querySelector(".curation-columns").scrollIntoView({block:"start"})');await wait(150);assert.equal(await run('document.querySelector(".main-panel").scrollWidth<=document.querySelector(".main-panel").clientWidth'),true);fs.writeFileSync(path.resolve(__dirname,'../artifacts/layer-curation-compact.png'),(await window.webContents.capturePage()).toPNG());
const planFile=path.join(directory,'private-set-plan.json');dialog.showSaveDialog=async()=>({canceled:false,filePath:planFile});await click('Export private set plan');const setPlan=JSON.parse(fs.readFileSync(planFile,'utf8'));assert.equal(setPlan.allocations[0].setPosition,1);assert.equal(setPlan.allocations[0].drawTokenId,'2');assert.equal(setPlan.publicationReady,false);
window.webContents.reload();await until(()=>run('document.querySelectorAll(".project-card").length>0'),'Reload did not restore workspace');await run('document.querySelector(".project-card").click()');await until(()=>run('document.querySelectorAll(".curation-card").length===4'),'Candidate pool did not restore');assert.equal(await run('document.querySelectorAll(".curation-set .curation-card").length'),2);
await click('Choose collection →');assert.equal(await run('document.querySelector(".artwork-upload").innerText.includes("Edit layers")'),true);await click('Open full preview ↗');await until(async()=>{try{const outer=window.webContents.mainFrame.frames.find(f=>f.url.startsWith('keel-preview:'));return outer&&await outer.executeJavaScript('document.body.dataset.verification==="verified"')&&outer.frames[0]&&await outer.frames[0].executeJavaScript('!!window.keelRender&&document.querySelector("canvas").width===1024&&document.querySelector("img").src.startsWith("data:image/png;base64,")&&!document.querySelector("img").hidden');}catch{return false;}},'Layer module did not render in canonical shell').catch(async e=>{for(const frame of window.webContents.mainFrame.frames){console.error('Outer frame:',frame.url,await frame.executeJavaScript('({text:document.body.innerText.slice(0,1800),state:document.body.dataset.verification})'));for(const child of frame.frames)console.error('Child:',await child.executeJavaScript('({text:document.body.innerText.slice(0,1600),canvas:document.querySelector("canvas")?.width,render:typeof window.keelRender,crypto:!!globalThis.crypto?.subtle})'));}throw e;});
assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'passed',proof,exceptionProof,checks:['lossless PNG import with preserved original','right-click PNG save','pool batch and preview capture','drag assignment and reorder','rarity counts','curation persistence and private plan export','combination rule builder and persistence','exception pixel composition','saved attributes/items','mask drawing','100 samples and contact sheet','responsive layout','collection guide','canonical shell shared layer runtime'],errors}));clearTimeout(timeout);app.exit(0);
})().catch(e=>{console.error(e);app.exit(1)});
