const {app,BrowserWindow,protocol}=require('electron');
app.commandLine.appendSwitch('force-device-scale-factor','1');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
protocol.registerSchemesAsPrivileged([{scheme:'raster-test',privileges:{standard:true,secure:true,supportFetchAPI:true}}]);
const timer=setTimeout(()=>app.exit(1),45000);
app.whenReady().then(async()=>{let win;try{
 const {compilePNGStrips,assemblePNGStrips,decodeRasterPNG}=await import('../../../packages/sdk/dist/raster-strips.js');const {assembleLayerAPNG}=await import('../../../packages/sdk/dist/raster-apng.js');
 const width=64,height=64,background=new Uint8Array(width*height*4),overlay=new Uint8Array(background.length);for(let i=0;i<background.length;i+=4){background[i]=30;background[i+1]=80;background[i+2]=180;background[i+3]=255;if((i/4)%64<32){overlay[i]=200;overlay[i+1]=30;overlay[i+3]=128;}}
 async function encode(data){const c=compilePNGStrips({width,height,data},16);return assemblePNGStrips(c.recipe,async id=>c.chunks.get(id).bytes);}
 const first=await encode(background),second=await encode(overlay),apng=assembleLayerAPNG([first,second],30);const root=path.resolve(__dirname,'../artifacts/gator-raster-study');
 protocol.handle('raster-test',request=>{const name=new URL(request.url).pathname;if(name==='/stack.apng')return new Response(apng,{headers:{'content-type':'image/apng'}});if(name==='/gator.png')return new Response(fs.readFileSync(path.join(root,'contract-token-0.png')),{headers:{'content-type':'image/png'}});return new Response('<style>img,canvas{image-rendering:pixelated}</style><body style="margin:0"><img id="apng" src="/stack.apng" style="position:absolute;left:0;top:0;width:64px;height:64px"><canvas id="reference" width="64" height="64" style="position:absolute;left:64px;top:0"></canvas><img id="gator" src="/gator.png" style="position:absolute;top:64px;width:216px;height:216px"></body>',{headers:{'content-type':'text/html'}});});
 win=new BrowserWindow({width:300,height:350,show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});await win.loadURL('raster-test://app/');
 await win.webContents.executeJavaScript(`(async()=>{const canvas=document.getElementById('reference'),ctx=canvas.getContext('2d');for(const bytes of ${JSON.stringify([first.toString('base64'),second.toString('base64')])}){const img=new Image();img.src='data:image/png;base64,'+bytes;await img.decode();ctx.drawImage(img,0,0);}await Promise.all([...document.images].map(i=>i.decode()));return true;})()`);
 await new Promise(r=>setTimeout(r,1000));const shot=await win.webContents.capturePage(),scale=shot.getSize().width/await win.webContents.executeJavaScript('innerWidth'),edge=64*scale,left=shot.crop({x:0,y:0,width:edge,height:edge}).toPNG(),right=shot.crop({x:edge,y:0,width:edge,height:edge}).toPNG();const a=await decodeRasterPNG(left),b=await decodeRasterPNG(right);const difference=a.data.reduce((n,v,i)=>n+(v!==b.data[i]),0);assert.equal(difference,0,'Native APNG final display differs from native source-over composition');
 fs.writeFileSync(path.join(root,'native-raster-proof.json'),JSON.stringify({apngFinalDisplayMatchesNativeCanvas:true,standardPNGLoaded:true,apngFrames:2,fixture:'opaque background and partially transparent foreground',scope:'Electron Chromium only'},null,2));fs.writeFileSync(path.join(root,'native-raster-proof.png'),shot.toPNG());console.log('Native APNG final display and standard PNG decode passed.');win.destroy();clearTimeout(timer);app.exit(0);
 }catch(e){console.error(e);win?.destroy();app.exit(1);}});
