const {app,BrowserWindow,protocol}=require('electron');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),recovery='/tmp/keel-gator-recovery';
const size=Number(process.env.KEEL_GATOR_SIZE||1024);assert.ok([1024,1080,1440,1600,2160].includes(size),'Choose a measured fixture size');
const resized=size!==1024,artifactRoot=path.join(root,'apps/desktop/artifacts/gator-recovery');
protocol.registerSchemesAsPrivileged([{scheme:'gator-test',privileges:{standard:true,secure:true,supportFetchAPI:true}}]);
app.on('window-all-closed',()=>{});
const timeout=setTimeout(()=>{console.error('Gator render test timed out');app.exit(1);},90000);
app.whenReady().then(async()=>{try{console.log('Gator render fixture started');
 const {build}=require('esbuild');const {legacyGatorReference}=await import('../scripts/gator-reference.mjs');const reference=await legacyGatorReference(recovery);
 let {manifest}=JSON.parse(fs.readFileSync('/tmp/keel-gator-original-manifest.json','utf8'));
 let resizedRows;
 if(resized){resizedRows=JSON.parse(fs.readFileSync(path.join(artifactRoot,`png-${size}.json`),'utf8'));assert.equal(resizedRows.length,915);const {importGatorLayers}=await import('../../../packages/sdk/dist/gator-import.js');manifest=importGatorLayers(JSON.parse(fs.readFileSync(path.join(artifactRoot,'generatorConfig.json'),'utf8')),resizedRows.map(r=>({path:r.path,objectId:r.objectId})),`gator-${size}`).manifest;manifest.width=size;manifest.height=size;}
 const {gatorStack}=await import('../../../packages/sdk/dist/gator-assembly.js');
 let cases=[{background:'Fresh Squeezed',body:'Rock',eyes:'Frog',mouth:'Stubble',hat:'Fire Hair',costume:'Pirate'},{background:'Red',body:'Gamer',eyes:'Chill',mouth:'Sharp',hat:'None',costume:'None'},{background:'Midnight',body:'Monster',eyes:'Hero',mouth:'Hungry',hat:'Crown',costume:'Mech'}];
 if(process.env.KEEL_GATOR_ORIGINAL_SET){const dataRoot=path.join(root,'apps/desktop/artifacts/gator-sepolia/source-data');const ids=JSON.parse(fs.readFileSync(path.join(dataRoot,'ids.json'),'utf8')),traits=JSON.parse(fs.readFileSync(path.join(dataRoot,'metadata.json'),'utf8'));cases=[0,1,2].map(id=>traits[ids.find(row=>row['Token ID']===id).ID]);}
 const fixtures=cases.map(metadata=>{const stack=gatorStack(manifest.assembly,metadata).stack;const expected=reference.stack(metadata).map(p=>p.replace(/^.*layers\//,''));assert.deepEqual(stack.map(f=>f.path),expected);return {metadata,stack};});
 const assets={};for(const fixture of fixtures)for(const f of fixture.stack)assets[f.objectId]=fs.readFileSync(resized?path.join(artifactRoot,`png-${size}`,resizedRows.find(r=>r.path===f.path).file):path.join(recovery,'public/layers',f.path)).toString('base64');
 const bundle=await build({stdin:{contents:"import * as art from '@keel/sdk/layered-art';import {renderLayeredArt} from '@keel/sdk/layered-renderer';import {renderLayeredSVG} from '@keel/sdk/layered-svg';window.testSDK={...art,renderLayeredArt,renderLayeredSVG};",resolveDir:path.resolve(__dirname,'..'),loader:'js'},bundle:true,write:false,format:'iife',platform:'browser'});
 const win=new BrowserWindow({width:1320,height:570,show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false}});protocol.handle('gator-test',()=>new Response('<html><body style="margin:0;background:#0a0c12;color:white;font:14px sans-serif"><main style="display:flex;gap:12px;padding:16px"></main></body></html>',{headers:{'content-type':'text/html'}}));win.webContents.on('render-process-gone',(_event,details)=>{console.error('Renderer exited',details);app.exit(1);});await win.loadURL('gator-test://app/');await win.webContents.executeJavaScript(bundle.outputFiles[0].text);
 const result=await win.webContents.executeJavaScript(`(async()=>{const size=${size},t=window.testSDK,manifest=${JSON.stringify(manifest)},fixtures=${JSON.stringify(fixtures)},encoded=${JSON.stringify(assets)},results=[];const resolve=async id=>({bytes:Uint8Array.from(atob(encoded[id]),c=>c.charCodeAt(0)),type:'image/png'});for(const [index,fixture]of fixtures.entries()){const selections=manifest.attributes.map(a=>{const item=a.items.find(i=>i.name===fixture.metadata[a.name.toLowerCase()]);return {attributeId:a.id,itemId:item.id,variantId:item.variants[0].id,objectId:item.variants[0].objectId};});const canvas=document.createElement('canvas');await t.renderLayeredArt(canvas,manifest,selections,resolve);const original=document.createElement('canvas');original.width=original.height=size;const ctx=original.getContext('2d');for(const part of fixture.stack){const a=await resolve(part.objectId),img=await createImageBitmap(new Blob([a.bytes],{type:a.type}));ctx.drawImage(img,0,0,size,size);img.close();}const actual=canvas.getContext('2d').getImageData(0,0,size,size).data,expected=ctx.getImageData(0,0,size,size).data;let different=0;for(let i=0;i<actual.length;i++)if(actual[i]!==expected[i])different++;const svg=await t.renderLayeredSVG(manifest,selections,resolve),image=new Image();await new Promise((ok,fail)=>{image.onload=ok;image.onerror=fail;image.src='data:image/svg+xml;base64,'+btoa(svg.source);});const svgCanvas=document.createElement('canvas');svgCanvas.width=svgCanvas.height=size;svgCanvas.getContext('2d').drawImage(image,0,0);const svgPixels=svgCanvas.getContext('2d').getImageData(0,0,size,size).data;let svgDifferent=0,svgMaxDifference=0,svgTotalDifference=0;for(let i=0;i<actual.length;i++){const delta=Math.abs(actual[i]-svgPixels[i]);if(delta)svgDifferent++;svgTotalDifference+=delta;svgMaxDifference=Math.max(svgMaxDifference,delta);}const figure=document.createElement('div');figure.style.width='31%';const display=new Image();display.src=canvas.toDataURL('image/png');display.style.width='100%';figure.append(display);const caption=document.createElement('p');caption.textContent=Object.values(fixture.metadata).join(' · ');figure.append(caption);document.querySelector('main').append(figure);results.push({metadata:fixture.metadata,pieces:fixture.stack.length,different,svgDifferent,svgMaxDifference,svgMeanDifference:svgTotalDifference/actual.length,png:display.src.split(',')[1]});}return results;})()`);
 const output=process.env.KEEL_GATOR_ORIGINAL_SET?path.join(root,'apps/desktop/artifacts/gator-sepolia/original-set-render'):resized?path.join(artifactRoot,`render-${size}`):artifactRoot;fs.mkdirSync(output,{recursive:true});for(const [i,r]of result.entries()){assert.equal(r.different,0,JSON.stringify(r.metadata));fs.writeFileSync(path.join(output,`gator-${i+1}.png`),Buffer.from(r.png,'base64'));delete r.png;}fs.writeFileSync(path.join(output,'native-render-proof.json'),JSON.stringify(result,null,2));await win.webContents.executeJavaScript('Promise.all([...document.images].map(image=>image.decode()))');fs.writeFileSync(path.join(output,'gator-contact-sheet.png'),(await win.webContents.capturePage()).toPNG());console.log(JSON.stringify({size,results:result}));clearTimeout(timeout);win.destroy();app.exit(0);
}catch(e){console.error(e);app.exit(1);}});
