import test from 'node:test';import assert from 'node:assert/strict';
import {importGatorLayers,applyGatorMetadataNames} from '@keel/sdk/gator-import';
import {resolveLayeredArt,selectLayeredArt,defaultPlacement} from '@keel/sdk/layered-art';
function fixture(){const names=['Background','Body','Eyes','Mouth','Hat','Costume'];const config={stack:names,TopperEyes:[],extras:{},attributes:Object.fromEntries(names.map(n=>[n,{main:n,addons:[]}])),weight:Object.fromEntries(names.map(n=>[n,{A:{weight:.5},B:{weight:.5}}])),exclusions:{}};let i=0;const files=names.flatMap(n=>['A','B'].map(trait=>({path:n==='Background'?`Background/Background_${trait}.png`:`${n}/_0000_${n}_${trait}.png`,objectId:(++i).toString(16).padStart(64,'0')})));return importGatorLayers(config,files,'fixture').manifest;}
test('contract trait labels preserve original asset selection and layering for token zero',async()=>{
 const art=fixture(),before=JSON.stringify(art),renamed=applyGatorMetadataNames(art,{Body:{name:'Skin'},Costume:{name:'Outfit'},Hat:{items:{A:'Windblown',B:'Knitted Cap'}}});
 const draw=await selectLayeredArt(art,'chain','0'),updated=await selectLayeredArt(renamed,'chain','0');
 assert.deepEqual(updated,draw);assert.deepEqual(resolveLayeredArt(renamed,updated).pieces,resolveLayeredArt(art,draw).pieces);
 assert.equal(renamed.attributes.find(a=>a.id==='hat').items[0].name,'Windblown');assert.equal(renamed.attributes.find(a=>a.id==='body').name,'Skin');assert.equal(JSON.stringify(art),before);
 const again=applyGatorMetadataNames(renamed,{Hat:{items:{A:'Windblown revised'}}});assert.deepEqual(resolveLayeredArt(again,updated).pieces,resolveLayeredArt(art,draw).pieces);
 assert.throws(()=>applyGatorMetadataNames(art,{Bogus:{name:'Broken'}}),/Unknown source/);
 for(const id of ['-1','01','',(1n<<256n).toString()])await assert.rejects(selectLayeredArt(renamed,'chain',id),/token number/);
});
test('imported assembly inclusion adds an item without replacing the primary stack',async()=>{const art=fixture(),draw=await selectLayeredArt(art,'seed','1',Object.fromEntries(art.attributes.map(a=>[a.id,'b'])));const original=resolveLayeredArt(art,draw);art.exceptions=[{id:'add',name:'Add A hat',enabled:true,match:'all',conditions:[{attributeId:'hat',itemIds:['b'],mode:'include'}],actions:[{kind:'include',attributeId:'hat',itemId:'a',variantId:'original'}]}];const next=resolveLayeredArt(art,draw);assert.equal(next.pieces.length,original.pieces.length+1);assert.deepEqual(next.pieces.filter(p=>p.itemId==='b'),original.pieces);assert.equal(next.pieces.find(p=>p.attributeId==='hat'&&p.itemId==='a').objectId,art.attributes[4].items.find(i=>i.id==='a').variants[0].objectId);});
test('imported assembly respects variants, split pieces, replacement and hide',async()=>{const art=fixture();const hat=art.attributes[4].items.find(i=>i.id==='b');hat.variants.push({id:'alternate',name:'Alternate',objectId:'f'.repeat(64),weight:1});hat.placements.push({...defaultPlacement('split',99),mask:[[0,0],[.5,0],[.5,1]]});const draw=await selectLayeredArt(art,'seed','1',Object.fromEntries(art.attributes.map(a=>[a.id,'b'])),{hat:'alternate'});const before=resolveLayeredArt(art,draw);assert.equal(before.pieces.filter(p=>p.attributeId==='hat').length,2);assert.ok(before.pieces.filter(p=>p.attributeId==='hat').every(p=>p.objectId==='f'.repeat(64)));art.exceptions=[{id:'hide',name:'Hide split',enabled:true,match:'all',conditions:[{attributeId:'hat',itemIds:['b'],mode:'include'}],actions:[{kind:'hide',attributeId:'hat',itemId:'b',placementId:'split'},{kind:'move',attributeId:'hat',itemId:'b',placementId:'part-0',slot:55}]}];const after=resolveLayeredArt(art,draw);assert.equal(after.pieces.filter(p=>p.attributeId==='hat').length,1);assert.equal(after.pieces.find(p=>p.attributeId==='hat').placement.slot,55);art.exceptions[0].actions=[{kind:'replace',attributeId:'hat',itemId:'a',variantId:'original'}];assert.equal(resolveLayeredArt(art,draw).pieces.find(p=>p.attributeId==='hat').itemId,'a');});
