import test from 'node:test';
import assert from 'node:assert/strict';
import {deflateSync,inflateSync} from 'node:zlib';
import {optimizeLayerPNG} from '@keel/sdk/layered-png';
function chunk(type,data){const body=Buffer.concat([Buffer.from(type),data]);let crc=0xffffffff;for(const b of body){crc^=b;for(let i=0;i<8;i++)crc=crc&1?(crc>>>1)^0xedb88320:crc>>>1;}const p=Buffer.alloc(4),s=Buffer.alloc(4);p.writeUInt32BE(data.length);s.writeUInt32BE((crc^0xffffffff)>>>0);return Buffer.concat([p,body,s]);}
function png({depth=8,extra=[],split=false}={}){const header=Buffer.alloc(13);header.writeUInt32BE(2);header.writeUInt32BE(1,4);header[8]=depth;header[9]=6;const pixels=Buffer.from(Array.from({length:2*4*depth/8},(_,i)=>(i*23)%256));const scan=Buffer.concat([Buffer.from([0]),pixels]);const z=deflateSync(scan,{level:0});return {scan,bytes:Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),...extra,...(split?[chunk('IDAT',z.subarray(0,4)),chunk('IDAT',z.subarray(4))]:[chunk('IDAT',z)]),chunk('IEND',Buffer.alloc(0))])};}
function chunks(bytes){const b=Buffer.from(bytes),out=[];for(let at=8;at<b.length;){const n=b.readUInt32BE(at);out.push({type:b.toString('ascii',at+4,at+8),data:b.subarray(at+8,at+8+n)});at+=12+n;}return out;}
test('PNG optimization retains exact samples, precision, alpha and colour chunks',async()=>{for(const depth of [8,16]){const colour=chunk('iCCP',Buffer.concat([Buffer.from('profile\0\0'),deflateSync(Buffer.alloc(128))]));const gamma=chunk('gAMA',Buffer.from([0,0,177,143]));const source=png({depth,split:true,extra:[colour,gamma,chunk('iTXt',Buffer.alloc(160000,32)),chunk('eXIf',Buffer.from('orientation retained'))]});const original=Buffer.from(source.bytes);const r=await optimizeLayerPNG(source.bytes);assert.equal(r.type,'image/png');assert.equal(r.proof,'exact-png-image-stream');assert.deepEqual(source.bytes,original);assert.ok(r.storedBytes<r.originalBytes-150000);const parts=chunks(r.bytes);assert.deepEqual(inflateSync(Buffer.concat(parts.filter(c=>c.type==='IDAT').map(c=>c.data))),source.scan);assert.equal(parts.some(c=>c.type==='iTXt'),false);for(const type of ['iCCP','gAMA','eXIf'])assert.deepEqual(parts.find(c=>c.type===type).data,chunks(source.bytes).find(c=>c.type===type).data);assert.ok(r.bytes.length<=source.bytes.length);}});
test('animation bytes retained and corruption rejected',async()=>{const source=png({extra:[chunk('acTL',Buffer.from([0,0,0,1,0,0,0,0]))]});const r=await optimizeLayerPNG(source.bytes);assert.equal(r.proof,'original-animation-preserved');assert.deepEqual(Buffer.from(r.bytes),source.bytes);const corrupt=Buffer.from(png().bytes);corrupt[45]^=1;await assert.rejects(()=>optimizeLayerPNG(corrupt),/integrity/);await assert.rejects(()=>optimizeLayerPNG(Buffer.concat([png().bytes,Buffer.from([1])])),/after IEND/);});
