import test from 'node:test';import assert from 'node:assert/strict';
import {newLayeredArt,defaultPlacement,parseLayeredArt,selectLayeredArt,layeredDrawList,checkLayeredArt,sampleLayeredArt,layerDigest,layeredManifestDigest} from '@keel/sdk/layered-art';
import {sealLayeredBundle,openLayeredBundle} from '@keel/sdk/layered-reveal';
import {prepareLayeredKeyRelease} from '@keel/sdk/layered-chain';
import {keccak256} from 'viem';
import {layeredHTML,withLayeredPreview} from '../src/layered-project.mjs';
const bytes=new Uint8Array([1,2,3,4]);const id=await layerDigest(bytes);
export function fixture(){return {...newLayeredArt('Layer fixture'),width:64,height:64,attributes:[{id:'background',name:'Background',items:[{id:'blue',name:'Blue',weight:90,variants:[{id:'v1',name:'Default',objectId:id,weight:100}],placements:[defaultPlacement('back',1),{...defaultPlacement('front',5),mask:[[0,0],[.5,0],[.5,1],[0,1]]}],rules:[],usage:{scope:'public',renderer:'',license:'CC0',tags:['colour']}}]}]};}
test('deterministic seeds, weighted rarity, split slots, strict rule identities',async()=>{const art=fixture();const rare=structuredClone(art.attributes[0].items[0]);rare.id='rare';rare.weight=10;art.attributes[0].items.push(rare);const a=await selectLayeredArt(art,'hello','4');assert.deepEqual(a,await selectLayeredArt(art,'hello','4'));assert.deepEqual(layeredDrawList(art,a).map(p=>p.placement.slot),[1,5]);assert.throws(()=>layeredDrawList(art,[...a,...a]),/exactly one/);const sample=await sampleLayeredArt(art,1000,'fixture');assert.ok(sample.counts['background/rare']>60&&sample.counts['background/rare']<150);assert.equal(sample.failures.length,0);assert.equal(sample.guaranteedUnique,false);assert.equal(sample.duplicates,999);const root=await layeredManifestDigest(art);art.seed='another preview';assert.equal(await layeredManifestDigest(art),root);art.attributes[0].items[0].weight=89;assert.notEqual(await layeredManifestDigest(art),root);});
test('checks reject impossible rules, missing bytes and empty render combinations',async()=>{const art=fixture();const off=structuredClone(art.attributes[0].items[0]);off.id='off';off.weight=0;art.attributes[0].items.push(off);const second=structuredClone(art.attributes[0]);second.id='eyes';second.items=[{...off,id:'eye',weight:1,rules:[{attributeId:'background',itemIds:['off'],mode:'include'}]}];art.attributes.push(second);assert.equal(checkLayeredArt(art).ready,false);assert.ok((await sampleLayeredArt(art,10)).failures.length===10);assert.equal(checkLayeredArt(fixture(),[]).ready,false);const invisible=fixture();invisible.attributes[0].items[0].placements.forEach(p=>p.opacity=0);assert.equal((await sampleLayeredArt(invisible,2)).failures.length,2);second.items[0].rules[0].attributeId='eyes';second.items[0].rules[0].itemIds=['eye'];assert.throws(()=>parseLayeredArt(art),/earlier attribute/);});
test('AES bundle hides manifest and restores exact bytes; wrong key and tampering fail',async()=>{const art=fixture();art.reveal={mode:'chainlink',encrypted:true,revealAt:1900000000};const sealed=await sealLayeredBundle(art,[{id,type:'image/png',bytes}]);assert.equal(Buffer.from(sealed.ciphertext).includes(Buffer.from('Background')),false);assert.equal(JSON.stringify(sealed.descriptor).includes(id),false);const opened=await openLayeredBundle(sealed.descriptor,sealed.ciphertext,sealed.key);assert.deepEqual(opened.manifest,art);assert.deepEqual(opened.assets[0].bytes,bytes);await assert.rejects(()=>openLayeredBundle(sealed.descriptor,sealed.ciphertext,new Uint8Array(32)));const changed=sealed.ciphertext.slice();changed[20]^=1;await assert.rejects(()=>openLayeredBundle(sealed.descriptor,changed,sealed.key));await assert.rejects(()=>sealLayeredBundle(art,[{id,type:'image/png',bytes:new Uint8Array([9])}]),/identity/);});
test('key calldata is unavailable before finalized gates and exact commitment readback',async()=>{const key=new Uint8Array(32).fill(3),hash=`0x${await layerDigest(key)}`,root='0x'+'1'.repeat(64),cipher='0x'+'2'.repeat(64);const values={fulfilled:false,keyPublished:false,allocationReady:true,revealAt:10n,keyCommitment:hash,manifestDigest:root,ciphertextDigest:cipher};const client={getChainId:async()=>31337,getBlock:async()=>({number:3n,timestamp:20n}),getCode:async()=> '0x6000',readContract:async({functionName})=>values[functionName]};const input={key,address:'0x'+'1'.repeat(40),chainId:31337,runtimeCodeHash:keccak256('0x6000'),manifestDigest:root,ciphertextDigest:cipher};await assert.rejects(()=>prepareLayeredKeyRelease(client,input),/Wait for finalized/);values.fulfilled=true;const prepared=await prepareLayeredKeyRelease(client,input);assert.equal(prepared.data.length,74);assert.equal(prepared.sensitive,true);values.allocationReady=false;await assert.rejects(()=>prepareLayeredKeyRelease(client,input));values.allocationReady=true;values.keyCommitment=root;await assert.rejects(()=>prepareLayeredKeyRelease(client,input),/does not match/);});
test('public entry waits for per-token host; no generated plaintext source is persisted',()=>{const art=fixture();art.reveal={mode:'chainlink',encrypted:false,revealAt:1900000000};const html=layeredHTML(art);assert.ok(html.includes('Waiting for verified token'));assert.equal(html.includes("await window.keelRender({seed:manifest.seed,tokenId:'1'})"),false);const p=withLayeredPreview({layered:art,intent:{},presentation:{shell:'canonical'},runtimeModules:[],files:[]});assert.equal(p.files.length,0);assert.equal(p.runtimeModules[0].id,'keel-layered-runtime-v4');});
test('encrypted publication folder excludes source traits and images and never overwrites folders',async()=>{
 const {WorkspaceStore,newProject}=await import('../src/workspace.mjs');const {exportLayeredPackage}=await import('../src/layered-export.mjs');const {mkdtemp,readFile,readdir,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const path=await import('node:path');const folder=await mkdtemp(path.join(tmpdir(),'keel-layer-export-'));const store=new WorkspaceStore(':memory:');
 try{store.importObject(bytes,'Secret Original.png','image/png',0);const art=fixture();art.reveal={mode:'chainlink',encrypted:true,revealAt:1900000000};const project={...newProject('Private collection'),layered:art,objectIds:[id]};let snapshot=store.read();store.save({...snapshot.state,projects:[project]},snapshot.revision);const runtime=new URL('../../../packages/sdk/dist/layered-runtime.js',import.meta.url);const encryption={available:()=>true,encrypt:v=>Buffer.from(v)};
 const result=await exportLayeredPackage(store,project,folder,encryption,runtime);const plan=JSON.parse(await readFile(path.join(result.directory,'publication-plan.json'),'utf8'));assert.equal(plan.encrypted,true);assert.equal(plan.publicationReady,false);assert.equal(plan.reuse,undefined);assert.equal(plan.sample.counts,undefined);assert.deepEqual(await readdir(path.join(result.directory,'objects')),[plan.sealed.ciphertextDigest]);for(const name of ['index.html','publication-plan.json']){const text=await readFile(path.join(result.directory,name),'utf8');assert.equal(text.includes('Background'),false);assert.equal(text.includes(id),false);assert.equal(text.includes('Secret Original'),false);}
 const secret=JSON.parse(Buffer.from(store.db.prepare('SELECT encrypted FROM layered_secrets').get().encrypted).toString());const plaintext=await openLayeredBundle(plan.sealed,new Uint8Array(await readFile(path.join(result.directory,'objects',plan.sealed.ciphertextDigest))),Uint8Array.from(Buffer.from(secret.key,'hex')));assert.deepEqual(plaintext.manifest,art);assert.equal(JSON.stringify(store.read()).includes(secret.key),false);
 }finally{store.close();await rm(folder,{recursive:true,force:true});}
});
test('generated creator scripts parse, and changing to layers preserves user filenames',async()=>{const {Script}=await import('node:vm');for(const html of [layeredHTML(fixture()),layeredHTML(fixture(),{schema:'keel-layered-sealed@1',algorithm:'AES-256-GCM',iv:'0'.repeat(24),ciphertextDigest:'1'.repeat(64),keyCommitment:'2'.repeat(64),byteLength:20})])for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>new Script(match[1]));const files=[{name:'keel-layered.html',content:'My original file'}];assert.deepEqual(withLayeredPreview({layered:fixture(),intent:{},presentation:{},runtimeModules:[],files}).files,files);});
