/**
 * Generates the SDK's module registry from the manifests + deployment records.
 *
 * Consumers should never read the repo's filesystem, so everything the SDK needs
 * is emitted as one typed TypeScript module. Regenerate with `keel sync`.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { MODULES, TIER_OF } from "./module-map.mjs";

const REPO = resolve(import.meta.dirname, "../..");
const metaDir = (id) => join(REPO, "../keel-contracts", TIER_OF.get(id), id);
const TARGET = join(REPO, "packages/sdk/src/modules.generated.ts");
const ABI_DIR = join(REPO, "packages/sdk/src/abis");
const abiOnly = process.argv.find(arg => arg.startsWith("--abis-only="))?.slice("--abis-only=".length);
if (abiOnly && !MODULES.some(m => m.id === abiOnly)) throw new Error(`Unknown module: ${abiOnly}`);

const modules = [];
const deployments = [];
const abiIndex = [];   // [unitId, [contractName, ...]]
for (const m of MODULES) {
  if (abiOnly && m.id !== abiOnly) continue;
  const d = JSON.parse(readFileSync(join(metaDir(m.id), "keel.module.json"), "utf8"));
  modules.push({ id: d.id, kind: d.kind, title: d.title, group: d.group, visibility: d.visibility ?? null, summary: d.summary, version: d.version, repo: d.repo, deps: d.deps, contracts: d.contracts, deployable: d.deployable });
  // ABIs are ~1 MiB in total, so each unit gets its own module and is loaded on
  // demand rather than embedded in the registry every consumer imports.
  const abiSrc = join(metaDir(m.id), "abi");
  if (existsSync(abiSrc)) {
    const entries = readdirSync(abiSrc).filter((f) => f.endsWith(".json")).sort();
    if (entries.length) {
      mkdirSync(ABI_DIR, { recursive: true });
      const body = entries.map((f) => {
        const name = f.replace(/\.json$/, "");
        return `  ${JSON.stringify(name)}: ${JSON.stringify(JSON.parse(readFileSync(join(abiSrc, f), "utf8")))},`;
      }).join("\n");
      writeFileSync(join(ABI_DIR, `${m.id}.generated.ts`),
        `// GENERATED BY \`keel sync\` — DO NOT EDIT BY HAND.\n` +
        `/** ABIs for the ${m.id} ${d.kind}. */\n` +
        `export const ABIS = {\n${body}\n} as const;\n`);
      abiIndex.push([m.id, entries.map((f) => f.replace(/\.json$/, ""))]);
    }
  }

  const dir = join(metaDir(m.id), "deployments");
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir).filter((x) => x.endsWith(".json"))) {
    const rec = JSON.parse(readFileSync(join(dir, f), "utf8"));
    for (const [instance, slot] of Object.entries(rec.deployments ?? {})) {
      for (const c of Object.values(slot.contracts ?? {})) {
        deployments.push({ module: rec.module, chainId: rec.chainId, instance, contract: c.contract, address: c.address, block: c.block ?? null, txHash: c.txHash ?? null });
      }
    }
  }
}
if (abiOnly) { console.log(`sync-sdk: regenerated ABIs for ${abiOnly}`); process.exit(0); }
deployments.sort((a, b) => a.module.localeCompare(b.module) || a.chainId - b.chainId || a.instance.localeCompare(b.instance) || a.contract.localeCompare(b.contract));

const onlyModules = modules.filter((m) => m.kind !== "app");
const onlyApps = modules.filter((m) => m.kind === "app");
const ids = onlyModules.map((m) => `"${m.id}"`).join(" | ");
const appIds = onlyApps.map((m) => `"${m.id}"`).join(" | ");
const groups = [...new Set(modules.map((m) => m.group))].sort().map((g) => `"${g}"`).join(" | ");
const out = `// GENERATED BY \`keel sync\` — DO NOT EDIT BY HAND.
// Source: packages/contracts/modules/*/keel.module.json and */deployments/*.json

/** Reusable protocol infrastructure. Each module ships as its own repository. */
export type KeelModuleId = ${ids};

/**
 * Concrete products built on the modules. Apps consume modules exactly as an
 * outside integrator does, and no module may depend on one.
 */
export type KeelAppId = ${appIds};

/** Anything with contracts on a chain — a module or an app. */
export type KeelUnitId = KeelModuleId | KeelAppId;

/** Role labels units are grouped and browsed by. */
export type KeelModuleGroup = ${groups};

export interface KeelModule {
  readonly id: KeelUnitId;
  /** "module" is reusable infrastructure; "app" is a product built on it. */
  readonly kind: "module" | "app";
  readonly title: string;
  /** Role label; the topic this module's repository is tagged with. */
  readonly group: KeelModuleGroup;
  readonly summary: string;
  readonly version: string;
  /** Repository this module is published from once split out of the monorepo. */
  readonly repo: string | null;
  /** Repository visibility, when known. Affects installation, not resolution. */
  readonly visibility: "public" | "private" | null;
  readonly deps: readonly KeelUnitId[];
  readonly contracts: readonly string[];
  /** Contracts with creation bytecode — the ones a release actually deploys. */
  readonly deployable: readonly string[];
}

export interface KeelDeployment {
  readonly module: KeelUnitId;
  readonly chainId: number;
  /** Named instance: one chain can carry several deployments of a module. */
  readonly instance: string;
  readonly contract: string;
  readonly address: \`0x\${string}\`;
  readonly block: string | null;
  readonly txHash: string | null;
}

export const KEEL_MODULES: readonly KeelModule[] = ${JSON.stringify(onlyModules, null, 2)} as const;

/** Products built on the modules; excluded from the module registry by design. */
export const KEEL_APPS: readonly KeelModule[] = ${JSON.stringify(onlyApps, null, 2)} as const;

export const KEEL_DEPLOYMENTS: readonly KeelDeployment[] = ${JSON.stringify(deployments, null, 2)} as const;
`;
writeFileSync(TARGET, out);

// loader map: static import specifiers so bundlers can see every target
const loaderEntries = abiIndex.map(([id]) => `  ${JSON.stringify(id)}: () => import("./abis/${id}.generated.js"),`).join("\n");
const contractIndex = abiIndex.map(([id, names]) => `  ${JSON.stringify(id)}: ${JSON.stringify(names)},`).join("\n");
writeFileSync(join(REPO, "packages/sdk/src/abis.generated.ts"),
  `// GENERATED BY \`keel sync\` — DO NOT EDIT BY HAND.\n\n` +
  `/** Contracts with a recorded ABI, per unit. */\n` +
  `export const ABI_CONTRACTS: Readonly<Record<string, readonly string[]>> = {\n${contractIndex}\n};\n\n` +
  `/** Lazy loaders — each unit's ABIs are a separate chunk. */\n` +
  `export const ABI_LOADERS: Readonly<Record<string, () => Promise<{ ABIS: Record<string, unknown> }>>> = {\n${loaderEntries}\n};\n`);
console.log(`sync-sdk: ${abiIndex.reduce((n, [, c]) => n + c.length, 0)} ABIs, ${onlyModules.length} modules, ${onlyApps.length} apps, ${deployments.length} deployments -> packages/sdk/src/modules.generated.ts`);
