import React, { useEffect, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { api, queryClient } from './client';
import { Badge, Field } from './ui';
import type { EditorTarget, Workspace, Shared } from './types';

type AgentProps = {state:Workspace['state'];chatId?:string;select:(id:string)=>void;projectId?:string;compact?:boolean;openChats:()=>void;navigate:(target:EditorTarget)=>Promise<void>;beforeAction:()=>Promise<void>;search?:string};
const providers:Record<string,string>={codex:'Codex · local',claude:'Claude Code · local',openai:'OpenAI · API',anthropic:'Anthropic · API'};
const errorText=(error:unknown)=>error instanceof Error?error.message:String(error);
export const refreshChats = async(id?:string)=>{await Promise.all([queryClient.invalidateQueries({queryKey:['agent-chats']}),...(id?[queryClient.invalidateQueries({queryKey:['agent-chat',id]}),queryClient.invalidateQueries({queryKey:['agent-history',id]})]:[])]);};

function ActionCard({item,navigate,beforeAction,refresh}:{item:any;navigate:AgentProps['navigate'];beforeAction:AgentProps['beforeAction'];refresh:()=>Promise<void>}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const review=item.payload.review;
  async function apply(){
    setBusy(true);setError('');
    try{
      await beforeAction();
      const result=await api('applyAgentAction',{id:item.id,reviewed:true});
      if(result.navigate){await navigate(result.navigate);await api('agentNavigationResult',{id:item.id,ok:true});}
      await queryClient.invalidateQueries({queryKey:['workspace']});await refresh();
    }catch(error){setError(errorText(error));await refresh();}finally{setBusy(false);}
  }
  return <article className={`agent-action ${item.kind}`}><div className="agent-action-title"><span>{item.kind==='wallet-review'?'◈':item.kind==='navigate'?'↗':'◇'}</span><strong>{item.title}</strong><Badge>{item.status==='pending'?(item.kind==='navigate'?'OPEN IN EDITOR':'YOUR REVIEW'):item.status.replaceAll('-',' ')}</Badge></div>
    {item.kind==='project-edit'&&<details><summary>Review changes to {item.payload.next.title}</summary><div className="agent-diff"><div><h4>Saved work</h4><pre>{JSON.stringify({title:item.payload.previous.title,metadata:item.payload.previous.metadata,notes:item.payload.previous.notes,intent:item.payload.previous.intent,objects:item.payload.previous.objectIds},null,2)}</pre>{item.payload.previous.files.map((f:any)=><details key={f.id}><summary>{f.name}</summary><pre>{f.content}</pre></details>)}</div><div><h4>Suggested work</h4><pre>{JSON.stringify({title:item.payload.next.title,metadata:item.payload.next.metadata,notes:item.payload.next.notes,intent:item.payload.next.intent,objects:item.payload.next.objectIds},null,2)}</pre>{item.payload.next.files.map((f:any)=><details key={f.id}><summary>{f.name}</summary><pre>{f.content}</pre></details>)}</div></div></details>}
    {item.kind==='memory'&&<p>{item.payload.content}</p>}
    {item.kind==='track-contract'&&<><p>Chain {item.payload.chainId} · {item.payload.kind} · authority unverified</p><code>{item.payload.address}</code><details><summary>Contract and ABI controls</summary><pre>{JSON.stringify(item.payload,null,2)}</pre></details></>}
    {review&&<><dl className="agent-review-grid"><div><dt>Network</dt><dd>{review.chainId??(typeof review.network==='string'?review.network:review.network?.name??review.network?.type??'Tezos')}</dd></div><div><dt>From</dt><dd><code>{review.account??review.address??review.source}</code></dd></div><div><dt>To</dt><dd><code>{review.to??review.destination??review.operation?.destination}</code></dd></div><div><dt>Amount</dt><dd>{review.valueWei!==undefined?`${review.valueWei} wei`:`${review.operation?.amount??review.amountMutez??'Unavailable'} mutez`}</dd></div><div><dt>Estimated fee</dt><dd>{review.estimatedFeeWei!==undefined?`${review.estimatedFeeWei} wei`:JSON.stringify(review.estimate??review.fees??'See details')}</dd></div><div><dt>Expires</dt><dd>{new Date(review.expiresAt).toLocaleTimeString()}</dd></div></dl><details><summary>Exact call, fees & simulation</summary><pre>{JSON.stringify(review,null,2)}</pre></details></>}
    {item.result?.hash&&<p>Submitted: <code>{item.result.hash}</code></p>}
    {(error||item.error)&&<p role="alert" className="error-text">{error||item.error}</p>}
    {item.status==='pending'&&<div className="inline-actions"><button className="primary" disabled={busy} onClick={()=>void apply()}>{busy?'Working…':item.kind==='navigate'?'Open in editor':item.kind==='wallet-review'?'Review & approve in wallet':item.kind==='memory'?'Save memory':item.kind==='track-contract'?'Track contract':'Apply to project'}</button><button disabled={busy} onClick={()=>{setBusy(true);void api('dismissAgentAction',item.id).then(refresh).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}>Dismiss</button></div>}
    {item.kind==='wallet-review'&&item.status!=='pending'&&<button onClick={()=>void navigate({page:'Wallets'})}>Open wallet activity ↗</button>}
  </article>;
}

export function AgentWorkspace({state,chatId,select,projectId,compact=false,openChats,navigate,beforeAction,search=''}:AgentProps){
  const [archived,setArchived]=useState(false);const [offset,setOffset]=useState(0);const [creating,setCreating]=useState(false);const [error,setError]=useState('');const [settings,setSettings]=useState(false);
  const chats=useQuery({queryKey:['agent-chats',archived,search,offset],queryFn:()=>api('agentChats',{archived,search,offset})});
  const chat=useQuery({queryKey:['agent-chat',chatId],queryFn:()=>api('agentChat',chatId),enabled:!!chatId});
  const [before,setBefore]=useState<number>();
  const history=useQuery({queryKey:['agent-history',chatId,before],queryFn:()=>api('agentHistory',{id:chatId,before}),enabled:!!chatId,refetchInterval:query=>query.state.data?.runs.some((r:any)=>r.status==='running')?1200:false});
  const [prompt,setPrompt]=useState('');const draftValues=useRef(new Map<string,string>());
  const changePrompt=(value:string)=>{setPrompt(value);if(chatId){draftValues.current.set(chatId,value);queryClient.setQueryData(['agent-chat',chatId],(old:any)=>old?{...old,draft:value}:old);}};
  useEffect(()=>()=>{const draft=chatId?draftValues.current.get(chatId):undefined;if(chatId&&draft!==undefined)void api('updateAgentChat',{id:chatId,fields:{draft}}).catch(()=>{});},[chatId]);const [sending,setSending]=useState(false);const [context,setContext]=useState<any>();
  const draftLoaded=useRef<string | undefined>(undefined);const bottom=useRef<HTMLDivElement>(null);
  useEffect(()=>{setBefore(undefined);setContext(undefined);setError('');setPrompt('');draftLoaded.current=undefined;},[chatId]);
  useEffect(()=>{if(chat.data&&draftLoaded.current!==chat.data.id){setPrompt(chat.data.draft??'');draftLoaded.current=chat.data.id;}},[chat.data]);
  useEffect(()=>{if(!chatId||draftLoaded.current!==chatId||sending)return;const timer=setTimeout(()=>{void api('updateAgentChat',{id:chatId,fields:{draft:prompt}}).catch(e=>setError(errorText(e)));},400);return()=>clearTimeout(timer);},[prompt,chatId,sending]);
  const running=history.data?.runs.some((r:any)=>r.status==='running')??false;
  useEffect(()=>{if(running)bottom.current?.scrollIntoView({block:'nearest'});},[history.data?.runs.at(-1)?.reply,running]);
  useEffect(()=>{setOffset(0);},[search]);
  const activeProject=state.projects.find(p=>p.id===chat.data?.projectId);
  async function create(){setCreating(true);setError('');try{await beforeAction();const created=await api('createAgentChat',{projectId:projectId??null,provider:chat.data?.provider??'codex',model:chat.data?.model??''});select(created.id);setArchived(false);setOffset(0);await refreshChats(created.id);}catch(error){setError(errorText(error));}finally{setCreating(false);}}
  async function update(fields:any){setError('');try{await api('updateAgentChat',{id:chatId,fields});if(fields.contextMode!==undefined)setContext(undefined);await refreshChats(chatId);}catch(error){setError(errorText(error));}}
  async function send(event:React.FormEvent){
    event.preventDefault();if(!chatId||sending||running)return;setSending(true);setError('');
    try{await beforeAction();await api('startAgent',{id:chatId,prompt});changePrompt('');setBefore(undefined);await refreshChats(chatId);}catch(error){setError(errorText(error));}finally{setSending(false);}
  }
  const resetScroll=()=>{setBefore(undefined);};
  return <section className={`agent-workspace ${compact?'compact':''}`} aria-label="KEEL assistant workspace">
    {!compact&&<aside className="chat-list"><div className="chat-list-heading"><div><div className="eyebrow">YOUR CREATIVE ASSISTANT</div><h2>Conversations</h2></div><button aria-label="New chat" className="primary" disabled={creating} onClick={()=>void create()}>＋</button></div><div className="chat-filters"><button className={!archived?'selected':''} onClick={()=>{setArchived(false);setOffset(0);}}>Chats</button><button className={archived?'selected':''} onClick={()=>{setArchived(true);setOffset(0);}}>Archived</button><button aria-label="Manage memories" title="Manage memories" onClick={()=>void navigate({page:'Memory'})}>◷</button></div><div className="chat-list-items">{chats.data?.chats.map((item:any)=><button key={item.id} className={`chat-list-item ${chatId===item.id?'selected':''}`} onClick={()=>select(item.id)}><strong>{item.pinned?'⌑ ':''}{item.title}</strong><span>{item.running?'● Working':providers[item.provider]} · {state.projects.find(p=>p.id===item.projectId)?.title??'Workspace'}</span><small>{new Date(item.updatedAt).toLocaleDateString()}</small></button>)}{chats.data&&!chats.data.chats.length&&<p className="chat-list-empty">{archived?'Archived chats will appear here.':'Start a conversation about your next piece.'}</p>}</div>{chats.data?.total>100&&<div className="inline-actions"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous</button><span>{offset+1}–{Math.min(offset+100,chats.data.total)}</span><button disabled={offset+100>=chats.data.total} onClick={()=>setOffset(offset+100)}>Next</button></div>}</aside>}
    <div className="chat-work"><header className="chat-heading"><div><span className="eyebrow">✳ KEEL ASSISTANT</span><h2>{chat.data?.title??'Make something together.'}</h2>{chat.data&&<small>{activeProject?.title??'Workspace'} · {providers[chat.data.provider]}{running?' · Working…':''}</small>}</div><div className="inline-actions">{compact&&<button aria-label="All chats" onClick={openChats}>All chats ↗</button>}<button onClick={()=>void create()} disabled={creating}>New chat</button>{chat.data&&<button aria-label="Chat settings" aria-expanded={settings} onClick={()=>setSettings(!settings)}>•••</button>}</div></header>
      {settings&&chat.data&&<div className="chat-settings"><Field label="Chat name"><input aria-label="Chat name" defaultValue={chat.data.title} key={chatId} maxLength={160} onBlur={event=>{if(event.target.value.trim())void update({title:event.target.value});}} /></Field><div className="form-grid"><Field label="Connection"><select value={chat.data.provider} disabled={running} onChange={event=>void update({provider:event.target.value,model:''})}>{Object.entries(providers).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Model (optional for local apps)"><input aria-label="Agent model" value={chat.data.model} maxLength={160} disabled={running} onChange={event=>{queryClient.setQueryData(['agent-chat',chatId],{...chat.data,model:event.target.value});}} onBlur={event=>void update({model:event.target.value})} placeholder="Use local app default" /></Field><Field label="Project context"><select disabled={running||history.data?.runs.length>0} value={chat.data.projectId??''} onChange={event=>void update({projectId:event.target.value||null})}><option value="">Workspace</option>{state.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field></div><label className="checkbox"><input type="checkbox" aria-label="Use saved work in this chat" disabled={running} checked={chat.data.contextMode==='auto'} onChange={event=>void update({contextMode:event.target.checked?'auto':'none'})}/>Use saved projects, memories, and editor tools</label><label className="checkbox"><input type="checkbox" disabled={running} checked={chat.data.allowEdits} onChange={event=>void update({allowEdits:event.target.checked})}/>Allow new drafts and suggested edits</label><div className="inline-actions"><button onClick={()=>void update({pinned:!chat.data.pinned})}>{chat.data.pinned?'Unpin':'Pin chat'}</button><button disabled={running} onClick={()=>void update({archived:!chat.data.archived})}>{chat.data.archived?'Restore chat':'Archive chat'}</button><button onClick={()=>void navigate({page:'Connections'})}>Connection setup ↗</button></div></div>}
      {(error||chat.error||chats.error||history.error)&&<p role="alert" className="notice error">{error||chat.error?.message||chats.error?.message||history.error?.message}</p>}
      <div className="chat-transcript" aria-live="polite">{!chatId&&<div className="agent-welcome"><span className="welcome-mark">✳</span><h1>From the first idea<br/>to the final piece.</h1><p>Make artwork, understand your contracts, find modules, and prepare a release—with your work close at hand.</p><button className="primary" onClick={()=>void create()}>Start a chat ↗</button></div>}
        {chatId&&!history.data?.runs.length&&<div className="agent-welcome"><span className="welcome-mark">✳</span><h2>What would you like to make?</h2><p>{activeProject?`Let’s work on ${activeProject.title}.`:'Start with an idea, or ask about something in your workspace.'}</p><div className="agent-suggestions">{(activeProject?['Check this project and show me what needs work','Help improve the metadata for this piece','Find the modules this project needs','Walk me through releasing this work']:['Create a simple animated HTML artwork','Help me find my projects and contracts','Show me how KEEL storage and minting work']).map(text=><button key={text} onClick={()=>changePrompt(text)}>{text}<span>↗</span></button>)}</div></div>}
        {history.data?.nextBefore&&<button onClick={()=>setBefore(history.data.nextBefore)}>Earlier messages</button>}{before&&<button onClick={resetScroll}>Back to latest</button>}
        {history.data?.runs.map((run:any)=><article className="chat-turn" key={run.id}><div className="chat-user"><span>YOU</span><p>{run.prompt}</p></div><div className="chat-assistant"><div className="chat-speaker"><span>✳ KEEL</span><small>{run.status==='running'?'Working…':run.status==='completed'?providers[run.provider]:run.status}</small></div>{run.reply&&<div className="agent-markdown"><Markdown remarkPlugins={[remarkGfm]} components={{a:({children})=><span>{children}</span>,img:({alt})=><span>{alt??'Image reference'}</span>}}>{run.reply}</Markdown></div>}{run.error&&<p className="notice error">{run.error}</p>}{run.events?.length>0&&<details className="agent-tool-log"><summary>{run.events.filter((e:any)=>e.status==='completed').length} completed actions{run.status==='running'&&run.events.at(-1)?.status==='running'?` · ${run.events.at(-1).name.replace(/^keel_/,'').replaceAll('_',' ')}`:''}</summary>{run.events.filter((e:any)=>e.status!=='running').map((event:any,i:number)=><p key={i}><Badge>{event.status}</Badge> {event.name.replace(/^keel_/,'').replaceAll('_',' ')}{event.message&&` · ${event.message}`}</p>)}</details>}{run.actions?.map((item:any)=><ActionCard key={item.id} item={item} navigate={navigate} beforeAction={beforeAction} refresh={()=>refreshChats(chatId)} />)}{run.context&&<details className="agent-context-used"><summary>Context used · {run.context.parts.length} sources</summary>{run.context.parts.map((part:any,i:number)=><details key={i}><summary>{part.label} · {part.reason}{part.truncated?' · excerpt':''}</summary><pre>{part.text}</pre></details>)}</details>}</div></article>)}<div ref={bottom}/>
      </div>
      {chat.data&&!chat.data.archived&&<form className="chat-composer" onSubmit={send}><div className="composer-context"><span>{chat.data.contextMode==='auto'?`Context: ${activeProject?.title??'workspace'} + relevant memory`:'Saved work is off for this chat'}</span>{chat.data.contextMode==='none'&&<button type="button" disabled={running||sending} onClick={()=>void update({contextMode:'auto'})}>Use saved work</button>}<button type="button" onClick={()=>{setContext(undefined);void api('agentContext',{id:chatId,prompt}).then(setContext).catch(e=>setError(errorText(e)));}}>Inspect context</button></div>{chat.data.contextMode==='none'&&<p className="small">Enable saved work to let KEEL find your projects and memories and help in the editor.</p>}{context&&<details open className="composer-context-detail"><summary>{context.characters.toLocaleString()} context characters · {context.parts.length} sources</summary>{context.parts.map((part:any,i:number)=><details key={i}><summary>{part.label}</summary><pre>{part.text}</pre></details>)}</details>}<textarea aria-label="Message KEEL assistant" required maxLength={16000} rows={3} value={prompt} onChange={e=>changePrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(!running&&!sending&&prompt.trim())e.currentTarget.form?.requestSubmit();}}} placeholder={running?'Write your next message while KEEL works…':'Ask, create, or tell KEEL what to change…'}/><div className="composer-actions"><small>{['openai','anthropic'].includes(chat.data.provider)?'Uses your API connection':'Uses your local app sign-in'} · Shift + Enter for a new line</small>{running?<button type="button" onClick={()=>void api('stopAgent',chatId).then(()=>refreshChats(chatId)).catch(e=>setError(errorText(e)))}>Stop reply</button>:<button className="primary" disabled={sending||!prompt.trim()}>{sending?'Starting…':'Send ↗'}</button>}</div>{['openai','anthropic'].includes(chat.data.provider)&&!chat.data.model&&<p className="small">Choose your model in chat settings before sending. <button type="button" onClick={()=>setSettings(true)}>Choose model</button></p>}</form>}
      {chat.data?.archived&&<div className="chat-composer"><p>This chat is archived. Its messages and reviews are saved.</p><button className="primary" onClick={()=>void update({archived:false})}>Restore & continue</button></div>}
    </div>
  </section>;
}

export function AgentMemory({state,save,action}:Shared){
  const [editing,setEditing]=useState<any>();const [filter,setFilter]=useState('');
  const memory=state.memories as any[];
  return <><div className="page-heading compact"><div><div className="eyebrow">CONTINUITY, ON YOUR TERMS</div><h1>What KEEL remembers.</h1><p>Keep creative preferences and decisions across chats. Project notes stay with their project; enabled notes are selected when relevant.</p></div></div><div className="content-pad"><form className="memory-form" key={editing?.id??'new'} onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);void action(async()=>{const current=queryClient.getQueryData<Workspace>(['workspace'])!;const item={id:editing?.id??crypto.randomUUID(),title:String(data.get('title')),content:String(data.get('content')),projectId:String(data.get('project'))||undefined,enabled:true,pinned:data.get('pinned')==='on',source:'creator'};await save({...current.state,memories:[...current.state.memories.filter(m=>m.id!==item.id),item]});setEditing(undefined);form.reset();});}}><h2>{editing?'Edit a memory':'Remember something useful'}</h2><Field label="Title"><input name="title" defaultValue={editing?.title} required maxLength={160} placeholder="My preferred visual style"/></Field><Field label="Details"><textarea name="content" defaultValue={editing?.content} required maxLength={4000} rows={3} placeholder="Creative direction, preferences, or a decision worth keeping."/></Field><Field label="Use for"><select name="project" defaultValue={editing?.projectId??''}><option value="">Across my workspace</option>{state.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field><label className="checkbox"><input name="pinned" type="checkbox" defaultChecked={editing?.pinned}/>Always include when this context is shared</label><div className="inline-actions"><button className="primary">{editing?'Save changes':'Save memory'}</button>{editing&&<button type="button" onClick={()=>setEditing(undefined)}>Cancel</button>}</div></form><input aria-label="Search memories" className="search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Find a memory…"/>{memory.filter(m=>`${m.title} ${m.content}`.toLowerCase().includes(filter.toLowerCase())).map(m=><article key={m.id} className="memory-card"><div className="inline-actions"><h3>{m.title}</h3><Badge>{state.projects.find(p=>p.id===m.projectId)?.title??'Workspace'}</Badge><Badge>{m.enabled===false?'Paused':m.pinned?'Always included':'Relevant requests'}</Badge></div><p>{m.content}</p><div className="inline-actions"><button onClick={()=>setEditing(m)}>Edit</button><button onClick={()=>void action(()=>save({...state,memories:memory.map(item=>item.id===m.id?{...item,enabled:item.enabled===false}:item)}))}>{m.enabled===false?'Enable':'Pause'}</button><button onClick={()=>void action(()=>save({...state,memories:memory.filter(item=>item.id!==m.id)}))}>Forget</button></div></article>)}</div></>;
}
