import {renderLayeredAPNGFrames} from '@keel/sdk/layered-renderer';
import {LayerMath} from './layer-math';
import {DirectImageEditor} from './direct-image-editor';
import {LayerCurationEditor} from './layer-curation';
import { LayerExceptions } from './layer-exceptions';
import React, { useEffect, useRef, useState } from 'react';
import { resolveLayeredArt, newLayeredArt, defaultPlacement, checkLayeredArt, selectLayeredArt, sampleLayeredArt, parseLayeredArt, type LayeredArt, type LayerItem, type LayerPlacement, type Point, type Rule } from '@keel/sdk/layered-art';
import { renderLayeredArt, encodeLayeredCanvas, verifyLayeredAssets } from '@keel/sdk/layered-renderer';
import { layeredRevealPlan } from '@keel/sdk/layered-reveal';
import type { Project, Workspace, Shared } from './types';
import { api, queryClient } from './client';
import { Field } from './ui';
const uid=()=>crypto.randomUUID();
async function asset(id:string){const response=await fetch(`keel-asset://${id}/raw`);if(!response.ok)throw Error('Layer image is unavailable.');return {bytes:new Uint8Array(await response.arrayBuffer()),type:response.headers.get('content-type')??'image/png'};}
function Dial({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void}){return <Field label={label}><div className="layer-dial"><input aria-label={`${label} slider`} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={e=>{if(e.target.value&&e.target.validity.valid)onChange(Number(e.target.value));}}/></div></Field>;}
function Rules({attributes,value,change}:{attributes:LayeredArt['attributes'];value:Rule[];change:(v:Rule[])=>void}){return <><p>Show this only with, or without, an item from another attribute.</p>{value.map((rule,index)=><div className="layer-rule" key={index}><select aria-label="Rule mode" value={rule.mode} onChange={e=>change(value.map((r,i)=>i===index?{...r,mode:e.target.value as Rule['mode']}:r))}><option value="include">Only with</option><option value="exclude">Except with</option></select><select aria-label="Rule target" value={`${rule.attributeId}/${rule.itemIds[0]}`} onChange={e=>{const [attributeId,itemId]=e.target.value.split('/');change(value.map((r,i)=>i===index?{...r,attributeId,itemIds:[itemId]}:r));}}>{attributes.flatMap(a=>a.items.map(i=><option key={`${a.id}/${i.id}`} value={`${a.id}/${i.id}`}>{a.name} · {i.name}</option>))}</select><button aria-label="Remove rule" onClick={()=>change(value.filter((_,i)=>i!==index))}>×</button></div>)}<button disabled={!attributes.some(a=>a.items.length)} onClick={()=>{const a=attributes.find(a=>a.items.length)!;change([...value,{attributeId:a.id,itemIds:[a.items[0].id],mode:'include'}]);}}>Add condition</button></>;}
export function LayerEditor({project,state,change,action,save,release}:{project:Project;state:Workspace['state'];change:(p:Partial<Project>)=>void;action:Shared['action'];save:()=>Promise<any>;release:()=>Promise<void>}){
  const art=project.layered;const [attributeId,setAttribute]=useState(''),[itemId,setItem]=useState(''),[pieceId,setPiece]=useState('');
  const [variantPin,setVariantPin]=useState('');const [pngPreview,setPngPreview]=useState('');const [appliedRules,setAppliedRules]=useState<string[]>([]);const [previewPieces,setPreviewPieces]=useState<ReturnType<typeof resolveLayeredArt>['pieces']>([]);const mathArea=useRef<HTMLDivElement>(null);const exceptionArea=useRef<HTMLDivElement>(null);const curationArea=useRef<HTMLDivElement>(null);
  const [token,setToken]=useState('1'),[pinned,setPinned]=useState(false),[error,setError]=useState(''),[sample,setSample]=useState<any>(),[sheet,setSheet]=useState<string[]>([]),[notice,setNotice]=useState('');
  const [boundary,setBoundary]=useState<Point[]|null>(null);const [handle,setHandle]=useState<{kind:'mask'|'mesh';index:number}|null>(null);
  const canvas=useRef<HTMLCanvasElement>(null);const generation=useRef(0);const [rendered,setRendered]=useState(false);
  const attribute=art?.attributes.find(a=>a.id===attributeId)??art?.attributes[0];const item=attribute?.items.find(i=>i.id===itemId)??attribute?.items[0];const piece=item?.placements.find(p=>p.id===pieceId)??item?.placements[0];
  const update=(patch:Partial<LayeredArt>)=>{if(art){change({layered:{...art,...patch}});setSample(undefined);setSheet([]);}};
  const updateItem=(patch:Partial<LayerItem>)=>{if(art&&attribute&&item)update({attributes:art.attributes.map(a=>a.id===attribute.id?{...a,items:a.items.map(i=>i.id===item.id?{...i,...patch}:i)}:a)});};
  const updatePiece=(patch:Partial<LayerPlacement>)=>{if(item&&piece)updateItem({placements:item.placements.map(p=>p.id===piece.id?{...p,...patch}:p)});};
  useEffect(()=>{setVariantPin('');},[item?.id]);
  useEffect(()=>{setBoundary(null);setHandle(null);},[attribute?.id,item?.id,piece?.id]);
  useEffect(()=>{const current=++generation.current;setRendered(false);setPngPreview('');setAppliedRules([]);setPreviewPieces([]);setError('');if(!art||!canvas.current)return;const target=document.createElement('canvas');void (async()=>{try{if(!art.attributes.length)throw Error('Add your first attribute and image to see it here.');const selection=await selectLayeredArt(art,art.seed,token,pinned&&attribute&&item?{[attribute.id]:item.id}:{},pinned&&attribute&&variantPin?{[attribute.id]:variantPin}:{});await renderLayeredArt(target,art,selection,asset);if(generation.current!==current||!canvas.current)return;canvas.current.width=target.width;canvas.current.height=target.height;canvas.current.getContext('2d')!.drawImage(target,0,0);setPngPreview(target.toDataURL('image/png'));const resolved=resolveLayeredArt(art,selection);setAppliedRules(resolved.appliedRules.map(r=>r.id));setPreviewPieces(resolved.pieces);setRendered(true);}catch(e){if(generation.current===current)setError((e as Error).message);}})();return()=>{generation.current++;};},[art,token,pinned,attribute?.id,item?.id,variantPin]);
  if(!art)return <section className="setup-card"><h2>Build artwork from layers.</h2><p>Add attributes such as Background, Face and Hair. Each item can have its own images, rarity and drawing pieces.</p><button className="primary" onClick={()=>change({layered:newLayeredArt(project.title)})}>Start layering</button></section>;
  let issues:{level:string;message:string}[]=[];try{issues=checkLayeredArt(art,project.objectIds).issues;}catch(e){issues=[{level:'error',message:(e as Error).message}];}
  function reorderAttribute(direction:number){if(!attribute)return;const index=art!.attributes.indexOf(attribute),next=[...art!.attributes];if(index+direction<0||index+direction>=next.length)return;[next[index],next[index+direction]]=[next[index+direction],next[index]];try{parseLayeredArt({...art,attributes:next});update({attributes:next});}catch(e){setNotice((e as Error).message);}}
  const exceptionReferences=(targetAttribute:string,targetItem?:string)=>art.exceptions?.some(r=>r.conditions.some(c=>c.attributeId===targetAttribute&&(!targetItem||c.itemIds.includes(targetItem)))||r.actions.some(a=>a.attributeId===targetAttribute&&(!targetItem||a.itemId===targetItem)));
  const references=(targetAttribute:string,targetItem?:string)=>exceptionReferences(targetAttribute,targetItem)||art.attributes.some(a=>a.items.some(i=>[...i.rules,...i.placements.flatMap(p=>p.rules)].some(r=>r.attributeId===targetAttribute&&(!targetItem||r.itemIds.includes(targetItem)))));
  async function importImage(asVariant=false){const saved=await save();const result=await api('importObject',{revision:saved.revision});if(!result)return;queryClient.setQueryData(['workspace'],result);const object=result.state.objects.at(-1);if(!object.type.startsWith('image/'))throw Error('This file is saved in Files. Choose an image for this layer.');await prepareImage(object,asVariant,result.revision);}
  async function prepareImage(object:{id:string;name:string},asVariant=false,revision?:number){const saved=revision===undefined?await save():{revision};const result=await api('prepareLayerAsset',{objectId:object.id,revision:saved.revision});queryClient.setQueryData(['workspace'],result.workspace);setNotice(result.message);addImage(result.object,asVariant);}
  function addImage(object:{id:string;name:string},asVariant=false){if(!attribute)return;const name=object.name.replace(/\.[^.]+$/,'');const variant={id:uid(),name,objectId:object.id,weight:100};let items:LayerItem[];
    if(asVariant&&item)items=attribute.items.map(i=>i.id===item.id?{...i,variants:[...i.variants,variant]}:i);
    else {const next:LayerItem={id:uid(),name,weight:100,variants:[variant],placements:[defaultPlacement(uid(),art!.attributes.indexOf(attribute)*10)],rules:[],usage:{scope:'ask',renderer:'',license:'',tags:[]}};items=[...attribute.items,next];setItem(next.id);setPinned(true);}
    change({objectIds:[...new Set([...project.objectIds,object.id])],layered:{...art!,attributes:art!.attributes.map(a=>a.id===attribute.id?{...a,items}:a)}});
  }
  async function test(){await verifyLayeredAssets(art,asset);const value=await sampleLayeredArt(art,100,art!.seed);setSample(value);const images:string[]=[];for(let i=1;i<=12;i++){const c=document.createElement('canvas');const s=await selectLayeredArt(art,art!.seed,String(i));await renderLayeredArt(c,art,s,asset);const thumb=document.createElement('canvas');thumb.width=thumb.height=180;thumb.getContext('2d')!.drawImage(c,0,0,180,180);images.push(thumb.toDataURL());}setSheet(images);}
  function localPoint(event:React.PointerEvent<SVGSVGElement>):Point {const box=event.currentTarget.getBoundingClientRect();let x=((event.clientX-box.left)/box.width-piece!.x)/piece!.width-.5,y=((event.clientY-box.top)/box.height-piece!.y)/piece!.height-.5;const angle=-piece!.rotation*Math.PI/180;return [Math.max(-4,Math.min(4,x*Math.cos(angle)-y*Math.sin(angle)+.5)),Math.max(-4,Math.min(4,x*Math.sin(angle)+y*Math.cos(angle)+.5))];}
  const transform=piece?`translate(${piece.x*1000} ${piece.y*1000}) scale(${piece.width} ${piece.height}) rotate(${piece.rotation} 500 500)`:'';
  return <section className="layer-workbench"><div className="layer-top"><div><span className="eyebrow">1 · ATTRIBUTES  /  2 · ITEMS  /  3 · MAKE IT YOURS</span><h2>Your collection, piece by piece.</h2></div><div className="inline-actions"><button onClick={()=>mathArea.current?.scrollIntoView({behavior:"smooth",block:"start"})}>Math & probabilities</button><button onClick={()=>curationArea.current?.scrollIntoView({behavior:"smooth",block:"start"})}>Pool & set</button><button onClick={()=>exceptionArea.current?.scrollIntoView({behavior:'smooth',block:'start'})}>Combination rules · {art.exceptions?.length??0}</button><button className="primary" onClick={()=>void action(release)}>Choose collection →</button></div></div>
    <div className="layer-layout"><aside className="layer-library"><h3>Attributes</h3>{art.attributes.map(a=><button className={`layer-attribute ${a.id===attribute?.id?'selected':''}`} key={a.id} onClick={()=>{setAttribute(a.id);setItem('');}}><strong>{a.name||'Unnamed attribute'}</strong><small>{a.items.length} {a.items.length===1?'item':'items'}</small></button>)}<form onSubmit={e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('attribute') as HTMLInputElement;const a={id:uid(),name:input.value.trim(),items:[]};if(!a.name)return;update({attributes:[...art.attributes,a]});setAttribute(a.id);setItem('');input.value='';}}><input aria-label="New attribute" name="attribute" placeholder="e.g. Hair" maxLength={160} required/><button>Add attribute</button></form>
      {attribute&&<><div className="section-line"><h3>{attribute.name}</h3><span>{attribute.items.length} items</span></div><Field label="Attribute name"><input value={attribute.name} maxLength={160} onChange={e=>update({attributes:art.attributes.map(a=>a.id===attribute.id?{...a,name:e.target.value}:a)})}/></Field><details className="disclosure"><summary>Organize attribute</summary><div className="inline-actions"><button onClick={()=>reorderAttribute(-1)}>Earlier</button><button onClick={()=>reorderAttribute(1)}>Later</button><button disabled={references(attribute.id)} onClick={()=>update({attributes:art.attributes.filter(a=>a.id!==attribute.id)})}>Remove attribute</button></div>{references(attribute.id)&&<small>Remove conditions targeting this attribute before deleting it.</small>}</details><div className="layer-items">{attribute.items.map(i=><button className={`layer-item ${i.id===item?.id?'selected':''}`} key={i.id} onClick={()=>{setItem(i.id);setPiece('');setPinned(true);}}><img loading="lazy" decoding="async" src={`keel-asset://${i.variants[0]?.objectId}/raw`} alt=""/><span>{i.name}</span><small>{i.weight}</small></button>)}</div><button onClick={()=>void action(()=>importImage())}>＋ Add item image</button><details className="disclosure"><summary>Use a saved image</summary>{state.objects.filter(o=>o.type.startsWith('image/')).map(o=><button key={o.id} onClick={()=>void action(()=>prepareImage(o))}>{o.name}</button>)}</details></>}
    </aside><div className="layer-stage"><div className="layer-preview-controls"><Field label="Preview seed"><input value={art.seed} maxLength={128} onChange={e=>update({seed:e.target.value})}/></Field><Field label="Token"><input type="number" min="1" value={token} onChange={e=>{if(/^[1-9]\d{0,7}$/.test(e.target.value))setToken(e.target.value);}}/></Field><button onClick={()=>{setPinned(false);setToken(String(Number(token)+1));}}>Shuffle</button></div><label className="layer-pin"><input type="checkbox" checked={pinned} onChange={e=>setPinned(e.target.checked)}/> Show selected item · preview only</label>
      <div className="layer-canvas" onContextMenu={e=>{if(!pngPreview||!rendered||e.target instanceof HTMLImageElement)return;e.preventDefault();void action(()=>api('exportLayeredImage',{name:project.title+'-'+token,dataUrl:pngPreview}));}} style={{aspectRatio:`${art.width}/${art.height}`}}><canvas ref={canvas} style={{visibility:rendered||handle?'visible':'hidden'}}/>{pngPreview&&(rendered||handle)&&<img className="layer-png-preview" src={pngPreview} alt={project.title} draggable={false}/>}{piece&&(rendered||handle)&&pinned&&<svg viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="Layer boundary editor" onPointerDown={e=>{if(boundary){setBoundary([...boundary,localPoint(e)]);e.preventDefault();}}} onPointerMove={e=>{if(!handle)return;const p=localPoint(e);if(handle.kind==='mask')updatePiece({mask:piece.mask.map((v,i)=>i===handle.index?p:v)});else if(piece.mesh)updatePiece({mesh:{...piece.mesh,target:piece.mesh.target.map((v,i)=>i===handle.index?p:v)}});}} onPointerUp={()=>setHandle(null)} onPointerCancel={()=>setHandle(null)}><g transform={transform}><rect width="1000" height="1000" className="layer-outline"/>{(boundary??piece.mask).length>0&&<polygon points={(boundary??piece.mask).map(p=>p.map(n=>n*1000).join(',')).join(' ')} className="layer-boundary"/>}{(piece.mesh?.target??[]).length>0&&piece.mesh!.triangles.map((t,i)=><polygon key={i} points={t.map(n=>piece.mesh!.target[n].map(v=>v*1000).join(',')).join(' ')} className="layer-mesh"/>)}{!boundary&&(piece.mesh?piece.mesh.target:piece.mask).map((p,index)=><circle key={index} cx={p[0]*1000} cy={p[1]*1000} r="13" className="layer-handle" onPointerDown={e=>{e.stopPropagation();e.currentTarget.ownerSVGElement!.setPointerCapture(e.pointerId);setHandle({kind:piece.mesh?'mesh':'mask',index});}}/>)}</g></svg>}{!rendered&&<p className="layer-canvas-message">{error||'Add your first attribute and image to see it here.'}</p>}</div>
      {boundary&&<div className="notice">Click around the piece to draw its boundary. <button disabled={boundary.length<3} onClick={()=>{updatePiece({mask:boundary});setBoundary(null);}}>Finish boundary</button><button onClick={()=>setBoundary(null)}>Cancel</button></div>}
      <div className="inline-actions"><button disabled={!rendered} onClick={()=>void action(test)}>Test 100 combinations</button><button disabled={!rendered} onClick={()=>void action(async()=>{const blob=await encodeLayeredCanvas(canvas.current!,art);const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Image encoding failed.'));reader.readAsDataURL(blob);});const saved=await api('exportLayeredImage',{name:project.title+'-'+token,dataUrl});if(saved)setNotice('Image saved.');})}>Export this image</button></div>
      {sample&&<div className="notice" role="status">Checked {sample.count} seeds · {sample.failures.length} broken combinations · {sample.duplicates} duplicate combinations.<p>Weights are relative. Conditions affect final rarity. This sample does not guarantee unique tokens.</p><details><summary>Observed traits in this sample</summary>{art.attributes.map(a=><div key={a.id}><strong>{a.name}</strong>{a.items.map(i=><p key={i.id}>{i.name} · {sample.counts[`${a.id}/${i.id}`]??0} of {sample.count}</p>)}</div>)}</details>{sample.failures.slice(0,3).map((f:any)=><p key={f.tokenId}>{f.message}</p>)}</div>}{!!sheet.length&&<div className="layer-contact-sheet">{sheet.map((src,i)=><figure key={i}><img src={src} alt={`Sample token ${i+1}`}/><figcaption>#{i+1}</figcaption></figure>)}</div>}
    </div><aside className="layer-inspector">{item&&attribute?<><h3>{item.name}</h3><Field label="Item name"><input value={item.name} maxLength={160} onChange={e=>updateItem({name:e.target.value})}/></Field><Dial label="Rarity weight" value={item.weight} min={0} max={Math.max(1000,...attribute.items.map(i=>i.weight))} onChange={weight=>updateItem({weight})}/><small>{Math.round(item.weight/Math.max(1,attribute.items.reduce((s,i)=>s+i.weight,0))*10000)/100}% before conditions · 0 skips the random draw; a rule can still add it</small><details className="disclosure"><summary>Image variants · {item.variants.length}</summary>{item.variants.map(v=><div key={v.id}><button aria-pressed={variantPin===v.id} onClick={()=>{setPinned(true);setVariantPin(variantPin===v.id?'':v.id);}}>{variantPin===v.id?'Unpin variant':'Preview this variant'}</button><Field label="Variant name"><input value={v.name} onChange={e=>updateItem({variants:item.variants.map(x=>x.id===v.id?{...x,name:e.target.value}:x)})}/></Field><Dial label={`${v.name} weight`} value={v.weight} min={0} max={1000} onChange={weight=>updateItem({variants:item.variants.map(x=>x.id===v.id?{...x,weight}:x)})}/></div>)}<button onClick={()=>void action(()=>importImage(true))}>Add image variant</button></details>
      <button disabled={references(attribute.id,item.id)} onClick={()=>update({attributes:art.attributes.map(a=>a.id===attribute.id?{...a,items:a.items.filter(i=>i.id!==item.id)}:a)})}>Remove item</button><h3>Drawing pieces</h3><p>Use the same image in several places. Higher slots draw in front.</p><div className="layer-pieces">{item.placements.map(p=><button className={p.id===piece?.id?'selected':''} key={p.id} onClick={()=>setPiece(p.id)}>{p.name} · slot {p.slot}{rendered&&appliedRules.length>0&&(()=>{const visible=previewPieces.find(x=>x.attributeId===attribute.id&&x.itemId===item.id&&x.placement.id===p.id);return !visible?' · hidden here':visible.placement.slot!==p.slot?` → ${visible.placement.slot} here`:'';})()}</button>)}</div><button onClick={()=>{const p=defaultPlacement(uid(),(piece?.slot??0)+1);p.name=`Piece ${item.placements.length+1}`;updateItem({placements:[...item.placements,p]});setPiece(p.id);setPinned(true);}}>＋ Another piece of this image</button>
      {piece&&<><Field label="Piece name"><input value={piece.name} onChange={e=>updatePiece({name:e.target.value})}/></Field><Dial label="Layer slot" value={piece.slot} min={-1000} max={1000} onChange={slot=>updatePiece({slot})}/><div className="inline-actions"><button onClick={()=>{setPinned(true);setBoundary([]);}}>Draw boundary</button><button onClick={()=>updatePiece({mask:[]})}>Clear boundary</button></div><details className="disclosure"><summary>Position, size & mesh</summary>{(['x','y','width','height','rotation','opacity'] as const).map(key=><Dial key={key} label={key} value={piece[key]} min={key==='rotation'?-360:key==='width'||key==='height'?.01:key==='opacity'?0:-2} max={key==='rotation'?360:key==='opacity'?1:2} step={key==='rotation'?1:.01} onChange={v=>updatePiece({[key]:v})}/>)}<button onClick={()=>{setPinned(true);updatePiece({mesh:{source:[[0,0],[1,0],[1,1],[0,1]],target:[[0,0],[1,0],[1,1],[0,1]],triangles:[[0,1,2],[0,2,3]]}});}}>Add four-corner mesh</button><button onClick={()=>updatePiece({mesh:null})}>Remove mesh</button><p>Drag the points on the preview. Meshes reshape the image; boundaries clip the result.</p></details><details className="disclosure"><summary>When this piece appears</summary><Rules attributes={art.attributes} value={piece.rules} change={rules=>updatePiece({rules})}/></details>{item.placements.length>1&&<button disabled={art.exceptions?.some(r=>r.actions.some(a=>(a.kind==='move'||a.kind==='hide')&&a.attributeId===attribute.id&&a.itemId===item.id&&a.placementId===piece.id))} onClick={()=>updateItem({placements:item.placements.filter(p=>p.id!==piece.id)})}>Remove this piece</button>}</>}
      <details className="disclosure"><summary>Compatible items</summary><Rules attributes={art.attributes.slice(0,art.attributes.indexOf(attribute))} value={item.rules} change={rules=>updateItem({rules})}/><p>Conditions follow attribute order, so selections stay predictable.</p></details><details className="disclosure" open={item.usage.scope==='ask'}><summary>Who can reuse this layer?</summary><select aria-label="Layer reuse" value={item.usage.scope} onChange={e=>updateItem({usage:{...item.usage,scope:e.target.value as any,renderer:e.target.value==='renderer'?project.id:item.usage.renderer}})}><option value="ask">Choose permission…</option><option value="renderer">My renderer only</option><option value="public">Let others reuse it</option></select>{item.usage.scope==='public'&&<Field label="Reuse terms"><input placeholder="e.g. CC0 or your license URL" value={item.usage.license} onChange={e=>updateItem({usage:{...item.usage,license:e.target.value}})}/></Field>}<Field label="Tags"><input placeholder="hair, pixel, blue" key={item.id} defaultValue={item.usage.tags.join(', ')} onBlur={e=>updateItem({usage:{...item.usage,tags:e.target.value.split(',').map(v=>v.trim()).filter(Boolean).slice(0,20)}})}/></Field><small>Permission describes allowed reuse. Public image bytes can still be copied.</small></details></>:<p>Add an attribute, then an image. Its controls will appear here.</p>}</aside></div>
    <div ref={exceptionArea}><LayerExceptions art={art} change={exceptions=>update({exceptions})} applied={appliedRules}/></div>
    <div ref={mathArea}><LayerMath art={art} change={layered=>change({layered})} inspect={id=>{setAttribute(id);setItem('');document.querySelector('.layer-top')?.scrollIntoView({behavior:'smooth'});}}/></div>
    <div ref={curationArea}><LayerCurationEditor projectId={project.id} save={save} art={art} value={project.layerCuration} change={layerCuration=>change({layerCuration})} asset={asset} action={action} capture={{seed:art.seed,tokenId:token,overrides:pinned&&attribute&&item?{[attribute.id]:item.id}:{},variantOverrides:pinned&&attribute&&variantPin?{[attribute.id]:variantPin}:{}}}/></div>
    {notice&&<p className="notice" role="status">{notice}</p>}<div className="layer-settings"><DirectImageEditor apngFrames={async()=>{const version=generation.current;const selection=await selectLayeredArt(art,art.seed,token,pinned&&attribute&&item?{[attribute.id]:item.id}:{},pinned&&attribute&&variantPin?{[attribute.id]:variantPin}:{});const frames=await renderLayeredAPNGFrames(art,selection,asset);if(version!==generation.current)throw Error('The preview changed. Prepare it again.');return frames;}} previewPNG={pngPreview} project={project} change={change} save={save} action={action} ready={rendered} notice={setNotice} capture={{tokenId:token,overrides:pinned&&attribute&&item?{[attribute.id]:item.id}:{},variantOverrides:pinned&&attribute&&variantPin?{[attribute.id]:variantPin}:{}}}/><details className="disclosure"><summary>Image format & canvas</summary><Field label="Output format"><select value={art.format} onChange={e=>update({format:e.target.value as any,...(e.target.value==='image/jpeg'&&!art.background?{background:'#ffffff'}:{})})}><option value="image/png">PNG · transparency</option><option value="image/webp">WebP · optional</option><option value="image/jpeg">JPEG · solid background</option></select></Field><div className="inline-actions">{[512,1024,2048].map(size=><button key={size} onClick={()=>update({width:size,height:size})}>{size} × {size}</button>)}</div><Dial label="Width" value={art.width} min={16} max={8192} onChange={width=>update({width})}/><Dial label="Height" value={art.height} min={16} max={8192} onChange={height=>update({height})}/>{art.format!=='image/png'&&<Dial label="Image quality" value={art.quality} min={.1} max={1} step={.01} onChange={quality=>update({quality})}/>}<Field label="Background"><input type="color" value={art.background||'#ffffff'} onChange={e=>update({background:e.target.value})}/></Field>{art.format!=='image/jpeg'&&<button onClick={()=>update({background:''})}>Use transparency</button>}</details>
    <details className="disclosure"><summary>Reveal & encrypted layers</summary><Field label="Reveal method"><select value={art.reveal.mode} onChange={e=>update({reveal:{...art.reveal,mode:e.target.value as any,encrypted:e.target.value==='visible'?false:art.reveal.encrypted}})}><option value="visible">Visible from the start</option><option value="creator">Creator reveal · committed seed</option><option value="future-block">Future block · one fixed draw</option><option value="chainlink">Chainlink VRF · verified randomness</option></select></Field>{art.reveal.mode!=='visible'&&<><label><input type="checkbox" checked={art.reveal.encrypted} onChange={e=>update({reveal:{...art.reveal,encrypted:e.target.checked}})}/> Encrypt images and trait names until reveal</label><Field label="Earliest reveal"><input type="datetime-local" value={art.reveal.revealAt?new Date(art.reveal.revealAt*1000-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>{const time=new Date(e.target.value).getTime();if(Number.isFinite(time))update({reveal:{...art.reveal,revealAt:Math.floor(time/1000)}});}}/></Field><p>{art.reveal.mode==='chainlink'?'VRF verifies randomness. Freeze the artwork and token allocation before requesting it. The creator can still leak or withhold an encryption key.':art.reveal.mode==='future-block'?'Like the future-block approach in Pixel Marine, with a single fixed draw. This module has no expiry reroll; missing its settlement window stalls the reveal.':'The creator chooses the committed seed and can withhold its reveal.'}</p><details><summary>Setup checklist</summary><ul>{layeredRevealPlan(art).required.map(s=><li key={s}>{s}</li>)}</ul></details></>}</details>
    <details className="disclosure"><summary>Prepare for KEEL</summary><p>The layer images are stored once and the renderer is a reusable module. This prepares files locally; selected-network module bindings and collection permissions still need verification before your wallet signs.</p>{issues.map((i,n)=><p key={n}>{i.message}</p>)}<button disabled={issues.length>0} onClick={()=>void action(async()=>{await verifyLayeredAssets(art,asset);await save();const result=await api('exportLayeredPackage',project.id);if(result)setNotice(result.message);})}>Prepare publication folder</button>{art.reveal.encrypted&&<button onClick={()=>void action(async()=>{const result=await api('exportLayeredRecovery',project.id);if(result)setNotice('Private recovery key saved separately. Keep it private until the verified reveal gate is ready.');})}>Back up private reveal key</button>}</details></div>
  </section>;
}
