import React,{useEffect,useRef,useState} from 'react';
import {newLayerCuration,addLayerCandidate,assignLayerCandidate,removeLayerCandidateFromSet,resolveLayerCandidate,layerCurationStats,type LayerCuration,type LayerCandidate} from '@keel/sdk/layered-curation';
import {renderLayeredArt,type LayerAsset} from '@keel/sdk/layered-renderer';
import type {LayeredArt} from '@keel/sdk/layered-art';
import type {Shared} from './types';
import {Field} from './ui';
import {api} from './client';
// Thumbnails share a queue to bound simultaneous image decoding and canvas allocation.
let thumbnailQueue:Promise<unknown>=Promise.resolve();
function CandidateCard({candidate,state,asset,selected,position,onAssign,onRemove,onBefore}:{candidate:LayerCandidate;state:LayerCuration;asset:(id:string)=>Promise<LayerAsset>;selected:boolean;position?:number;onAssign:()=>void;onRemove:()=>void;onBefore:(id:string)=>void}){
 const [image,setImage]=useState(''),[error,setError]=useState('');const host=useRef<HTMLElement>(null);
 useEffect(()=>{let alive=true,started=false;const observer=new IntersectionObserver(entries=>{if(started||!entries.some(e=>e.isIntersecting))return;started=true;thumbnailQueue=thumbnailQueue.catch(()=>{}).then(async()=>{if(!alive)return;try{const r=await resolveLayerCandidate(state,candidate.id),canvas=document.createElement('canvas');const scale=Math.max(16/Math.min(r.manifest.width,r.manifest.height),Math.min(1,180/Math.max(r.manifest.width,r.manifest.height)));await renderLayeredArt(canvas,{...r.manifest,width:Math.max(16,Math.round(r.manifest.width*scale)),height:Math.max(16,Math.round(r.manifest.height*scale))},r.baseSelections,asset);if(alive)setImage(canvas.toDataURL('image/png'));}catch(e){if(alive)setError((e as Error).message);}});});if(host.current)observer.observe(host.current);return()=>{alive=false;observer.disconnect();};},[candidate.id]);
 return <article ref={host} className="curation-card" draggable onDragStart={e=>e.dataTransfer.setData('application/x-keel-candidate',candidate.id)} onDragOver={e=>{if(selected)e.preventDefault();}} onDrop={e=>{if(!selected)return;e.preventDefault();e.stopPropagation();const id=e.dataTransfer.getData('application/x-keel-candidate');if(id)onBefore(id);}}>
 {image?<img src={image} alt={`Candidate ${candidate.tokenId}`} draggable={false}/>:<div className="curation-thumb">{error||'Preparing preview…'}</div>}
 <strong>{position!==undefined?`#${position+1} · `:''}{candidate.origin==='curated'?'Chosen traits':'Generated'} {candidate.tokenId}</strong><small>Seed {candidate.seed}</small>
 <button onClick={selected?onRemove:onAssign}>{selected?'Return to pool':'Add to set'}</button></article>;
}
export function LayerCurationEditor({art,value,change,asset,action,capture,projectId,save}:{projectId:string;save:()=>Promise<unknown>;art:LayeredArt;value?:LayerCuration;change:(v:LayerCuration)=>void;asset:(id:string)=>Promise<LayerAsset>;action:Shared['action'];capture:{seed:string;tokenId:string;overrides:Record<string,string>;variantOverrides:Record<string,string>}}){
 const state=value??newLayerCuration(),[batch,setBatch]=useState(12),[seed,setSeed]=useState(art.seed),[stats,setStats]=useState<Awaited<ReturnType<typeof layerCurationStats>>|null>(null),[poolStats,setPoolStats]=useState<Awaited<ReturnType<typeof layerCurationStats>>|null>(null),[pins,setPins]=useState<Record<string,string>>({}),[notice,setNotice]=useState(''),[page,setPoolPage]=useState(0),[setPage,setSetPage]=useState(0);
 useEffect(()=>{setStats(null);setPoolStats(null);},[value]);
 const pool=state.candidates.filter(c=>!state.set.includes(c.id));
 useEffect(()=>{setPoolPage(p=>Math.min(p,Math.max(0,Math.ceil(pool.length/12)-1)));setSetPage(p=>Math.min(p,Math.max(0,Math.ceil(state.set.length/12)-1)));},[pool.length,state.set.length]);
 async function generate(manual=false,preview=false){let next=state,added=0;const failures:string[]=[];for(let i=0;i<(manual?1:batch);i++){try{const tokenId=preview?capture.tokenId:String(state.candidates.length+i+1);const r=await addLayerCandidate(next,art,{seed:preview?capture.seed:seed,tokenId,overrides:manual?(preview?capture.overrides:pins):{},variantOverrides:preview?capture.variantOverrides:{},origin:manual?'curated':'generated'});next=r.state;if(r.added)added++;}catch(e){failures.push((e as Error).message);}}change(next);setNotice(`${added} ${added===1?'candidate':'candidates'} added.${failures.length?' '+failures.length+' could not be generated: '+failures[0]:''}`);}
 const assign=(id:string,index?:number)=>change(assignLayerCandidate(state,id,index));
 const remove=(id:string)=>change(removeLayerCandidateFromSet(state,id));
 const card=(id:string,position?:number)=><CandidateCard key={id} candidate={state.candidates.find(c=>c.id===id)!} state={state} asset={asset} selected={position!==undefined} position={position} onAssign={()=>void action(async()=>assign(id))} onRemove={()=>remove(id)} onBefore={other=>void action(async()=>assign(other,position))}/>;
 return <section className="layer-curation" aria-label="Candidate pool and collection set"><div className="section-line"><div><h3>Generate. Pick. Build your set.</h3><p>Keep candidates in a pool, then drag your favourites into the collection.</p></div><span>{state.candidates.length} saved candidates</span></div>
 <div className="curation-controls"><Field label="Collection approach"><select value={state.mode} onChange={e=>change({...state,mode:e.target.value as LayerCuration['mode']})}><option value="curated">Curate the complete set</option><option value="mixed">Curated pieces + mint-time generation</option><option value="seeded">Generate from the mint seed</option></select></Field><Field label="Collection size"><input type="number" min={Math.max(1,state.set.length,...state.targets.map(t=>t.count))} max={100000} value={state.supply} onChange={e=>{if(e.target.value&&e.target.validity.valid)change({...state,supply:Number(e.target.value)});}}/></Field><Field label="Batch seed"><input value={seed} maxLength={128} onChange={e=>setSeed(e.target.value)}/></Field><Field label="How many"><input type="number" min={1} max={50} value={batch} onChange={e=>{if(e.target.value&&e.target.validity.valid)setBatch(Number(e.target.value));}}/></Field><button className="primary" disabled={!art.attributes.length||state.candidates.length+batch>5000} onClick={()=>void action(()=>generate())}>Generate candidates</button><button disabled={!art.attributes.length||state.candidates.length>=5000} onClick={()=>void action(()=>generate(true,true))}>Keep this preview</button></div>
 {state.mode!=='curated'&&<p className="notice">Mint-time generation is a saved plan. Contract seed/allocation integration must be verified before release. Pool experiments do not assign live tokens.</p>}
 <details className="disclosure"><summary>Choose traits for one candidate</summary><div className="curation-controls">{art.attributes.map(a=><Field key={a.id} label={a.name}><select value={pins[a.id]??''} onChange={e=>setPins(current=>{const next={...current};if(e.target.value)next[a.id]=e.target.value;else delete next[a.id];return next;})}><option value="">Let the generator choose</option>{a.items.filter(i=>i.weight>0).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></Field>)}</div><button disabled={!art.attributes.length||state.candidates.length>=5000} onClick={()=>void action(()=>generate(true))}>Add this combination to pool</button><p>Your exceptions and compatibility rules still apply.</p></details>
 {notice&&<p role="status">{notice}</p>}
 <div className="curation-columns"><div><h4>Candidate pool · {pool.length}</h4><div className="curation-grid">{pool.slice(page*12,page*12+12).map(c=>card(c.id))}</div>{!pool.length&&<p>Generate candidates or keep the current preview.</p>}<div className="inline-actions"><button disabled={!page} onClick={()=>setPoolPage(page-1)}>Previous candidates</button><button disabled={(page+1)*12>=pool.length} onClick={()=>setPoolPage(page+1)}>More candidates</button></div></div>
 <div className="curation-set" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-keel-candidate');if(id)void action(async()=>assign(id));}}><h4>Your set · {state.set.length} / {state.supply}</h4><p>Drop here to add. Drop on a card to place it before that piece.</p><div className="curation-grid">{state.set.slice(setPage*12,setPage*12+12).map((id,i)=>card(id,setPage*12+i))}</div><div className="inline-actions"><button disabled={!setPage} onClick={()=>setSetPage(setPage-1)}>Previous pieces</button><button disabled={(setPage+1)*12>=state.set.length} onClick={()=>setSetPage(setPage+1)}>More pieces</button></div></div></div>
 <details className="disclosure"><summary>Rarity targets & counts</summary><p>Generation weights live on each item above. Targets describe the set you want to curate; they do not silently change saved pieces.</p><div className="inline-actions"><button onClick={()=>void action(async()=>{setStats(await layerCurationStats(state));setPoolStats(await layerCurationStats(state,pool.map(c=>c.id)));})}>Check pool and set rarity</button></div>
 <div className="curation-rarity">{art.attributes.map(a=><div key={a.id}><h4>{a.name}</h4>{a.items.map(i=>{const target=state.targets.find(t=>t.attributeId===a.id&&t.itemId===i.id);return <div className="curation-rarity-row" key={i.id}><span>{i.name}</span><small>Pool {poolStats?.counts[a.id+'/'+i.id]??'—'} · Set {stats?.counts[a.id+'/'+i.id]??'—'}</small><input aria-label={`${a.name} ${i.name} target count`} type="number" min={0} max={state.supply} placeholder="Target" value={target?.count??''} onChange={e=>{if(!e.target.validity.valid)return;const targets=state.targets.filter(t=>!(t.attributeId===a.id&&t.itemId===i.id));if(e.target.value)targets.push({attributeId:a.id,itemId:i.id,count:Number(e.target.value)});change({...state,targets});}}/></div>;})}</div>)}</div>
 {stats&&<p role="status">Set: {stats.duplicates} repeated compositions · {stats.failures.length} broken candidates. {stats.targets.filter(t=>t.remaining!==0).length} targets still differ.</p>}</details>
 <button disabled={!state.set.length} onClick={()=>void action(async()=>{await save();const result=await api('exportLayerCuration',projectId);if(result)setNotice('Private set plan saved, including original seeds, traits and generator versions.');})}>Export private set plan</button>
 <small>Saved candidates keep their generator version, seed and chosen traits. Editing layers or weights only affects new candidates. Set positions are local until collection allocation is finalized.</small>
 </section>;
}
