import React,{useRef,useState} from 'react';
import {analyzeLayeredMath} from '@keel/sdk/layered-math';
import type {LayeredArt} from '@keel/sdk/layered-art';
type Report=Awaited<ReturnType<typeof analyzeLayeredMath>>;
export function LayerMath({art,change,inspect}:{art:LayeredArt;change:(art:LayeredArt)=>void;inspect:(id:string)=>void}){
  const [selected,setSelected]=useState(art.attributes[0]?.id??''),[count,setCount]=useState(250),[report,setReport]=useState<Report>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const measured=useRef<LayeredArt | undefined>(undefined),current=useRef(art);current.current=art;
  const attribute=art.attributes.find(a=>a.id===selected)??art.attributes[0],fresh=measured.current===art;
  const edges=art.attributes.flatMap(a=>a.items.flatMap(i=>i.rules.map(r=>({from:r.attributeId,to:a.id,mode:r.mode}))));
  const width=Math.max(680,art.attributes.length*160),x=(id:string)=>80+art.attributes.findIndex(a=>a.id===id)*160;
  async function measure(){const snapshot=art;setBusy(true);setError('');try{const next=await analyzeLayeredMath(snapshot,count);if(current.current===snapshot){measured.current=snapshot;setReport(next);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function weight(id:string,value:number){if(!Number.isSafeInteger(value)||value<0||value>1000000000)return;change({...art,attributes:art.attributes.map(a=>a.id===attribute?.id?{...a,items:a.items.map(i=>i.id===id?{...i,weight:value}:i)}:a)});}
  return <section className="layer-math" aria-label="Generator math"><div className="section-line"><div><span className="eyebrow">GENERATOR MATH</span><h3>See what shapes your collection.</h3></div><div className="inline-actions"><select aria-label="Math sample size" value={count} onChange={e=>setCount(Number(e.target.value))}>{[100,250,1000].map(n=><option key={n} value={n}>{n} test draws</option>)}</select><button disabled={busy||!attribute} onClick={()=>void measure()}>{busy?'Testing draws…':'Test probabilities'}</button></div></div>
    <p>Follow the choices from left to right. Curved lines show compatibility rules. Select an attribute to tune its weights; a larger weight makes an item more common.</p>
    <div className="math-flow"><svg width={width} height="190" role="img" aria-label="Attribute order and compatibility connections"><title>Selection order with compatibility connections</title>{art.attributes.slice(1).map((a,i)=><path key={a.id} d={`M ${x(art.attributes[i].id)+64} 145 H ${x(a.id)-64}`} stroke="currentColor" fill="none"/>)}{[...new Set(edges.map(e=>`${e.from}/${e.to}`))].map(key=>{const [from,to]=key.split('/');return <path key={key} d={`M ${x(from)} 116 Q ${(x(from)+x(to))/2} ${Math.max(8,100-Math.abs(x(to)-x(from))/5)} ${x(to)} 116`} stroke="var(--accent, #9391ff)" strokeOpacity=".55" fill="none"/>;})}{art.attributes.map(a=><g key={a.id} role="button" tabIndex={0} aria-label={`Tune ${a.name}`} onClick={()=>setSelected(a.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(a.id);}}}><rect x={x(a.id)-67} y="116" width="134" height="58" rx="8" fill={attribute?.id===a.id?'#343257':'#16191f'} stroke="#77758e"/><text x={x(a.id)} y="140" textAnchor="middle" fill="#f3f1ff">{a.name}</text><text x={x(a.id)} y="160" textAnchor="middle" fill="#b9b8c8" fontSize="11">{a.items.length} items · {edges.filter(e=>e.to===a.id).length} rules</text></g>)}</svg></div>
    {attribute&&<><div className="section-line"><h3>{attribute.name}</h3><button onClick={()=>inspect(attribute.id)}>Edit images & conditions →</button></div><div className="math-legend"><span>Lavender: before conditions</span><span>Mint: observed in test draws</span></div><div className="math-items">{attribute.items.map(i=>{const total=attribute.items.reduce((s,v)=>s+v.weight,0),base=total?i.weight/total:0,observed=fresh?report?.attributes.find(a=>a.id===attribute.id)?.items.find(v=>v.id===i.id):undefined;return <div className="math-item" key={i.id}><div><strong>{i.name}</strong><small>{i.rules.length?`${i.rules.length} conditions`:'Unconditional'}{i.weight===0?' · random draw off':''}</small></div><div className="math-bars"><div style={{width:`${base*100}%`}}/><div style={{width:`${(observed?.observedFraction??0)*100}%`}}/></div><span>{(base*100).toFixed(1)}% / {observed?.observedFraction==null?'—':`${(observed.observedFraction*100).toFixed(1)}%`}</span><input aria-label={`${attribute.name} ${i.name} math weight`} type="number" min="0" max="1000000000" step="1" value={i.weight} onChange={e=>{if(e.target.value)weight(i.id,Number(e.target.value));}}/></div>;})}</div></>}
    {error&&<p role="alert">{error}</p>}{report&&<p role="status">{fresh?`${report.successful}/${report.count} successful draws · ${report.duplicates} repeated artworks · ${report.failures.length} failed draws.`:'Settings changed. Test again to update the observed graph.'}</p>}{fresh&&!!report?.failures.length&&<details><summary>Inspect failed draws</summary>{report.failures.slice(0,20).map(f=><p key={f.tokenId}>Draw {f.tokenId}: {f.message}</p>)}</details>}
    <small>These are sample results, not guaranteed edition counts. Rules can change the odds; items added by rules can push observed totals above 100%. Changing weights affects future generations. Pieces already saved in your pool keep their original settings.</small>
  </section>;
}
