import React from 'react';
import type { LayeredArt, LayerException, LayerExceptionAction, Rule } from '@keel/sdk/layered-art';
import { Field } from './ui';

export function LayerExceptions({art,change,applied}:{art:LayeredArt;change:(rules:LayerException[])=>void;applied:string[]}) {
  const rules=art.exceptions??[];
  const choices=art.attributes.flatMap(a=>a.items.map(i=>({value:`${a.id}/${i.id}`,label:`${a.name} · ${i.name}`,a,i})));
  const first=choices[0];
  const patch=(id:string,value:Partial<LayerException>)=>change(rules.map(r=>r.id===id?{...r,...value}:r));
  const targetOptions=choices.map(c=><option key={c.value} value={c.value}>{c.label}</option>);
  function actionFor(kind:LayerExceptionAction['kind'],target=first?.value):LayerExceptionAction {
    const c=choices.find(c=>c.value===target)??first;
    return kind==='include'||kind==='replace'?{kind,attributeId:c.a.id,itemId:c.i.id,variantId:c.i.variants.find(v=>v.weight>0)?.id??c.i.variants[0]?.id??''}:kind==='move'?{kind,attributeId:c.a.id,itemId:c.i.id,slot:3}:{kind,attributeId:c.a.id,itemId:c.i.id};
  }
  return <section className="layer-exceptions" aria-label="Exceptions and inclusions">
    <div className="section-line"><div><h3>Exceptions & inclusions</h3><p>When these items meet, change how the artwork comes together.</p></div><button disabled={!first||rules.length>=128} onClick={()=>change([...rules,{id:crypto.randomUUID(),name:`Combination ${rules.length+1}`,enabled:true,match:'all',conditions:[{attributeId:first.a.id,itemIds:[first.i.id],mode:'include'}],actions:[actionFor('move')]}])}>＋ Add combination rule</button></div>
    {!rules.length&&<p className="muted">For example: when a helmet and long hair appear together, move the back hair behind the body, add a visor, or hide the hat.</p>}
    {rules.map(rule=><article className="layer-exception-card" key={rule.id}>
      <div className="layer-exception-heading"><input aria-label="Combination name" value={rule.name} maxLength={160} onChange={e=>patch(rule.id,{name:e.target.value})}/><label><input type="checkbox" checked={rule.enabled} onChange={e=>patch(rule.id,{enabled:e.target.checked})}/> Enabled</label><span role="status">{applied.includes(rule.id)?'Applied in this preview':rule.enabled?'Not matched in this preview':'Paused'}</span><button aria-label={`Delete ${rule.name}`} onClick={()=>change(rules.filter(r=>r.id!==rule.id))}>Delete</button></div>
      <div className="layer-exception-flow"><div><Field label="When"><select aria-label="Match conditions" value={rule.match} onChange={e=>patch(rule.id,{match:e.target.value as 'all'|'any'})}><option value="all">All of these are true</option><option value="any">Any of these is true</option></select></Field>
        {rule.conditions.map((c,index)=>{const update=(value:Partial<Rule>)=>patch(rule.id,{conditions:rule.conditions.map((r,i)=>i===index?{...r,...value}:r)});return <div className="layer-rule" key={index}><select aria-label="Combination condition" value={c.mode} onChange={e=>update({mode:e.target.value as Rule['mode']})}><option value="include">Includes</option><option value="exclude">Does not include</option></select><select aria-label="Condition item" value={`${c.attributeId}/${c.itemIds[0]}`} onChange={e=>{const [attributeId,itemId]=e.target.value.split('/');update({attributeId,itemIds:[itemId]});}}>{targetOptions}</select><button aria-label="Remove combination condition" disabled={rule.conditions.length===1} onClick={()=>patch(rule.id,{conditions:rule.conditions.filter((_,i)=>i!==index)})}>×</button>{c.itemIds.length>1&&<small>Matches any of {c.itemIds.length} saved items. Selecting here replaces that group.</small>}</div>;})}
        <button disabled={!first||rule.conditions.length>=32} onClick={()=>patch(rule.id,{conditions:[...rule.conditions,{attributeId:first.a.id,itemIds:[first.i.id],mode:'include'}]})}>＋ Add condition</button></div>
      <span className="layer-exception-arrow" aria-hidden="true">→</span><div><h4>Then</h4>{rule.actions.map((a,index)=>{const item=choices.find(c=>c.value===`${a.attributeId}/${a.itemId}`)?.i;const update=(value:LayerExceptionAction)=>patch(rule.id,{actions:rule.actions.map((r,i)=>i===index?value:r)});return <div className="layer-exception-action" key={index}>
        <div className="layer-rule"><select aria-label="Combination action" value={a.kind} onChange={e=>update(actionFor(e.target.value as LayerExceptionAction['kind'],`${a.attributeId}/${a.itemId}`))}><option value="move">Move to layer</option><option value="include">Add an extra item</option><option value="replace">Replace this attribute’s item</option><option value="hide">Hide</option></select><select aria-label="Action item" value={`${a.attributeId}/${a.itemId}`} onChange={e=>update(actionFor(a.kind,e.target.value))}>{targetOptions}</select><button aria-label="Remove combination action" disabled={rule.actions.length===1} onClick={()=>patch(rule.id,{actions:rule.actions.filter((_,i)=>i!==index)})}>×</button></div>
        <div className="inline-actions">{a.kind==='move'||a.kind==='hide'?<Field label="Apply to"><select aria-label="Action piece" value={a.placementId??''} onChange={e=>{const {placementId,...rest}=a;update({...rest,...(e.target.value?{placementId:e.target.value}:{})});}}><option value="">Whole item · all pieces</option>{item?.placements.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>:<Field label="Image variant"><select aria-label="Action variant" value={a.variantId} onChange={e=>update({...a,variantId:e.target.value})}>{item?.variants.filter(v=>v.weight>0).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>}
        {a.kind==='move'&&<Field label="Layer"><input aria-label="Exception layer" type="number" min={-1000} max={1000} step={1} value={a.slot} onChange={e=>{if(e.target.value&&e.target.validity.valid)update({...a,slot:Number(e.target.value)});}}/></Field>}</div></div>;})}
        <button disabled={!first||rule.actions.length>=32} onClick={()=>patch(rule.id,{actions:[...rule.actions,actionFor('hide')]})}>＋ Add action</button></div></div>
    </article>)}
    {!!rules.length&&<small>Conditions use the original trait draw. Added items do not trigger more rules. Higher layer numbers appear in front. Conflicting actions stop the preview and name the rules to fix.</small>}
  </section>;
}
