import React, { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { Project, Shared, Workspace } from './types';
import { api } from './client';
import { Badge, Field } from './ui';
import { metadataDocument, metadataChecks, projectCover, parseMetadata, readinessRating, indexCandidates, exactIndexMatches } from './metadata.mjs';
import { choiceTitle, workPlan } from './artist-workflow.mjs';
import { useLatestResult } from './use-latest-result';

export function ArtworkCover({ project, objects, caption = false }: { project: Project; objects: Workspace['state']['objects']; caption?: boolean }) {
  const workspace = useQuery<Workspace>({ queryKey: ['workspace'], queryFn: () => api('workspace') });
  const cover = projectCover(project, objects);
  const imageSource = cover.kind === 'remote' ? `${cover.src}?revision=${workspace.data?.revision ?? 0}` : cover.src;
  const [failed, setFailed] = useState(false);
  useEffect(() => setFailed(false), [imageSource, project.metadata?.image]);
  return <div className="artwork-cover">{cover.src && !failed ? <img src={imageSource} alt={project.metadata?.name || project.title} loading="lazy" onError={() => setFailed(true)} /> : <div className="cover-empty"><span aria-hidden="true">▧</span><p>{failed ? 'Cover could not be loaded' : cover.source}</p><small>{failed ? 'Check the image in Metadata.' : 'Add a cover in Metadata.'}</small></div>}{caption && cover.src && !failed && <small className="cover-caption">{cover.source}</small>}</div>;
}
export function CheckList({ checks }: { checks: any[] }) {
  return <div className="check-list">{checks.map((check) => <article key={check.id}><span className={`check-mark ${check.status}`} aria-label={check.status}>{check.status === 'pass' ? '✓' : check.status === 'attention' ? '!' : '○'}</span><div><h3>{check.title}</h3><p>{check.detail}</p></div><Badge>{({ pass: 'Checked', attention: 'Needs attention', unknown: 'Not verified', info: 'Optional' } as any)[check.status]}</Badge></article>)}</div>;
}
export function MetadataEditor({ project, objects, change, importCover, action, persist }: { project: Project; objects: Workspace['state']['objects']; change: (patch: Partial<Project>) => void; importCover: () => Promise<void>; action: Shared['action']; persist: () => Promise<any> }) {
  const metadata = metadataDocument(project);
  const [json, setJson] = useState(''); const [jsonOpen, setJsonOpen] = useState(false); const [error, setError] = useState('');
  const set = (key: string, value: any) => change({ metadata: { ...project.metadata, [key]: value } });
  const attributes = metadata.attributes ?? [];
  const checks = metadataChecks(project, objects);
  const displayedArtist = typeof metadata.artist === 'string' ? metadata.artist : project.listing.artist;
  return <div className="metadata-layout"><section className="metadata-form"><div className="section-intro"><h2>The details that travel with your work.</h2><p>This is your draft metadata. Saving here keeps it on this computer; updating a published token is a separate contract action.</p></div>
    <div className="inline-actions"><button onClick={() => void action(async () => { const result = await api('importMetadata'); if (result) change({ metadata: result.metadata }); })}>Import metadata JSON</button><button onClick={() => void action(async () => { await persist(); await api('exportMetadata', project.id); })}>Export metadata JSON</button></div>
    <div className="form-grid"><Field label="Project name"><input value={project.title} maxLength={160} onChange={(event) => change({ title: event.target.value })} /></Field><Field label="Artwork name in metadata"><input value={metadata.name ?? ''} onChange={(event) => set('name', event.target.value)} /></Field><Field label="Artist"><input maxLength={160} value={displayedArtist} onChange={(event) => change({ listing: { ...project.listing, artist: event.target.value }, metadata: { ...project.metadata, artist: event.target.value } })} /></Field><Field label="Tags (comma separated)"><input defaultValue={project.listing.tags.join(', ')} onBlur={(event) => change({ listing: { ...project.listing, tags: [...new Set(event.target.value.split(',').map((tag) => tag.trim()).filter(Boolean))].slice(0, 20) } })} /></Field></div>
    <Field label="Description"><textarea rows={4} maxLength={16000} value={metadata.description ?? ''} onChange={(event) => set('description', event.target.value)} placeholder="What should someone know about this work?" /></Field>
    <section className="metadata-cover-fields"><h3>Cover image</h3><p>Used on project cards and by wallets that read the image field.</p><Field label="Choose an imported image"><select value={objects.some((item) => metadata.image === `keel-asset://${item.id}/raw`) ? metadata.image : ''} onChange={(event) => { if (event.target.value) set('image', event.target.value); }}><option value="">Choose a file…</option>{objects.filter((item) => item.type.startsWith('image/')).map((item) => <option value={`keel-asset://${item.id}/raw`} key={item.id}>{item.name}</option>)}</select></Field><button onClick={() => void action(importCover)}>Import a cover image</button><Field label="Or an image URI"><textarea rows={2} value={metadata.image ?? ''} onChange={(event) => set('image', event.target.value)} placeholder="https://…, ipfs://…, or data:image/…" /></Field><small>Remote covers load after saving. IPFS and Arweave previews use their public gateways. Local image references need publication before export can serve as live token metadata.</small></section>
    <details className="disclosure"><summary>Animation, website & background</summary><div className="form-grid">{[['animation_url', 'Animation or interactive work URI'], ['external_url', 'Artwork website'], ['background_color', 'Background colour (six hex digits)']].map(([key, title]) => <Field label={title} key={key}><input value={metadata[key] ?? ''} onChange={(event) => set(key, event.target.value)} /></Field>)}</div></details>
    <section className="trait-editor"><div className="section-line"><h3>Traits</h3><button disabled={attributes.length >= 200} onClick={() => set('attributes', [...attributes, { trait_type: '', value: '' }])}>Add trait</button></div><p>Optional labels such as medium, palette, or edition. Numbers stay numbers.</p>{attributes.map((item: any, index: number) => <div className="trait-row" key={index}><input aria-label={`Trait ${index + 1} name`} placeholder="Medium" value={item.trait_type ?? ''} onChange={(event) => set('attributes', attributes.map((entry: any, position: number) => position === index ? { ...entry, trait_type: event.target.value } : entry))} /><input aria-label={`Trait ${index + 1} value`} placeholder="Value" value={String(item.value)} onChange={(event) => set('attributes', attributes.map((entry: any, position: number) => position === index ? { ...entry, value: typeof entry.value === 'number' && event.target.value.trim() && Number.isFinite(Number(event.target.value)) ? Number(event.target.value) : typeof entry.value === 'boolean' && ['true', 'false'].includes(event.target.value) ? event.target.value === 'true' : event.target.value } : entry))} /><select aria-label={`Trait ${index + 1} type`} value={typeof item.value} onChange={(event) => { const value = event.target.value === 'number' ? Number(item.value) : event.target.value === 'boolean' ? item.value === true || item.value === 'true' : String(item.value); if (typeof value === 'number' && !Number.isFinite(value)) return; set('attributes', attributes.map((entry: any, position: number) => position === index ? { ...entry, value } : entry)); }}><option value="string">Text</option><option value="number">Number</option><option value="boolean">True / false</option></select><button aria-label={`Remove trait ${index + 1}`} onClick={() => set('attributes', attributes.filter((_: any, position: number) => position !== index))}>Remove</button></div>)}</section>
    <details className="disclosure" open={jsonOpen} onToggle={(event) => { const open = event.currentTarget.open; if (open && !jsonOpen) setJson(JSON.stringify(metadata, null, 2)); setJsonOpen(open); }}><summary>Full JSON & custom fields</summary><p>Standard fields, display types, properties and custom fields are preserved. Applying JSON replaces this draft document.</p><textarea aria-label="Full metadata JSON" rows={12} value={json} onChange={(event) => setJson(event.target.value)} /><button onClick={() => { try { change({ metadata: parseMetadata(json) }); setError(''); setJsonOpen(false); } catch (error) { setError((error as Error).message); } }}>Apply metadata JSON</button>{error && <p role="alert" className="error-text">{error}</p>}</details>
  </section><aside className="metadata-preview"><ArtworkCover project={project} objects={objects} /><h2>{metadata.name || 'Untitled work'}</h2>{displayedArtist && <p>By {displayedArtist}</p>}<p className="metadata-description">{metadata.description || 'Add a description for your work.'}</p><CheckList checks={checks} /></aside></div>;
}
export function Audience({ project, change, action }: { project: Project; change: (patch: Partial<Project>) => void; action: Shared['action'] }) {
  const [query, setQuery] = useState(project.title); const lookup = useLatestResult(); const result: any = lookup.data;
  const candidates = indexCandidates(result); const exact = exactIndexMatches(result, project);
  return <section className="audience-panel"><h2>How people find and experience it.</h2><p>A public onchain file can be read by anyone. Rules for collecting govern who can mint; they do not make the artwork private.</p><Field label="Discovery preference"><select value={project.listing.discoverability} onChange={(event) => change({ listing: { ...project.listing, discoverability: event.target.value as Project['listing']['discoverability'] } })}><option value="undecided">Decide later</option><option value="listed">I want it listed for discovery</option><option value="unlisted">I will share the link myself</option></select></Field><small>This saves your preference. It does not publish or remove an index entry.</small>
    <div className="management-grid"><article><h3>Viewing</h3><p>{project.presentation.shell === 'canonical' ? 'KEEL verification shell' : 'Direct artwork display'}</p><small>Previewed locally. Public viewer support still needs release checks.</small></article><article><h3>Collecting</h3><p>{choiceTitle('mintSystem', project.intent.mintSystem)}</p><small>{project.intent.access?.map((item) => choiceTitle('access', item)).join(', ') || 'Eligibility has not been chosen.'}</small></article><article><h3>Viewer counts</h3><p>Not connected</p><small>No viewer analytics are collected by this desktop workspace.</small></article></div>
    <div className="discovery-check"><h3>Look for library records</h3><p>Search the connected Studio’s resource index. Search results are discovery records, not proof of ownership, publication, or a public gallery listing.</p><form className="inline-actions" onSubmit={(event) => { event.preventDefault(); void action(() => lookup.load(() => api('searchStudio', query))); }}><input aria-label="Project index query" value={query} maxLength={160} required onChange={(event) => { lookup.clear(); setQuery(event.target.value); }} /><button>Check Studio index</button></form>{result && <><p>{candidates.length} results · {exact.length} match an attached file fingerprint · {result.status}</p>{!candidates.length && <p>No match returned by this search. The work may exist outside this index or its current coverage.</p>}{result.errors?.map((error: string) => <p key={error} role="alert">{error}</p>)}{candidates.map((record: any, index: number) => <details key={index}><summary>{String(record.name ?? record.title ?? 'Library record')} · {exact.includes(record) ? 'Fingerprint matches' : 'Search candidate'}</summary><pre>{JSON.stringify(record, null, 2)}</pre></details>)}</>}</div>
  </section>;
}
export function ProjectManager({ project, state, action, persist, dirty, change, go, openContracts }: { project: Project; state: Workspace['state']; action: Shared['action']; persist: () => Promise<any>; dirty: boolean; change: (patch: Partial<Project>) => void; go: (tab: string) => void; openContracts: (id?: string) => void }) {
  const history = useQuery<any[]>({ queryKey: ['project-checks', project.id], queryFn: () => api('projectChecks', project.id) });
  const [selectedCheck, setSelectedCheck] = useState('');
  const plan = workPlan(project, state.objects); const current: any = history.data?.find((item) => item.checkedAt === selectedCheck) ?? history.data?.[0];
  const checks = current && !dirty && current.current ? [...current.checks, ...(current.onchain?.checks ?? [])] : metadataChecks(project, state.objects);
  const rating = readinessRating(checks);
  const contracts = state.contracts.filter((item) => item.projectId === project.id || project.contractIds.includes(item.id));
  const [token, setToken] = useState(project.publication ? { ...project.publication, chainId: String(project.publication.chainId) } : { contractAddress: '', tokenId: '', standard: 'erc721', chainId: String(project.intent.chainId ?? '') });
  return <div className="project-management content-pad"><div className="section-intro"><h2>Keep this project in good shape.</h2><p>Manage the draft, keep track of its published token, and review what the evidence can tell you.</p></div><div className="management-grid"><article><h3>Release / drop</h3><p>{choiceTitle('outcome', project.intent.outcome)}</p><small>{plan.status === 'planned' ? 'Direction chosen · release setup still required' : `${plan.questions.length} choices remaining`}</small><button onClick={() => go('Release')}>Edit release plan</button></article><article><h3>Storage & files</h3><p>{project.files.length} source files · {project.objectIds.length} {project.objectIds.length === 1 ? 'original' : 'originals'}</p><small>{choiceTitle('storage', project.intent.storage)}</small><button onClick={() => go('Viewing')}>Manage presentation & storage</button></article><article><h3>Contracts & collections</h3><p>{contracts.length} linked contracts</p><small>Inspect controls, proxies, permissions and unsigned updates.</small><button onClick={() => openContracts()}>Manage contracts</button></article><article><h3>Creative resources</h3><p>{state.moduleSelections.filter((item) => item.projectId === project.id).length} saved references</p><small>Library records need selected-network binding.</small><button onClick={() => go('Resources')}>Manage resources</button></article></div>
    <details className="disclosure"><summary>Project contract links · {contracts.length}</summary><p>Link a tracked collection, proxy or storage contract. The same contract can belong to several projects; linking it does not claim ownership.</p><Field label="Link a tracked contract"><select value="" onChange={(event) => { if (event.target.value) change({ contractIds: [...new Set([...project.contractIds, event.target.value])] }); }}><option value="">Choose from this workspace…</option>{state.contracts.filter((item) => !contracts.includes(item)).map((item) => <option key={item.id} value={item.id}>{item.name} · chain {item.chainId}</option>)}</select></Field>{contracts.map((item) => <div className="inline-actions" key={item.id}><span>{item.name} · {item.chainId}</span><button onClick={() => openContracts(item.id)}>Open controls</button>{project.contractIds.includes(item.id) && item.projectId !== project.id && <button onClick={() => change({ contractIds: project.contractIds.filter((id) => id !== item.id) })}>Unlink from project</button>}</div>)}</details>
    <section className="checks-panel"><div className="section-line"><div><h2>Project checks</h2><p>Evidence rating · {rating.passed} of {rating.total} checks met</p></div><Badge>{rating.unknown} not verified</Badge></div><p>This rates readiness and available evidence, never artistic quality. A high count does not certify that every dependency is onchain.</p><div className="inline-actions"><button className="primary" onClick={() => void action(async () => { await persist(); await api('checkProject', { projectId: project.id }); setSelectedCheck(''); await history.refetch(); })}>Save & check files</button><button disabled={!project.publication || !project.targetNetworkId} onClick={() => void action(async () => { await persist(); await api('checkProject', { projectId: project.id, onchain: true }); setSelectedCheck(''); await history.refetch(); })}>Save & check onchain</button></div><CheckList checks={checks} />{history.error && <p role="alert">{history.error.message}</p>}{(history.data?.length ?? 0) > 1 && <Field label="Check history"><select value={selectedCheck || history.data?.[0]?.checkedAt} onChange={(event) => setSelectedCheck(event.target.value)}>{history.data?.map((item) => <option key={item.checkedAt} value={item.checkedAt}>{new Date(item.checkedAt).toLocaleString()} · {item.onchain ? 'Files & onchain' : 'Files'} · {item.current && !dirty ? 'Matches saved draft' : 'Earlier version'}</option>)}</select></Field>}{current && <details className="disclosure"><summary>{current.current && !dirty ? 'Latest saved check' : 'Earlier check · project has changed'} · {new Date(current.checkedAt).toLocaleString()}</summary>{current.onchain && <><p>Chain {current.onchain.chainId} · block {current.onchain.block} · token {current.onchain.tokenId}</p><code>{current.onchain.contractAddress}</code>{current.onchain.document && <button onClick={() => change({ metadata: current.onchain.document })}>Use published metadata as draft</button>}</>}<pre>{JSON.stringify(current, null, 2)}</pre></details>}</section>
    <details className="disclosure" open={!project.publication}><summary>Track a published token</summary><p>Already released? Save its exact collection and token, then connect that network in Viewing to check it. This does not mint or grant contract permissions.</p><form onSubmit={(event) => { event.preventDefault(); change({ publication: { ...token, chainId: Number(token.chainId), standard: token.standard as 'erc721' | 'erc1155' } }); }}><div className="form-grid"><Field label="Collection contract"><input value={token.contractAddress} required pattern="0x[0-9a-fA-F]{40}" onChange={(event) => setToken({ ...token, contractAddress: event.target.value })} /></Field><Field label="Token ID"><input required inputMode="numeric" pattern="0|[1-9][0-9]*" value={token.tokenId} onChange={(event) => setToken({ ...token, tokenId: event.target.value })} /></Field><Field label="Token network chain ID"><input type="number" min={1} required value={token.chainId} onChange={(event) => setToken({ ...token, chainId: event.target.value })} /></Field><Field label="Collection standard"><select value={token.standard} onChange={(event) => setToken({ ...token, standard: event.target.value })}><option value="erc721">Unique works · ERC-721 / ERC-721A</option><option value="erc1155">Editions · ERC-1155</option></select></Field></div><button>Use this token in draft</button></form>{project.publication && <p>Draft target: chain {project.publication.chainId} · token {project.publication.tokenId}. Save or run a check to keep this change.</p>}</details>
    <details className="disclosure"><summary>Export original files</summary>{state.objects.filter((item) => project.objectIds.includes(item.id)).map((item) => <div className="inline-actions" key={item.id}><span>{item.name}</span><button onClick={() => void action(() => api('exportObject', item.id))}>Export original</button></div>)}{!project.objectIds.length && <p>Imported originals will appear here. Use Setup to export the full workspace, including source files and metadata.</p>}</details>
  </div>;
}
