import React, { useState } from 'react';
import type { Project, Shared } from './types';
import { Field, Badge, fileSize } from './ui';
import { artistOptions, choiceTitle, changeIntent, workPlan } from './artist-workflow.mjs';
import { CREATION_STEPS, templateFor, releaseDefaults, artworkReady, artworkIssue, collectionReady, attachArtwork } from './creation-workflow.mjs';
import { Audience } from './project-details';
import { CreationNetwork, CollectionPicker } from './creation-ui';
import { api } from './client';
import { GameArtworkButton } from './game-engine/game-workspace';

type Props = {
  project: Project; state: Shared['state']; choice: (field: string, value: unknown) => void;
  change: (patch: Partial<Project>) => void; network: React.ReactNode; selectNetwork: (id: string, snapshot: any) => Promise<void>;
  action: Shared['action']; save: (next?: Project) => Promise<any>; importArtwork: () => Promise<void>;
  layers: () => void; game?: () => void; metadata: () => void; preview: () => void; openContracts: (id?: string) => void; assist: () => Promise<void>;
};
const STEP_LABELS: Record<string, string> = { artwork: 'Artwork', collection: 'Collection', review: 'Review' };

export function ReleaseWizard({ project, state, choice, change, network, selectNetwork, action, save, importArtwork, layers, game, metadata, preview, openContracts, assist }: Props) {
  const [requestedStep, setStep] = useState(project.creation?.step ?? 'artwork');
  const [saved, setSaved] = useState(false);
  const [report, setReport] = useState<any>();
  const [checking, setChecking] = useState(false);
  const steps = project.intent.outcome === 'explore' ? ['artwork', 'review'] : CREATION_STEPS;
  const step = steps.includes(requestedStep) ? requestedStep : 'artwork'; const position = steps.indexOf(step);
  const intent = project.intent; const template = templateFor(project); const plan = workPlan(project, state.objects);
  const art = state.objects.find(item => item.id === project.presentation.entryObjectId);
  const originals = project.creation?.artworkIds ?? (art ? [art.id] : []);
  const ready = artworkReady(project); const hasCollection = collectionReady(project);
  const issue = artworkIssue(project);
  const canVisit = (value: string) => value === 'artwork' || (!issue && (value === 'collection' || hasCollection));
  async function go(value: string) {
    if (!canVisit(value)) return;
    const next = project.creation ? { ...project, creation: { ...project.creation, step: value as any } } : project;
    if (next.creation) change({ creation: next.creation });
    await save(next); setStep(value as any); setSaved(false);
  }
  const edit = (patch: Partial<Project>) => { change(patch); setSaved(false); setReport(undefined); };
  function select(field: string, title: string) {
    const value = (intent as any)[field]; const options = artistOptions(field as any);
    return <Field label={title}><select value={value ?? ''} onChange={event => choice(field, event.target.value)}><option value="">Choose…</option>{options.map((item: any) => <option key={item.value} value={item.value}>{item.title}</option>)}</select><small>{options.find((item: any) => item.value === value)?.description}</small></Field>;
  }
  async function check() {
    setChecking(true);
    try { await save(); const result = await api('checkProject', { projectId: project.id }); setReport({ ...result, draft: JSON.stringify(project) }); } finally { setChecking(false); }
  }
  const selectedContract = state.contracts.find(item => item.chainId === intent.chainId && item.address.toLowerCase() === intent.collectionAddress?.toLowerCase());
  return <div className="creation-guide"><nav className="creation-steps" aria-label="Creation steps">{steps.map((item, index) => <button key={item} disabled={!canVisit(item)} aria-current={step === item ? 'step' : undefined} className={step === item ? 'selected' : ''} onClick={() => void action(() => go(item))}><span>{index + 1}</span>{STEP_LABELS[item]}{index < steps.length - 1 && <i aria-hidden="true">→</i>}</button>)}</nav>
    <div className="creation-layout"><section className="creation-main"><div className="creation-intro"><div className="eyebrow">{template?.title ?? 'Your work'} · {position + 1} / {steps.length}</div><h2>{step === 'artwork' ? 'Start with the artwork.' : step === 'collection' ? 'Give it a home.' : 'A look before you release.'}</h2><p>{step === 'artwork' ? project.layered ? 'Your layers are ready here. Choose your collection size and continue.' : template?.id === 'collection' ? 'Add your works. They’ll stay together in this collection draft.' : 'Add your file and a name. We’ll take care of the presentation.' : step === 'collection' ? 'Use a collection you already have, or make a new one.' : 'Your work and choices, ready for the next step.'}</p></div>
    {step === 'artwork' && <>
      {template?.id === 'game' ? <GameArtworkButton project={project} open={game} /> : project.layered ? <button className="artwork-upload has-art" onClick={layers}><strong>Edit layers</strong><small>{project.layered.attributes.length} attributes · {project.layered.attributes.reduce((n,a)=>n+a.items.length,0)} items</small><span>↗</span></button> : <button className={`artwork-upload ${ready ? 'has-art' : ''}`} onClick={() => void action(importArtwork)}><span aria-hidden="true">＋</span><span><strong>{art ? template?.id === 'collection' ? 'Add more artworks' : 'Choose another file' : template?.id === 'interactive' ? 'Import your own work' : template?.id === 'collection' ? 'Choose your artworks' : 'Choose your image or file'}</strong><small>{art ? `${originals.length} ${originals.length === 1 ? 'artwork' : 'artworks'} added · originals preserved` : template?.id === 'interactive' ? 'Or use the 3D sketch beside this guide.' : 'Images, GIFs, video, sound, HTML and more.'}</small></span><span>↗</span></button>}
      {originals.length > 1 && <div className="artwork-strip" aria-label="Collection artworks">{originals.map(id => { const item = state.objects.find(object => object.id === id); if (!item) return null; return <button key={id} title={item.name} aria-label={`Preview ${item.name}`} aria-pressed={id === art?.id} className={id === art?.id ? 'selected' : ''} onClick={() => edit({ presentation: { ...project.presentation, entryObjectId: id } })}>{item.type.startsWith('image/') ? <img src={`keel-asset://${id}/raw`} alt={item.name} /> : <span>▧</span>}<small>{item.name}</small></button>; })}</div>}
      <Field label={template?.id === 'collection' ? 'Project name' : 'Artwork name'}><input maxLength={160} value={project.title} placeholder="Give your work a name" onChange={event => edit({ title: event.target.value, ...(!project.metadata.name || project.metadata.name === project.title ? { metadata: { ...project.metadata, name: event.target.value } } : {}) })} /></Field>
      {intent.outcome === 'release' && <Edition project={project} change={edit} />}
      <div className="shell-default"><span aria-hidden="true">✓</span><div><strong>{project.presentation.shell === 'canonical' ? 'Verified view included' : 'Direct display selected'}</strong><small>{project.presentation.shell === 'canonical' ? 'Your original artwork inside KEEL’s verification shell.' : 'Your artwork opens directly, using your saved choice.'}</small></div></div>
      <details className="disclosure"><summary>More artwork options</summary><Field label="Use a file already in your workspace"><select value="" onChange={event => { const object = state.objects.find(item => item.id === event.target.value); if (object) edit(attachArtwork(project, [object]) as Project); }}><option value="">Choose a saved file…</option>{state.objects.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Description (optional)"><textarea rows={3} maxLength={16000} value={project.metadata.description ?? ''} onChange={event => edit({ metadata: { ...project.metadata, description: event.target.value } })} /></Field><Field label="Presentation"><select value={project.presentation.shell} onChange={event => edit({ presentation: { ...project.presentation, shell: event.target.value as 'canonical' | 'none' } })}><option value="canonical">KEEL verification shell · default</option><option value="none">Direct display · bypass the shell</option></select></Field><Field label="What would you like to do?"><select value={intent.outcome ?? 'explore'} onChange={event => event.target.value === 'release' ? edit({ intent: releaseDefaults(intent, template) }) : choice('outcome', event.target.value)}>{artistOptions('outcome').map((item: any) => <option key={item.value} value={item.value}>{item.title}</option>)}</select></Field>{!art && !project.layered && select('runtime', 'Creative library')}{select('storage', 'How should the work be preserved?')}<p className="creation-hint">The verified viewer uses your saved delivery choice. Automatic delivery uses Inline up to 1.75 MB compressed, then recommends RPC reconstruction. You can choose Inline for larger works in the presentation settings.</p><button onClick={() => void action(async () => { await save(); metadata(); })}>Cover, traits & full metadata ↗</button></details>
    </>}
    {step === 'collection' && <><CreationNetwork project={project} action={action} select={selectNetwork} advanced={network} />{intent.outcome === 'release' && <><CollectionPicker project={project} state={state} change={edit} action={action} persist={save} openContracts={openContracts} /><details className="disclosure release-options"><summary>More options · collecting & custom contracts</summary>{select('mintSystem', 'How will people collect?')}{select('collection', 'Collection type')}{['existing', 'external'].includes(intent.collection ?? '') && <Field label="Existing collection address"><input key={`${intent.family}:${intent.chainId}:${intent.collection}`} defaultValue={intent.collectionAddress ?? ''} placeholder="0x…" onBlur={event => choice('collectionAddress', event.target.value)} /></Field>}{intent.mintSystem === 'fray-auction' ? <p>The assistant can prepare Fray’s auction intake. Choose the preset and exact terms before signing.</p> : <Access project={project} choice={choice} select={select} />}</details></>}{intent.outcome !== 'release' && select('storage', 'How should the work be preserved?')}</>}
    {step === 'review' && <><div className="creation-review"><div><small>Artwork</small><strong>{project.metadata.name || project.title}</strong><button onClick={() => void action(() => go('artwork'))}>Edit</button></div><div><small>Collection</small><strong>{selectedContract?.name || project.creation?.collectionName || choiceTitle('collection', intent.collection)}</strong><button onClick={() => void action(() => go('collection'))} disabled={intent.outcome === 'explore'}>Edit</button></div><div><small>Edition</small><strong>{intent.releaseType === 'limited-edition' ? `${intent.supply || '—'} copies` : intent.releaseType === 'series' ? `${project.layered ? project.layered.attributes.length+' layered attributes' : originals.length+' artworks added'}${intent.supply ? ` · ${intent.supply} planned` : ''}` : choiceTitle('releaseType', intent.releaseType)}</strong></div><div><small>Who can collect</small><strong>{intent.mintSystem === 'mint-gate' ? intent.access?.map(value => choiceTitle('access', value)).join(', ') : choiceTitle('mintSystem', intent.mintSystem)}</strong></div></div>
      {!!plan.questions.length && <div className="notice"><strong>A few choices still need attention</strong>{plan.questions.map((question: any) => <p key={question.field}>{question.question}</p>)}</div>}
      {!!plan.blockers.length && <div className="notice"><strong>Setup needed before publishing</strong>{plan.blockers.map((blocker: string) => <p key={blocker}>{blocker}</p>)}</div>}
      <div className="release-next"><h3>{saved ? 'Your draft is saved.' : 'Save now. Release when you’re ready.'}</h3><p>{template?.id === 'collection' ? 'These files form a local collection draft. Individual artwork metadata and minting still need release preparation.' : 'Next we’ll prepare the release, confirm prices and permissions, and show the wallet request.'}</p><div className="inline-actions"><button className="primary" onClick={() => void action(async () => { await save(); setSaved(true); })}>Save {template?.id === 'collection' ? 'collection' : 'release'} draft</button><button disabled={checking} onClick={() => void action(check)}>{checking ? 'Checking files…' : 'Check artwork'}</button></div><small>Saved on this computer. Publishing happens after you review the release and sign.</small></div>
      {report && report.draft === JSON.stringify(project) && <div className="creation-checks" role="status"><h3>Artwork check</h3>{report.checks.map((item: any) => <div key={item.id}><Badge tone={item.status === 'pass' ? '' : 'warm'}>{item.status === 'pass' ? 'Checked' : 'Review'}</Badge><span>{item.title}<small>{item.detail}</small></span></div>)}</div>}
      <button className="text-button" onClick={() => void action(async () => { await save(); await assist(); })}>Prepare release with the assistant ↗</button>
      <details className="disclosure"><summary>Discovery & remaining release checks</summary><Audience project={project} change={edit} action={action} />{plan.remainingReview.map((item: string) => <p key={item}>{item}</p>)}</details>
    </>}
    </section><aside className="creation-preview"><div className="creation-preview-frame">{art?.type.startsWith('image/') ? <img src={`keel-asset://${art.id}/raw`} alt={project.metadata.name || project.title} /> : art?.type.startsWith('video/') ? <video controls src={`keel-asset://${art.id}/raw`} /> : art?.type.startsWith('audio/') ? <audio controls src={`keel-asset://${art.id}/raw`} /> : ready ? <iframe title="Artwork preview in creation guide" sandbox="allow-scripts allow-pointer-lock" src={`keel-preview://${project.id}/index.html`} /> : <div className="creation-empty"><span aria-hidden="true">▧</span><strong>Your artwork goes here.</strong><p>Choose a file to see it take shape.</p></div>}</div><div className="creation-preview-caption"><span>ARTWORK PREVIEW</span><Badge>{project.presentation.shell === 'canonical' ? 'Verified view' : 'Direct display'}</Badge><h3>{project.metadata.name || project.title}</h3><p>{art ? `${art.name} · ${fileSize(art.byteLength)}` : ready ? 'Interactive work · shared creative library' : 'Original files stay intact.'}</p>{ready && <button onClick={() => void action(async () => { await save(); preview(); })}>Open full preview ↗</button>}</div></aside></div>
    <footer className="creation-footer"><button disabled={position === 0} onClick={() => void action(() => go(steps[position - 1]))}>← Back</button><span>{step === 'artwork' && issue ? issue : step === 'collection' && !hasCollection ? 'Choose a network and collection to continue.' : 'Each step saves your progress.'}</span>{position < steps.length - 1 ? <button className="primary" disabled={!canVisit(steps[position + 1])} onClick={() => void action(() => go(steps[position + 1]))}>Continue to {STEP_LABELS[steps[position + 1]].toLowerCase()} →</button> : <button onClick={() => void action(async () => { await save(); preview(); })}>Back to your work ↗</button>}</footer>
  </div>;
}

function Edition({ project, change }: { project: Project; change: (patch: Partial<Project>) => void }) {
  const edition = project.intent.releaseType; const supply = project.intent.supply ?? '';
  function choose(value: string) { const intent = changeIntent(project.intent, 'releaseType', value); if (value === 'limited-edition') intent.supply = '25'; if (value === 'series' && project.creation?.artworkIds.length) intent.supply = String(project.creation.artworkIds.length); if (project.creation && ['erc721a', 'erc1155'].includes(intent.collection ?? '')) intent.collection = ['limited-edition', 'open-edition'].includes(value) ? 'erc1155' : 'erc721a'; change({ intent }); }
  return <div className="edition-control"><span className="field-caption">How many?</span><div className="segmented" role="group" aria-label="Edition size">{[['one-of-one', 'One of one'], ['limited-edition', 'An edition'], ['open-edition', 'Open edition'], ['series', 'A series']].map(([value, title]) => <button key={value} aria-pressed={edition === value} className={edition === value ? 'selected' : ''} onClick={() => choose(value)}>{title}</button>)}</div>{edition === 'limited-edition' && <><div className="edition-quantity"><input type="range" aria-label="Edition quantity slider" min="1" max="1000" value={Math.min(1000, Number(supply) || 1)} onChange={event => change({ intent: { ...project.intent, supply: event.target.value } })} /><Field label="Number of copies"><input inputMode="numeric" value={supply} onChange={event => { if (!event.target.value || /^[1-9]\d{0,77}$/.test(event.target.value)) change({ intent: changeIntent(project.intent, 'supply', event.target.value) }); }} /></Field></div><div className="quantity-presets">{[10, 25, 50, 100].map(value => <button key={value} aria-pressed={supply === String(value)} onClick={() => change({ intent: { ...project.intent, supply: String(value) } })}>{value}</button>)}<small>One artwork, each copy collectible.</small></div></>}{edition === 'series' && <><Field label="Works in this release"><input inputMode="numeric" value={supply} placeholder="Number of unique works" onChange={event => { if (!event.target.value || /^[1-9]\d{0,77}$/.test(event.target.value)) change({ intent: changeIntent(project.intent, 'supply', event.target.value) }); }} /></Field><p className="creation-hint">Each artwork is a different work. You can add more as the collection grows.</p></>}{edition === 'open-edition' && <p className="creation-hint">Set the collecting window during release preparation.</p>}</div>;
}

function Access({ project, choice, select }: { project: Project; choice: Props['choice']; select: (field: string, label: string) => React.ReactNode }) {
  const intent = project.intent;
  return intent.mintSystem === 'mint-gate' ? <><h3>Who can collect?</h3><div className="choice-cards access-cards">{artistOptions('access').map((item: any) => <label key={item.value} className={intent.access?.includes(item.value) ? 'selected' : ''}><input type="checkbox" checked={intent.access?.includes(item.value) ?? false} onChange={event => { const current = intent.access ?? []; choice('access', event.target.checked ? item.value === 'public' ? ['public'] : [...current.filter(value => value !== 'public'), item.value] : current.filter(value => value !== item.value)); }} /><span><strong>{item.title}</strong><small>{item.description}</small></span></label>)}</div>{(intent.access?.length ?? 0) > 1 && select('gateLogic', 'How should these rules combine?')}{select('signature', 'Extra authorization')}</> : intent.mintSystem === 'one-mint' ? <><h3>Drop phases</h3><p>Add phases in the order they should run.</p><div className="phase-list">{intent.stages?.map((stage, index) => <div key={stage}><span>{index + 1}. {choiceTitle('stage', stage)}</span><button disabled={!index} aria-label={`Move ${stage} earlier`} onClick={() => { const next = [...intent.stages!]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; choice('stages', next); }}>Earlier</button><button aria-label={`Remove ${stage} phase`} onClick={() => choice('stages', intent.stages?.filter(item => item !== stage))}>Remove</button></div>)}</div><div className="inline-actions">{artistOptions('stage').map((item: any) => <button disabled={intent.stages?.includes(item.value)} key={item.value} onClick={() => choice('stages', [...(intent.stages ?? []), item.value])}>+ {item.title}</button>)}</div></> : <p>You’ll review recipients and quantities before signing.</p>;
}
