import { KEEL_PAYLOAD_STORAGE_POLICY } from "@keel/protocol";
/** One policy shared by handshake, prompts, resources and preflight. */
export const PREPARED_COPY_POLICY = {
  id: "prepared-copy",
  payloadStorage: KEEL_PAYLOAD_STORAGE_POLICY,
  existingObjectsFirst: "keel-inline-reuse-plan",
  documentation: "docs/KEEL_PREPARED_COPY_ASSEMBLY.md",
  inspector: "inspectKeelInlineExistingObjectReuse",
  sdkContext: "existingObjectReuse:{mode:'assembly-only',chainId,store}",
  base64Builder: "KeelHarnessBuilder",
  base64Methods: ["preparedTokenURI", "preEncodedTokenURI"],
  publicationCheck: "keel-inline-publication-check",
  publicTokenAudit: "keel-inline-token-audit",
  freshPayloadPolicy: "no-new-base64-or-hex-body",
  collectorInlineBinaryDefault: { helper: "buildKeelPreparedDenseCopyShell", payloadPreparation: "build-time", transportProfile: "base90-v1", shellBootEncoding: "base64", contractOperation: "verified-copy" },
  nativeReturnDefault: "as-is",
  encodedNativeReturnRequiresExplicitSelection: true,
  noEncodingScope: "A no-Base64/no-hex/as-is request applies to returned payloads as well as stored objects. Native storage does not authorize an expanding contract return.",
  payloadDocumentation: "docs/KEEL_INLINE_PAYLOAD_BOUNDARIES.md",
  prototypeTests: ["keel-contracts/test/KeelPreEncodedBench.t.sol", "keel-contracts/test/modules/keel-harness/KeelRawTokenURIBuilder.t.sol", "tests/sdk-inline-existing-object-reuse.test.mjs", "tests/mcp-prepared-copy.test.mjs"],
  bodyTransform: "none",
  newSourcePublicationBytes: 0,
  requires: ["exact existing ordered object IDs and bytes", "matching registered selected-chain builder and shell", "receipt/block/read-back authentication before publication"],
  incompatibleBytes: "Fail with a compatibility error. Padding raw binary alone does not make a prepared Base64 fragment; never silently encode, repack or republish it.",
} as const;

export const PREPARED_COPY_GUIDANCE = "Existing onchain objects come first: call keel-inline-reuse-plan before keel-inline-prepare or upload-plan. Read docs/KEEL_PREPARED_COPY_ASSEMBLY.md. KEEL's preparedTokenURI/preEncodedTokenURI copy already prepared, aligned Base64 prefix/body/suffix fragments; they never re-encode the large body. Preserve exact ordered object IDs, bytes, media, selected chain and store, and use the matching registered shell/builder. Existing bound Base64 carriage is reused directly, without a legacy migration or new encoded copy. Raw-percent and percent builders likewise copy their exact prepared fragments. SDK assembly-only reuse rejects missing references, new source parts, transcoding and incompatible bytes. Padding arbitrary binary is insufficient. New or changed creator source uses explicit preparation; small canonical metadata-envelope encoding is distinct from body encoding. Authenticate selected-chain receipts, read-back and revision authority before publication.";

export const COPY_PUBLICATION_GUIDANCE = "Every onchain-art publication uses the tested prepared COPY builders. Read the prototype/test map in docs/KEEL_PREPARED_COPY_ASSEMBLY.md before preparing bytes. Fresh MCP preparation accepts compact raw-percent only; existing prepared Base64/percent objects retain exact bytes. Selecting a carriage or setting an environment variable never grants a fresh encoding exception. Before publish-plan provide the complete collection return and exact canonical preparation to keel-inline-publication-check; prepared viewer plans reject missing evidence, altered transport or mismatched source. Never fork a runtime encoder/composer, substitute hex, or call a wallet directly to bypass this gate. The check is local byte evidence, not chain authentication or wallet approval; public receipts/read-back and browser verification remain distinct.";

const BASE_BINARY_PAYLOAD_GUIDANCE = "Default payloadStorage is compact across SDK, MCP, editor and Studio. Store native bytes once; compare supported lossless codecs and keep none when compression does not save bytes. Raw is an explicit persisted choice that keeps supplied bytes unchanged and disables automatic compression; it is separate from viewer=none, Inline/Hybrid delivery and prepared URI carriage. Reuse unchanged onchain object IDs and publish changed resources only. For native compressed binary, use the registered reader/composer profile in docs/KEEL_BINARY_RESOURCE_DELIVERY.md, not a second stored Base64/hex copy. Contract return encoding and storage are different boundaries: read-time Base64 or hex output does not prove another paid stored copy. Fresh prepared-COPY UTF-8 text uses storedText/none with exact byte verification; its guard does not validate native binary composers. Read docs/KEEL_PAYLOAD_STORAGE.md and audit source, new/reused stored bytes, complete tokenURI bytes and call gas separately. Raw does not change the selected shell or bypass integrity and selected-chain evidence checks. Shell choice is independent of payload storage. Default to the registered KEEL verification shell. If a creator explicitly selects viewer=none, preserve their creator-owned HTML shell and direct-artifact presentation through handoff, preview, preparation and publication; do not insert or label it as canonical protection. The same native-byte/no-duplicate storage policy applies to both. Existing explicit creator shell registration/selection APIs remain available for reusable custom shells.";

export const NATIVE_RETURN_GUIDANCE = "Native compressed payload return defaults to as-is, independently of payloadStorage. A user who forbids Base64, hex, or expanding encoding has forbidden those transformations in tokenURI/HTML too, even when Hold storage is native binary. buildCompactInlineKeelShell rejects embeddedContainerDelivery by default: the existing embedded-shared-containers@1 composer emits Base64 and needs an explicit binaryPayloadCarriage:'base64' selection authorized by the creator. Do not add that selection to evade an as-is requirement. Test the exact raw payload, padding, ABI string decoder and browser data URL before proposing a reader. If the bytes fail, report the incompatible boundary and stop before signing. Neither a stored-byte SHA check, three-byte padding, a custom viewer nor a network loader proves a working unchanged Inline return. Never describe encoding expansion as acceptable merely because no new encoded object was uploaded. A small standard shell header cannot protect native bytes from earlier ABI string, JSON and data-URI parsing. A single-byte HTML file can pass exact reconstruction and still fail ordinary marketplace delivery. Validate the complete UTF-8 tokenURI and both standard metadata/animation data-URI layers before the shell runs; keep native-file, returned-metadata, stored-byte and live-marketplace evidence separate. Escape only the characters the selected parser requires, and never call a broad octal-escape experiment the minimum overhead.";


/** Capability is local until the exact matching composer/shell is registered on the selected chain. */
export const DENSE_TRANSPORT_GUIDANCE = "When a creator authorizes dense binary-to-text carriage, SDK binaryPayloadCarriage:'base90' selects embedded-shared-containers-base90@1 and the optional bounded Base90 decoder; 'base91' selects the separate standard basE91 profile. Keep original compressed Hold objects unchanged. Both profiles use storedDense fields and verify table/stored/decoded/member commitments before execution. Compare complete tokenURI bytes, decoder bytes and matching wrapper escaping: generic quoted-HTML percent wrapping can erase savings. Local codec support is not selected-chain composer registration or marketplace proof. Require a matching registered composer/shell, public read-back, complete JSON/data-URI roundtrip and browser proof before publishing. Never substitute Base64/hex or relax an as-is requirement without explicit creator authorization.";

export const PREPARED_DENSE_COPY_GUIDANCE = "Full Inline is the automatic default at or below 2,000,000 complete prepared tokenURI bytes: one public tokenURI read embeds every module and asset, with no follow-up browser RPC. Module count is not public-call count; internal contract descriptor/carrier reads still require a gas check. Compressed asset size is only an estimate before final preparation. Preserve explicit delivery choices and never silently substitute a network reader. Use keel-inline-token-audit for actual token bytes and keel-inline-publication-check for the complete expected/returned URI. For new collector Inline binary work, default to buildKeelPreparedDenseCopyShell: compress first, prepare Base90-v1 text and URI escaping before upload, store one prepared payload representation, and copy committed fragments in tokenURI. The browser decodes Base64 shell literals and the separate Base90 payloads, verifies stored/decoded/member SHA-256, then mounts the exact chosen shell. Never encode dense payloads on read or Base64-wrap the complete HTML/metadata. Escape question marks at both URI layers to prevent query normalization. Explicit Raw/as-is and creator-owned shell choices remain authoritative; do not force this wrapper onto them. Existing native binary is not already a prepared Base90 fragment: a creator-authorized migration requires new carriages and a separate upload quote. Preserve existing source IDs, seed and ownership, report new versus reused bytes, and never claim zero new storage for that migration. Require the matching selected-chain COPY composer, complete exact URI check within public read gas limits and offline browser proof. Do not silently use the runtime Base64/hex composers.";

export const BINARY_PAYLOAD_GUIDANCE = BASE_BINARY_PAYLOAD_GUIDANCE + " " + NATIVE_RETURN_GUIDANCE + " " + DENSE_TRANSPORT_GUIDANCE + " " + PREPARED_DENSE_COPY_GUIDANCE;
