// GENERATED BY `keel sync` — DO NOT EDIT BY HAND.
/** ABIs for the keel-kernel module. */
export const ABIS = {
  "KeelFeeTreasury": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "manager_",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "receive",
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "PAYOUT_DELAY",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "accessGroups",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "contract KeelAccessGroups"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "claim",
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address payable"
        },
        {
          "name": "tokens",
          "type": "address[]",
          "internalType": "address[]"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "configureAccessGroups",
      "inputs": [
        {
          "name": "groups",
          "type": "address",
          "internalType": "contract KeelAccessGroups"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "configureCustomPayoutLimit",
      "inputs": [
        {
          "name": "asset",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "maximum",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "configurePayoutWallet",
      "inputs": [
        {
          "name": "wallet",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "expectedRevision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "customPayoutLimit",
      "inputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "manager",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "nextCustomPayoutAt",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "payout",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "asset",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "expectedRevision",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "deadline",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "signatures",
          "type": "tuple[]",
          "internalType": "struct KeelAccessGroups.Signature[]",
          "components": [
            {
              "name": "signer",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "signature",
              "type": "bytes",
              "internalType": "bytes"
            }
          ]
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "payoutRevision",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "payoutWallet",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "withdrawalsUnlockAt",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "AccessGroupsConfigured",
      "inputs": [
        {
          "name": "groups",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "revision",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "CustomPayoutLimitConfigured",
      "inputs": [
        {
          "name": "asset",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "maximum",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "revision",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "FeesClaimed",
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "asset",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "GroupPayout",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "recipient",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "asset",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "custom",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "PayoutWalletConfigured",
      "inputs": [
        {
          "name": "wallet",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "revision",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        },
        {
          "name": "unlockAt",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "CustomPayoutLimitExceeded",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CustomPayoutLocked",
      "inputs": []
    },
    {
      "type": "error",
      "name": "FeeTransferFailed",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidAssetOrder",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidFeeRecipient",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidManager",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidPayoutAmount",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidPayoutConfiguration",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ReentrancyGuardReentrantCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SafeERC20FailedOperation",
      "inputs": [
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "StalePayoutRevision",
      "inputs": []
    },
    {
      "type": "error",
      "name": "UnauthorizedGovernance",
      "inputs": []
    },
    {
      "type": "error",
      "name": "UnsupportedFeeToken",
      "inputs": []
    },
    {
      "type": "error",
      "name": "WithdrawalsLocked",
      "inputs": []
    }
  ],
  "KeelAccessGroups": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "manager_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "bootstrapMember",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "ACTION_TYPEHASH",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "MAX_MEMBERS",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "MODERATION_GROUP",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "OPERATIONS_GROUP",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "TREASURY_GROUP",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "actionDigest",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "selector",
          "type": "bytes4",
          "internalType": "bytes4"
        },
        {
          "name": "actionHash",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "deadline",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "authorize",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "selector",
          "type": "bytes4",
          "internalType": "bytes4"
        },
        {
          "name": "actionHash",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "deadline",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "signatures",
          "type": "tuple[]",
          "internalType": "struct KeelAccessGroups.Signature[]",
          "components": [
            {
              "name": "signer",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "signature",
              "type": "bytes",
              "internalType": "bytes"
            }
          ]
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "configureCapability",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "selector",
          "type": "bytes4",
          "internalType": "bytes4"
        },
        {
          "name": "enabled",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "configureGroup",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "members",
          "type": "address[]",
          "internalType": "address[]"
        },
        {
          "name": "enabled",
          "type": "bool",
          "internalType": "bool"
        },
        {
          "name": "expectedRevision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "eip712Domain",
      "inputs": [],
      "outputs": [
        {
          "name": "fields",
          "type": "bytes1",
          "internalType": "bytes1"
        },
        {
          "name": "name",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "version",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "chainId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "verifyingContract",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "salt",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "extensions",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "execute",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "call_",
          "type": "tuple",
          "internalType": "struct IKeelGroupManager.Call",
          "components": [
            {
              "name": "target",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "value",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "data",
              "type": "bytes",
              "internalType": "bytes"
            }
          ]
        },
        {
          "name": "deadline",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "signatures",
          "type": "tuple[]",
          "internalType": "struct KeelAccessGroups.Signature[]",
          "components": [
            {
              "name": "signer",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "signature",
              "type": "bytes",
              "internalType": "bytes"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "group",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "members",
          "type": "address[]",
          "internalType": "address[]"
        },
        {
          "name": "threshold",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "nonce",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "quorumActive",
          "type": "bool",
          "internalType": "bool"
        },
        {
          "name": "enabled",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "hasCapability",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "selector",
          "type": "bytes4",
          "internalType": "bytes4"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "manager",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "EIP712DomainChanged",
      "inputs": [],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "GroupAuthorized",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "digest",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "target",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "nonce",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "GroupCapabilityConfigured",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "target",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "selector",
          "type": "bytes4",
          "indexed": false,
          "internalType": "bytes4"
        },
        {
          "name": "enabled",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "GroupConfigured",
      "inputs": [
        {
          "name": "groupId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "revision",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        },
        {
          "name": "quorumActive",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        },
        {
          "name": "enabled",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        },
        {
          "name": "members",
          "type": "address[]",
          "indexed": false,
          "internalType": "address[]"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "GroupAccessDenied",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidGroup",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidMembers",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidShortString",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidSignatures",
      "inputs": []
    },
    {
      "type": "error",
      "name": "QuorumCannotBeDisabled",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ReentrancyGuardReentrantCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SignatureExpired",
      "inputs": []
    },
    {
      "type": "error",
      "name": "StaleGroupRevision",
      "inputs": []
    },
    {
      "type": "error",
      "name": "StringTooLong",
      "inputs": [
        {
          "name": "str",
          "type": "string",
          "internalType": "string"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedGovernance",
      "inputs": []
    }
  ]
} as const;
