// GENERATED BY `keel sync` — DO NOT EDIT BY HAND.
/** ABIs for the keel-hold module. */
export const ABIS = {
  "Ingot": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "stateMutability": "payable"
    }
  ],
  "KeelHold": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "manager_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "feeTreasury_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "initialSealFees",
          "type": "tuple",
          "internalType": "struct IKeelHoldSeal.SealFees",
          "components": [
            {
              "name": "perChunkWei",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "baseSealWei",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "stepSealWei",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "chunksPerStep",
              "type": "uint32",
              "internalType": "uint32"
            },
            {
              "name": "revision",
              "type": "uint32",
              "internalType": "uint32"
            }
          ]
        },
        {
          "name": "initialHarnessFeeWei",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "DESCRIPTOR_MAGIC",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes4",
          "internalType": "bytes4"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "DESCRIPTOR_VERSION",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "castSlug",
      "inputs": [
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [
        {
          "name": "slugId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "pointer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "castSlugFor",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [
        {
          "name": "slugId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "pointer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "castSlugs",
      "inputs": [
        {
          "name": "payloads",
          "type": "bytes[]",
          "internalType": "bytes[]"
        }
      ],
      "outputs": [
        {
          "name": "slugIds",
          "type": "bytes32[]",
          "internalType": "bytes32[]"
        },
        {
          "name": "pointers",
          "type": "address[]",
          "internalType": "address[]"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "castSlugsFor",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "payloads",
          "type": "bytes[]",
          "internalType": "bytes[]"
        }
      ],
      "outputs": [
        {
          "name": "slugIds",
          "type": "bytes32[]",
          "internalType": "bytes32[]"
        },
        {
          "name": "pointers",
          "type": "address[]",
          "internalType": "address[]"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "configureHarnessFees",
      "inputs": [
        {
          "name": "expectedRevision",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "registrationWei",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "configureLimits",
      "inputs": [
        {
          "name": "expectedRevision",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "maxSlugBytes",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "maxBatchSlugs",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "maxChildrenPerObject",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "maxReadDepth",
          "type": "uint32",
          "internalType": "uint32"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "configureSealFees",
      "inputs": [
        {
          "name": "expectedRevision",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "perChunkWei",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "baseSealWei",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "stepSealWei",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "chunksPerStep",
          "type": "uint32",
          "internalType": "uint32"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "descriptorPointer",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "pointer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "feeExempt",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "exempt",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "feeTreasury",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "flatSlugCount",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getObject",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct KeelHold.ObjectRecord",
          "components": [
            {
              "name": "digest",
              "type": "bytes32",
              "internalType": "bytes32"
            },
            {
              "name": "indexDigest",
              "type": "bytes32",
              "internalType": "bytes32"
            },
            {
              "name": "descriptorPointer",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "byteLength",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "storedByteLength",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "slugCount",
              "type": "uint32",
              "internalType": "uint32"
            },
            {
              "name": "compression",
              "type": "uint8",
              "internalType": "enum KeelHold.Compression"
            },
            {
              "name": "composite",
              "type": "bool",
              "internalType": "bool"
            },
            {
              "name": "exists",
              "type": "bool",
              "internalType": "bool"
            },
            {
              "name": "mediaType",
              "type": "string",
              "internalType": "string"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getObjectPartIds",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "offset",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "limit",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "result",
          "type": "bytes32[]",
          "internalType": "bytes32[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getObjectSlugPointers",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "offset",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "limit",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "result",
          "type": "address[]",
          "internalType": "address[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getSlug",
      "inputs": [
        {
          "name": "slugId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "harnessFees",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct IKeelHoldHarness.HarnessFees",
          "components": [
            {
              "name": "registrationWei",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "revision",
              "type": "uint32",
              "internalType": "uint32"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "harnessRegistered",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "renderer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "registered",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "haulObject",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "initWeld",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "slugCount",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "executor",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "expectedFeeRevision",
          "type": "uint32",
          "internalType": "uint32"
        }
      ],
      "outputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "isSealed",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "limits",
      "inputs": [],
      "outputs": [
        {
          "name": "maxSlugBytes",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "maxBatchSlugs",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "maxChildrenPerObject",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "maxReadDepth",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "manager",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "objectExists",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "preparedTokenURIEnvelopeValid",
      "inputs": [
        {
          "name": "prefix",
          "type": "bytes",
          "internalType": "bytes"
        },
        {
          "name": "suffix",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "quoteHarness",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "renderer",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "payer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "fee",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "revision",
          "type": "uint32",
          "internalType": "uint32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "quoteWeld",
      "inputs": [
        {
          "name": "slugCount",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "payer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "fee",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "revision",
          "type": "uint32",
          "internalType": "uint32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "readSlug",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "index",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        },
        {
          "name": "hasNext",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "registerHarness",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "renderer",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "expectedRevision",
          "type": "uint32",
          "internalType": "uint32"
        }
      ],
      "outputs": [],
      "stateMutability": "payable"
    },
    {
      "type": "function",
      "name": "requireHarness",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "renderer",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "requireSystemsActive",
      "inputs": [
        {
          "name": "mask",
          "type": "uint192",
          "internalType": "uint192"
        }
      ],
      "outputs": [],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "sealFees",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct IKeelHoldSeal.SealFees",
          "components": [
            {
              "name": "perChunkWei",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "baseSealWei",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "stepSealWei",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "chunksPerStep",
              "type": "uint32",
              "internalType": "uint32"
            },
            {
              "name": "revision",
              "type": "uint32",
              "internalType": "uint32"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "sealObject",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "sealRequired",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "setFeeExempt",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "exempt",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "slugPointer",
      "inputs": [
        {
          "name": "slugId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "weldComposite",
      "inputs": [
        {
          "name": "partObjectIds",
          "type": "bytes32[]",
          "internalType": "bytes32[]"
        },
        {
          "name": "digest",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "byteLength",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "mediaType",
          "type": "string",
          "internalType": "string"
        }
      ],
      "outputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "weldIntent",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct IKeelHoldSeal.WeldIntent",
          "components": [
            {
              "name": "executor",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "slugCount",
              "type": "uint32",
              "internalType": "uint32"
            },
            {
              "name": "remainingSlugs",
              "type": "uint32",
              "internalType": "uint32"
            },
            {
              "name": "complete",
              "type": "bool",
              "internalType": "bool"
            },
            {
              "name": "objectId",
              "type": "bytes32",
              "internalType": "bytes32"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "weldIntentId",
      "inputs": [
        {
          "name": "payer",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "executor",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "weldObject",
      "inputs": [
        {
          "name": "slugIds",
          "type": "bytes32[]",
          "internalType": "bytes32[]"
        },
        {
          "name": "digest",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "byteLength",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "compression",
          "type": "uint8",
          "internalType": "enum KeelHold.Compression"
        },
        {
          "name": "mediaType",
          "type": "string",
          "internalType": "string"
        }
      ],
      "outputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "FeeExemptionSet",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "exempt",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "HarnessFeesConfigured",
      "inputs": [
        {
          "name": "registrationWei",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        },
        {
          "name": "revision",
          "type": "uint32",
          "indexed": false,
          "internalType": "uint32"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "HarnessRegistered",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "renderer",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "payer",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "fee",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "LimitsConfigured",
      "inputs": [
        {
          "name": "revision",
          "type": "uint64",
          "indexed": true,
          "internalType": "uint64"
        },
        {
          "name": "packedLimits",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "ObjectSealed",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "intentId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "slugCount",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "ObjectWelded",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "digest",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "indexDigest",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "descriptorPointer",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "metadata",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        },
        {
          "name": "mediaType",
          "type": "string",
          "indexed": false,
          "internalType": "string"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SealFeesConfigured",
      "inputs": [
        {
          "name": "packedFees",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "SlugCast",
      "inputs": [
        {
          "name": "slugId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "pointer",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "byteLength",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "WeldInitiated",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "objectId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "payer",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "executor",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "slugCount",
          "type": "uint32",
          "indexed": false,
          "internalType": "uint32"
        },
        {
          "name": "fee",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "CompressedObjectReadUnsupported",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EmptyBatch",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EmptyObject",
      "inputs": []
    },
    {
      "type": "error",
      "name": "EmptySlug",
      "inputs": []
    },
    {
      "type": "error",
      "name": "FeeTransferFailed",
      "inputs": []
    },
    {
      "type": "error",
      "name": "HarnessRegistrationRequired",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "renderer",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "IncorrectHarnessFee",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "required",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "IncorrectSealFee",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "required",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "IntentAlreadyOpened",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ]
    },
    {
      "type": "error",
      "name": "IntentComplete",
      "inputs": []
    },
    {
      "type": "error",
      "name": "IntentCountMismatch",
      "inputs": [
        {
          "name": "actual",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "planned",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "IntentRequired",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidByteLength",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidDescriptor",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidDigest",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidFeeRecipient",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidHarness",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidIntent",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidLimits",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidManager",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidMediaType",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidSealFees",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ObjectMissing",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ]
    },
    {
      "type": "error",
      "name": "ObjectReadLengthMismatch",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ReadDepthExceeded",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SealRequired",
      "inputs": [
        {
          "name": "objectId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ]
    },
    {
      "type": "error",
      "name": "SliceOutOfBounds",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SlugAllowanceExceeded",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "remaining",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "SlugMissing",
      "inputs": [
        {
          "name": "slugId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ]
    },
    {
      "type": "error",
      "name": "SlugTooLarge",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "maximum",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "StaleHarnessFeeRevision",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "current",
          "type": "uint32",
          "internalType": "uint32"
        }
      ]
    },
    {
      "type": "error",
      "name": "StaleLimitsRevision",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "current",
          "type": "uint64",
          "internalType": "uint64"
        }
      ]
    },
    {
      "type": "error",
      "name": "StaleSealFeeRevision",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint32",
          "internalType": "uint32"
        },
        {
          "name": "current",
          "type": "uint32",
          "internalType": "uint32"
        }
      ]
    },
    {
      "type": "error",
      "name": "TooManyBatchSlugs",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "maximum",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "TooManyChildren",
      "inputs": [
        {
          "name": "supplied",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "maximum",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedGovernance",
      "inputs": []
    },
    {
      "type": "error",
      "name": "UnauthorizedUploader",
      "inputs": []
    },
    {
      "type": "error",
      "name": "WrongObjectKind",
      "inputs": []
    }
  ],
  "KeelIndex": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "admin",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "DEFAULT_ADMIN_ROLE",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "REGISTRAR_ROLE",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "activateCollectionRevision",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "activateTokenRevision",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "activePresentation",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "manifestURI",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "manifestDigest",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "activeRevision",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct KeelIndex.RevisionView",
          "components": [
            {
              "name": "manifestURI",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "manifestDigest",
              "type": "bytes32",
              "internalType": "bytes32"
            },
            {
              "name": "revision",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "parentRevision",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "compatibilityMin",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "compatibilityMax",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "activationTime",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "policy",
              "type": "uint8",
              "internalType": "enum KeelIndex.RevisionPolicy"
            },
            {
              "name": "frozen",
              "type": "bool",
              "internalType": "bool"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "claimCollection",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "collectionController",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "controller",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "freezeCollection",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "freezeToken",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getRoleAdmin",
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "grantRole",
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "hasRole",
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "presentationMatches",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "manifestDigest",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "publishCollectionRevision",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "manifestURI",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "manifestDigest",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "parentRevision",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "compatibilityMin",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "compatibilityMax",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "policy",
          "type": "uint8",
          "internalType": "enum KeelIndex.RevisionPolicy"
        },
        {
          "name": "activationTime",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "publishTokenRevision",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "manifestURI",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "manifestDigest",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "parentRevision",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "compatibilityMin",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "compatibilityMax",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "policy",
          "type": "uint8",
          "internalType": "enum KeelIndex.RevisionPolicy"
        },
        {
          "name": "activationTime",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "registerCollection",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "controller",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "renounceRole",
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "callerConfirmation",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "revisionOf",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "tokenSpecific",
          "type": "bool",
          "internalType": "bool"
        },
        {
          "name": "revision",
          "type": "uint64",
          "internalType": "uint64"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct KeelIndex.RevisionView",
          "components": [
            {
              "name": "manifestURI",
              "type": "string",
              "internalType": "string"
            },
            {
              "name": "manifestDigest",
              "type": "bytes32",
              "internalType": "bytes32"
            },
            {
              "name": "revision",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "parentRevision",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "compatibilityMin",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "compatibilityMax",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "activationTime",
              "type": "uint64",
              "internalType": "uint64"
            },
            {
              "name": "policy",
              "type": "uint8",
              "internalType": "enum KeelIndex.RevisionPolicy"
            },
            {
              "name": "frozen",
              "type": "bool",
              "internalType": "bool"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "revokeRole",
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "scopeStatus",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "tokenSpecific",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "outputs": [
        {
          "name": "latest",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "active",
          "type": "uint64",
          "internalType": "uint64"
        },
        {
          "name": "frozen",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "setCollectionController",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "controller",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "supportsInterface",
      "inputs": [
        {
          "name": "interfaceId",
          "type": "bytes4",
          "internalType": "bytes4"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "event",
      "name": "CollectionControllerUpdated",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "previousController",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "controller",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "CollectionRegistered",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "controller",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "RevisionActivated",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "tokenSpecific",
          "type": "bool",
          "indexed": true,
          "internalType": "bool"
        },
        {
          "name": "revision",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "RevisionPublished",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "tokenSpecific",
          "type": "bool",
          "indexed": true,
          "internalType": "bool"
        },
        {
          "name": "revision",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        },
        {
          "name": "parentRevision",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        },
        {
          "name": "manifestDigest",
          "type": "bytes32",
          "indexed": false,
          "internalType": "bytes32"
        },
        {
          "name": "manifestURI",
          "type": "string",
          "indexed": false,
          "internalType": "string"
        },
        {
          "name": "policy",
          "type": "uint8",
          "indexed": false,
          "internalType": "uint8"
        },
        {
          "name": "activationTime",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "RoleAdminChanged",
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "previousAdminRole",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "newAdminRole",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "RoleGranted",
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "account",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "sender",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "RoleRevoked",
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "account",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "sender",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "ScopePermanentlyFrozen",
      "inputs": [
        {
          "name": "collection",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "indexed": true,
          "internalType": "uint256"
        },
        {
          "name": "tokenSpecific",
          "type": "bool",
          "indexed": true,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AccessControlBadConfirmation",
      "inputs": []
    },
    {
      "type": "error",
      "name": "AccessControlUnauthorizedAccount",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "neededRole",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ]
    },
    {
      "type": "error",
      "name": "CollectionAlreadyRegistered",
      "inputs": []
    },
    {
      "type": "error",
      "name": "CollectionNotRegistered",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidActivationTime",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidCompatibility",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidManifest",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidParent",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidPolicy",
      "inputs": []
    },
    {
      "type": "error",
      "name": "PendingRevisionExists",
      "inputs": []
    },
    {
      "type": "error",
      "name": "RevisionMissing",
      "inputs": []
    },
    {
      "type": "error",
      "name": "RevisionNotReady",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ScopeFrozen",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Unauthorized",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ZeroAddress",
      "inputs": []
    }
  ]
} as const;
