import {readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gzipSync,gunzipSync,brotliCompressSync,brotliDecompressSync,constants} from 'node:zlib';
import {planKeelAssetPresentation} from '../../../packages/sdk/dist/presentation.js';
const root=new URL('../',import.meta.url),original=new URL('original/',root);const manifest=JSON.parse(await readFile(new URL('manifest.json',original)));
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
async function walk(dir,prefix=''){const out=[];for(const e of await readdir(dir,{withFileTypes:true})){const p=prefix+e.name;if(e.isDirectory())out.push(...await walk(new URL(e.name+'/',dir),p+'/'));else out.push(p);}return out;}
const files=await walk(original),records=[],errors=[];for(const path of files){const bytes=await readFile(new URL(path,original));const sha256=hash(bytes),expected=manifest.paths[path]?.id;if(expected&&expected!==sha256)errors.push({path,expected,actual:sha256});const gzip=gzipSync(bytes,{level:9});const brotli=brotliCompressSync(bytes,{params:{[constants.BROTLI_PARAM_QUALITY]:6}});if(!gunzipSync(gzip).equals(bytes)||!brotliDecompressSync(brotli).equals(bytes))throw Error('Lossless compression roundtrip failed');records.push({path,bytes:bytes.length,sha256,manifestMatch:expected?expected===sha256:null,gzipBytes:gzip.length,brotliQ6Bytes:brotli.length,storageCandidate:gzip.length<bytes.length?'gzip':'none'});}
const edition1=records.filter(r=>/^data\/1\//.test(r.path));const playback=edition1.filter(r=>r.path.includes('/1600/'));const sum=(a,key)=>a.reduce((s,r)=>s+r[key],0);
const report={schema:'link2-source-audit@1',manifestFiles:Object.keys(manifest.paths).length,localFiles:records.length,matchedManifestFiles:records.filter(r=>r.manifestMatch===true).length,missingManifestFiles:Object.keys(manifest.paths).filter(p=>!files.includes(p)),errors,originalsUnchanged:errors.length===0,records,edition1:{files:edition1.length,playbackFiles:playback.length,originalBytes:sum(edition1,'bytes'),playbackBytes:sum(playback,'bytes'),gzipStoredBytes:edition1.reduce((s,r)=>s+Math.min(r.bytes,r.gzipBytes),0),presentation:planKeelAssetPresentation({originalByteLength:sum(edition1,'bytes'),compressedByteLength:edition1.reduce((s,r)=>s+Math.min(r.bytes,r.gzipBytes),0)})},brotliBinding:'Not selected: no receipt-backed decoder binding established.',publicationReady:false};
await writeFile(new URL('evidence/source-audit.json',root),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,records:undefined,missingManifestFiles:report.missingManifestFiles.length},null,2));if(errors.length)process.exitCode=1;
