import{readFile,writeFile,mkdir,readdir}from'node:fs/promises';
import{gzipSync,gunzipSync}from'node:zlib';
import{createIntegrity}from'@keel/protocol';
import{planKeelAssetPresentation}from'../../../packages/sdk/dist/presentation.js';
const root=new URL('../',import.meta.url),current=new URL('current/',root),out=new URL('prepared/',root);
const manifest=JSON.parse(await readFile(new URL('manifest.json',current)));const capture=JSON.parse(await readFile(new URL('evidence/current-source.json',root)));const captures=new Map(capture.records.map(r=>[r.path,r.sha256]));
async function walk(dir,prefix=''){let r=[];for(const e of await readdir(dir,{withFileTypes:true})){const p=prefix+e.name;r.push(...e.isDirectory()?await walk(new URL(e.name+'/',dir),p+'/'):[p]);}return r;}
await mkdir(new URL('objects/',out),{recursive:true});const resources=[];
for(const path of await walk(current)){const bytes=await readFile(new URL(path,current));const integrity=await createIntegrity(bytes);const expected=captures.get(path)||manifest.paths[path]?.id;if(integrity.digest!=='0x'+expected)throw Error('Source changed: '+path);const gz=gzipSync(bytes,{level:9});const compressed=gz.length<bytes.length;const stored=compressed?gz:bytes;if(!(compressed?gunzipSync(stored):stored).equals(bytes))throw Error('Roundtrip mismatch: '+path);const objectPath=`objects/${integrity.digest.slice(2)}.${compressed?'gz':'bin'}`;await writeFile(new URL(objectPath,out),stored);resources.push({path,role:path==='index.html'?'entrypoint':path.startsWith('js/')?'script':path.startsWith('data/')?'image':'data',integrity,compression:compressed?'gzip':'none',storedIntegrity:await createIntegrity(stored),objectPath,objectId:null,sourceBinding:captures.has(path)?'current-token-url-capture':'image-manifest-sha256'});}
const originalByteLength=resources.reduce((s,r)=>s+r.integrity.byteLength,0),compressedByteLength=resources.reduce((s,r)=>s+r.storedIntegrity.byteLength,0);const missing=Object.keys(manifest.paths).filter(p=>!resources.some(r=>r.path===p));const plan={schema:'link2-local-preparation@1',source:{chainId:1,contract:capture.contract,tokenId:capture.tokenId,base:capture.base},target:{chainId:11155111,network:'sepolia',selection:'MCP Studio default; no publication requested'},presentation:planKeelAssetPresentation({originalByteLength,compressedByteLength}),resources,scope:{fullEdition1:true,otherEditions:'first/middle/last frame samples only',defaultEditionSelection:'unchanged original random selection; preview explicitly requests id=1',missingManifestFiles:missing.length},blockers:['Existing MP4 encoder module not found in local sources or default live library.','Remaining collection assets have not been downloaded.','Embedded code-manifest mismatch requires provenance review; current token-linked code is pinned separately.','Canonical shell and encoder receipt-backed bindings not verified.'],sourceManifestMismatches:capture.manifestMismatches,mp4:{implemented:false,verified:false},publicationReady:false};await writeFile(new URL('inventory.json',out),JSON.stringify(plan,null,2)+'\n');console.log(JSON.stringify({resourceCount:resources.length,originalByteLength,compressedByteLength,savedBytes:originalByteLength-compressedByteLength,percentSaved:(originalByteLength-compressedByteLength)/originalByteLength*100,presentation:plan.presentation.mode,scope:plan.scope,blockers:plan.blockers},null,2));
